// Code generated by yunka domain; DO NOT EDIT.

package rpc

import (
	"context"
	application "github.com/hvritual/biz/internal/device/application"
	domain "github.com/hvritual/biz/internal/device/domain"
	pb "github.com/hvritual/biz/internal/device/transport/rpc/pb"
	grpc "google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type DeviceGRPCBridge struct {
	pb.UnimplementedDeviceServiceServer
	service application.Service
}

func Register(registrar grpc.ServiceRegistrar, service application.Service) {
	pb.RegisterDeviceServiceServer(registrar, &DeviceGRPCBridge{service: service})
}
func (server *DeviceGRPCBridge) CreateDevice(ctx context.Context, request *pb.CreateDeviceRequest) (*pb.Device, error) {
	output, err := server.service.CreateDevice(ctx, application.CreateDeviceInput{CreatedBy: request.GetCreatedBy(), Name: request.GetName(), Serial: request.GetSerial(), SiteID: request.GetSiteId()})
	if err != nil {
		return nil, err
	}
	return deviceToProto(output.Value), nil
}
func (server *DeviceGRPCBridge) GetDevice(ctx context.Context, request *pb.GetDeviceRequest) (*pb.Device, error) {
	output, err := server.service.GetDevice(ctx, application.GetDeviceInput{ID: request.GetId()})
	if err != nil {
		return nil, err
	}
	return deviceToProto(output.Value), nil
}
func (server *DeviceGRPCBridge) ListDevices(ctx context.Context, request *pb.ListDevicesRequest) (*pb.ListDevicesResponse, error) {
	output, err := server.service.ListDevices(ctx, application.ListDevicesInput{Limit: int(request.GetLimit()), Offset: int(request.GetOffset())})
	if err != nil {
		return nil, err
	}
	response := &pb.ListDevicesResponse{Items: make([]*pb.Device, 0, len(output.Items))}
	for _, item := range output.Items {
		response.Items = append(response.Items, deviceToProto(item))
	}
	return response, nil
}
func (server *DeviceGRPCBridge) UpdateDevice(ctx context.Context, request *pb.UpdateDeviceRequest) (*pb.Device, error) {
	output, err := server.service.UpdateDevice(ctx, application.UpdateDeviceInput{ID: request.GetId(), Version: request.GetVersion(), CreatedBy: request.GetCreatedBy(), Name: request.GetName(), Serial: request.GetSerial(), SiteID: request.GetSiteId()})
	if err != nil {
		return nil, err
	}
	return deviceToProto(output.Value), nil
}
func (server *DeviceGRPCBridge) DeleteDevice(ctx context.Context, request *pb.DeleteDeviceRequest) (*pb.DeleteDeviceResponse, error) {
	if err := server.service.DeleteDevice(ctx, application.DeleteDeviceInput{ID: request.GetId(), Version: request.GetVersion()}); err != nil {
		return nil, err
	}
	return &pb.DeleteDeviceResponse{}, nil
}
func deviceToProto(value domain.Device) *pb.Device {
	result := &pb.Device{Id: value.ID, Version: value.Version, CreatedAt: timestamppb.New(value.CreatedAt), UpdatedAt: timestamppb.New(value.UpdatedAt), TenantId: value.TenantID, CreatedBy: value.CreatedBy, Name: value.Name, Serial: value.Serial, SiteId: value.SiteID}
	return result
}
