// Code generated by yunka domain; DO NOT EDIT.

package ports

import (
	"context"
	"errors"
	domain "github.com/hvritual/biz/internal/device/domain"
)

var (
	ErrNotFound = errors.New("domain repository: not found")
	ErrConflict = errors.New("domain repository: version conflict")
)

type DeviceRepository interface {
	Create(context.Context, *domain.Device) error
	Get(context.Context, string) (domain.Device, error)
	List(context.Context, int, int) ([]domain.Device, error)
	Update(context.Context, *domain.Device, uint64) error
	Delete(context.Context, string, uint64) error
}
type Repositories struct {
	Device DeviceRepository
}
