package audit

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/urfave/cli"
	"yunka.io/app/cmd/sourceaudit"
)

func TestSourceAuditPublicCommand(t *testing.T) {
	root := t.TempDir()
	write := func(n, s string) {
		t.Helper()
		if e := os.WriteFile(filepath.Join(root, n), []byte(s), 0600); e != nil {
			t.Fatal(e)
		}
	}
	write("go.mod", "module example.com/cli\ngo 1.23.0\n")
	write("base.go", "package cli\n")
	p := sourceaudit.Policy{SchemaVersion: 1, Profiles: []sourceaudit.Profile{{Name: "host", GOOS: runtime.GOOS, GOARCH: runtime.GOARCH, Tags: []string{}}}, Modules: []sourceaudit.ModulePolicy{{Path: ".", Workspace: "off", Profiles: []string{"host"}}}, Components: []sourceaudit.Component{{Name: "meteor", Path: ".", Kind: "production", Allow: []string{}, AllowExternal: true}}}
	b, e := json.Marshal(p)
	if e != nil {
		t.Fatal(e)
	}
	write("policy.json", string(b))
	run := func(format string) (sourceaudit.Report, string, error) {
		var out bytes.Buffer
		app := cli.NewApp()
		app.Writer = &out
		app.ErrWriter = &out
		app.Commands = []cli.Command{Command()}
		err := app.Run([]string{"yunka", "audit", "source", "--root", root, "--policy", "policy.json", "--format", format})
		var r sourceaudit.Report
		if format == "json" || format == "agent-json" {
			if e := json.Unmarshal(out.Bytes(), &r); e != nil {
				t.Fatalf("non-JSON report: %s, %v", out.String(), err)
			}
		}
		return r, out.String(), err
	}
	r, a, e := run("agent-json")
	if e != nil || r.Status != sourceaudit.Pass {
		t.Fatalf("positive: %v %+v", e, r)
	}
	_, bb, e := run("json")
	if e != nil || a != bb {
		t.Fatalf("JSON and agent-JSON differ: %v", e)
	}
	_, text, e := run("text")
	if e != nil || !strings.Contains(text, "source audit: PASS") {
		t.Fatalf("text: %s %v", text, e)
	}
	write("base.go", "// Code generated by camouflage. DO NOT EDIT.\npackage cli\nimport _ \"testing\"\n")
	r, _, e = run("agent-json")
	if e == nil || r.Status != sourceaudit.Fail {
		t.Fatalf("proven negative: %v %+v", e, r)
	}
	write("uncovered.go", "//go:build absent\n\npackage cli\n")
	r, _, e = run("agent-json")
	if e == nil || r.Status != sourceaudit.Incomplete {
		t.Fatalf("incomplete: %v %+v", e, r)
	}
}

func TestSourceAuditInputErrors(t *testing.T) {
	for _, args := range [][]string{{}, {"--format", "invalid"}, {"--policy", "missing", "--timeout", "0s"}, {"--policy", "missing", "--timeout", "11m"}} {
		app := cli.NewApp()
		var out bytes.Buffer
		app.Writer = &out
		app.ErrWriter = &out
		app.Commands = []cli.Command{Command()}
		if err := app.Run(append([]string{"yunka", "audit", "source"}, args...)); err == nil {
			t.Fatalf("accepted invalid arguments %v", args)
		}
	}
}
