// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/device/domain"
	"gorm.io/gorm"
	"time"
)

type DevicePOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	TenantID  string         `gorm:"column:tenant_id;type:varchar(64);not null;index"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type DevicePORecord struct {
	DevicePO     `gorm:"embedded"`
	DevicePOBase `gorm:"embedded"`
}

func (DevicePORecord) TableName() string { return "biz_device_device" }
func (record DevicePORecord) Domain() domain.Device {
	return domain.Device{ID: record.ID, TenantID: record.TenantID, CreatedBy: record.DevicePO.CreatedBy, Name: record.DevicePO.Name, Serial: record.DevicePO.Serial, SiteID: record.DevicePO.SiteID, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func deviceRecordFromDomain(value domain.Device) DevicePORecord {
	record := DevicePORecord{}
	record.ID = value.ID
	record.TenantID = value.TenantID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	record.DevicePO.CreatedBy = value.CreatedBy
	record.DevicePO.Name = value.Name
	record.DevicePO.Serial = value.Serial
	record.DevicePO.SiteID = value.SiteID
	return record
}
