// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	"context"
	"errors"
	domain "github.com/hvritual/biz/internal/device/domain"
	ports "github.com/hvritual/biz/internal/device/ports"
	"gorm.io/gorm"
	"time"
	identity "yunka.io/framework/core/identity"
	"yunka.io/framework/requestscope"
)

func AutoMigrate(ctx context.Context, database *gorm.DB) error {
	if database == nil {
		return errors.New("domain persistence: database is required")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	return database.WithContext(ctx).AutoMigrate(&DevicePORecord{})
}
func trustedTenant(ctx context.Context) (string, error) {
	principal, ok := identity.FromContext(ctx)
	if !ok || !principal.Authenticated || principal.TenantID == "" {
		return "", errors.New("domain persistence: trusted tenant principal is required")
	}
	return principal.TenantID, nil
}

type DeviceRepository struct{ database *gorm.DB }

func (repository *DeviceRepository) scoped(ctx context.Context) (*gorm.DB, error) {
	query := repository.database.WithContext(ctx)
	tenantID, err := trustedTenant(ctx)
	if err != nil {
		return nil, err
	}
	query = query.Where("tenant_id = ?", tenantID)
	return query, nil
}
func (repository *DeviceRepository) Create(ctx context.Context, value *domain.Device) error {
	if value == nil {
		return errors.New("domain persistence: value is required")
	}
	tenantID, err := trustedTenant(ctx)
	if err != nil {
		return err
	}
	value.TenantID = tenantID
	if value.Version == 0 {
		value.Version = 1
	}
	now := time.Now().UTC()
	if value.CreatedAt.IsZero() {
		value.CreatedAt = now
	}
	value.UpdatedAt = now
	record := deviceRecordFromDomain(*value)
	if err := repository.database.WithContext(ctx).Create(&record).Error; err != nil {
		return err
	}
	*value = record.Domain()
	return nil
}
func (repository *DeviceRepository) Get(ctx context.Context, id string) (domain.Device, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return domain.Device{}, err
	}
	var record DevicePORecord
	if err := query.Where("id = ?", id).First(&record).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return domain.Device{}, ports.ErrNotFound
		}
		return domain.Device{}, err
	}
	return record.Domain(), nil
}
func (repository *DeviceRepository) List(ctx context.Context, limit, offset int) ([]domain.Device, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return nil, err
	}
	var rows []DevicePORecord
	if limit > 0 {
		query = query.Limit(limit)
	}
	if offset > 0 {
		query = query.Offset(offset)
	}
	if err := query.Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	result := make([]domain.Device, 0, len(rows))
	for _, row := range rows {
		result = append(result, row.Domain())
	}
	return result, nil
}
func (repository *DeviceRepository) Update(ctx context.Context, value *domain.Device, expected uint64) error {
	if value == nil || value.ID == "" {
		return errors.New("domain persistence: update value/id is required")
	}
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	updates := map[string]any{"version": gorm.Expr("version + 1"), "updated_at": time.Now().UTC(), "created_by": value.CreatedBy, "name": value.Name, "serial": value.Serial, "site_id": value.SiteID}
	result := query.Model(&DevicePORecord{}).Where("id = ? AND version = ?", value.ID, expected).Updates(updates)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func (repository *DeviceRepository) Delete(ctx context.Context, id string, expected uint64) error {
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	result := query.Where("id = ? AND version = ?", id, expected).Delete(&DevicePORecord{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func NewScopeFactory(database *gorm.DB) (requestscope.ScopeFactory[ports.Repositories], error) {
	unit, err := requestscope.NewGORMFactory(database, nil)
	if err != nil {
		return nil, err
	}
	return requestscope.NewFactory(requestscope.FactoryOptions[ports.Repositories]{UnitOfWork: unit, Repositories: requestscope.GORMRepositories(func(ctx context.Context, transaction *gorm.DB) (ports.Repositories, error) {
		repositories := ports.Repositories{}
		repositories.Device = &DeviceRepository{database: transaction}
		return repositories, nil
	})})
}
