// Code generated by yunka domain; DO NOT EDIT.

package domain

import "time"

type Device struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenantId"`
	CreatedBy string    `json:"createdBy"`
	Name      string    `json:"name"`
	Serial    string    `json:"serial"`
	SiteID    string    `json:"siteId"`
	Version   uint64    `json:"version"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
