// Code generated by yunka domain; DO NOT EDIT.

package application

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	domain "github.com/hvritual/biz/internal/site/domain"
	ports "github.com/hvritual/biz/internal/site/ports"
	"time"
	"yunka.io/framework/requestscope"
)

type Service interface {
	CreateSite(context.Context, CreateSiteInput) (SiteOutput, error)
	GetSite(context.Context, GetSiteInput) (SiteOutput, error)
	ListSites(context.Context, ListSitesInput) (ListSitesOutput, error)
	UpdateSite(context.Context, UpdateSiteInput) (SiteOutput, error)
	DeleteSite(context.Context, DeleteSiteInput) error
}

type CreateSiteInput struct {
	Name string `json:"name"`
}
type GetSiteInput struct{ ID string }
type ListSitesInput struct {
	Limit  int
	Offset int
}
type UpdateSiteInput struct {
	ID      string
	Version uint64
	Name    string `json:"name"`
}
type DeleteSiteInput struct {
	ID      string
	Version uint64
}
type SiteOutput struct {
	Value domain.Site `json:"value"`
}
type ListSitesOutput struct {
	Items []domain.Site `json:"items"`
}

type DefaultService struct {
	scopes requestscope.ScopeFactory[ports.Repositories]
}

func NewService(scopes requestscope.ScopeFactory[ports.Repositories]) (*DefaultService, error) {
	if scopes == nil {
		return nil, errors.New("domain application: request scope factory is required")
	}
	return &DefaultService{scopes: scopes}, nil
}

func (service *DefaultService) CreateSite(ctx context.Context, input CreateSiteInput) (SiteOutput, error) {
	value := domain.Site{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC(), Name: input.Name}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Site, error) {
		if err := scope.Repositories().Site.Create(scope.Context(), &value); err != nil {
			return domain.Site{}, err
		}
		return value, nil
	})
	return SiteOutput{Value: created}, err
}
func (service *DefaultService) GetSite(ctx context.Context, input GetSiteInput) (SiteOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Site, error) {
		return scope.Repositories().Site.Get(scope.Context(), input.ID)
	})
	return SiteOutput{Value: value}, err
}
func (service *DefaultService) ListSites(ctx context.Context, input ListSitesInput) (ListSitesOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.Site, error) {
		return scope.Repositories().Site.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListSitesOutput{Items: items}, err
}
func (service *DefaultService) UpdateSite(ctx context.Context, input UpdateSiteInput) (SiteOutput, error) {
	value := domain.Site{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC(), Name: input.Name}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Site, error) {
		repository := scope.Repositories().Site
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.Site{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return SiteOutput{Value: updated}, err
}
func (service *DefaultService) DeleteSite(ctx context.Context, input DeleteSiteInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().Site.Delete(scope.Context(), input.ID, input.Version)
	})
}

func newID() string {
	var value [16]byte
	if _, err := rand.Read(value[:]); err != nil {
		panic(err)
	}
	return hex.EncodeToString(value[:])
}
