package generator

import (
	"github.com/golang/protobuf/protoc-gen-go/descriptor"
	plugin "github.com/golang/protobuf/protoc-gen-go/plugin"
	"strings"
	"yunka-rpc/protobuf/pkg/generator"
)

/**
* @Description: TODO
* @date 2019-07-25
* @version V1.0
 */
type mig struct {
	generator.Base
	filesHandled int
}

// BmGenerator BM generator.
func MigGenerator() *mig {
	t := &mig{}
	return t
}

// Generate ...
func (t *mig) Generate(in *plugin.CodeGeneratorRequest) *plugin.CodeGeneratorResponse {
	t.Setup(in)
	resp := new(plugin.CodeGeneratorResponse)
	switch t.Params.ImportMap["type"] {
	case "method":
		t.generateMethod(resp)
	case "client":
		t.generateClient(resp)
	case "grpc":
		t.generateGrpcInvokeServer(resp)
	case "server":
		t.generateServer(resp)
	case "memory":
		t.generateMemoryInvokeServer(resp)
	case "handle":
		t.generateServerHandle(resp)
	default:
		t.generateServer(resp)
		t.generateMethod(resp)
		t.generateClient(resp)

	}

	// Showtime! Generate the response.

	return resp
}
func (t *mig) generateFileHeader(file *descriptor.FileDescriptorProto, pkgName string) {
	t.P("// Code generated by yunka-rpc ", generator.Version, ", DO NOT EDIT.")
	t.P("// source: ", file.GetName())
	t.P()
	if t.filesHandled == 0 {
		// doc for the first file
		t.P("/*")
		t.P("Package ", t.GenPkgName, " is a generated rpc stub package.")
		t.P()
		comment, err := t.Reg.FileComments(file)
		if err == nil && comment.Leading != "" {
			for _, line := range strings.Split(comment.Leading, "\n") {
				line = strings.TrimPrefix(line, " ")
				// ensure we don't escape from the block comment
				line = strings.Replace(line, "*/", "* /", -1)
				t.P(line)
			}
			t.P()
		}
		t.P("It is generated from these files:")
		for _, f := range t.GenFiles {
			t.P("\t", f.GetName())
		}
		t.P("*/")
	}
	t.P(`package `, pkgName)
	t.P()
}
