// Code generated by yunka domain; DO NOT EDIT.

package ports

import (
	"context"
	"errors"
	domain "github.com/hvritual/biz/internal/site/domain"
)

var (
	ErrNotFound = errors.New("domain repository: not found")
	ErrConflict = errors.New("domain repository: version conflict")
)

type SiteRepository interface {
	Create(context.Context, *domain.Site) error
	Get(context.Context, string) (domain.Site, error)
	List(context.Context, int, int) ([]domain.Site, error)
	Update(context.Context, *domain.Site, uint64) error
	Delete(context.Context, string, uint64) error
}
type Repositories struct {
	Site SiteRepository
}
