// Code generated by yunka domain; DO NOT EDIT.

package domain

import "time"

type MemberRole struct {
	ID        string    `json:"id"`
	Version   uint64    `json:"version"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
