// Code generated by yunka domain; DO NOT EDIT.

package domain

import "time"

type RolePermission struct {
	ID         string    `json:"id"`
	DataScope  string    `json:"dataScope"`
	Permission string    `json:"permission"`
	Version    uint64    `json:"version"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}
