package ownership

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestBuildDerivesSafeMutationBoundariesWithoutOwnershipManifest(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "go.mod"), "module example.com/demo\n\ngo 1.25.0\n")
	mustWrite(t, filepath.Join(root, "contracts", "proto", "demo.proto"), "syntax = \"proto3\";\n")
	mustWrite(t, filepath.Join(root, ".yunka", "protobuf-go.json"), "{\n  \"schemaVersion\": 1,\n  \"files\": [\"internal/pb/demo.pb.go\"]\n}\n")
	mustWrite(t, filepath.Join(root, "internal", "tenant", "application", "existing_gen.go"), "// Code generated by yunka contract; DO NOT EDIT.\npackage application\n")

	paths := []string{
		"contracts/proto/demo.proto",
		"contracts/proto/new.proto",
		"contracts/generated/operation-plans.json",
		"internal/pb/demo.pb.go",
		"internal/tenant/application/existing_gen.go",
		"internal/tenant/application/zz_yunka_future_gen.go",
		"internal/tenant/application/suspend.go",
		".yunka/providers.json",
		".yunka/protobuf-go.json",
		"README.md",
	}
	report, err := Build(root, paths)
	if err != nil {
		t.Fatal(err)
	}
	if report.SchemaVersion != SchemaVersion {
		t.Fatalf("schemaVersion=%d", report.SchemaVersion)
	}

	assertDecision(t, report, "contracts/proto/demo.proto", "developer-contract", MutationEditable, true)
	assertDecision(t, report, "contracts/proto/new.proto", "developer-contract", MutationEditable, true)
	assertDecision(t, report, "contracts/generated/operation-plans.json", "yunka-generator", MutationGeneratedOnly, false)
	assertDecision(t, report, "internal/pb/demo.pb.go", "protobuf-go-generator", MutationGeneratedOnly, false)
	assertDecision(t, report, "internal/tenant/application/existing_gen.go", "yunka-generator", MutationGeneratedOnly, false)
	assertDecision(t, report, "internal/tenant/application/zz_yunka_future_gen.go", "yunka-generator", MutationGeneratedOnly, false)
	assertDecision(t, report, "internal/tenant/application/suspend.go", "developer-code", MutationEditable, true)
	assertDecision(t, report, ".yunka/providers.json", "developer-config", MutationEditable, true)
	assertDecision(t, report, ".yunka/protobuf-go.json", "protobuf-go-generator", MutationGeneratedOnly, false)
	assertDecision(t, report, "README.md", "unclassified", MutationUnclassified, false)

	jsonOutput, err := render(report, "json")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(jsonOutput, `"safeAutoEdit": true`) || !strings.Contains(jsonOutput, `"mutation": "generated-only"`) {
		t.Fatalf("unexpected json output:\n%s", jsonOutput)
	}
}

func TestBuildRejectsOutsideProjectPath(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "go.mod"), "module example.com/demo\n\ngo 1.25.0\n")
	if err := os.MkdirAll(filepath.Join(root, "contracts", "proto"), 0o755); err != nil {
		t.Fatal(err)
	}
	outside := filepath.Join(filepath.Dir(root), "outside.go")
	report, err := Build(root, []string{outside})
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Decisions) != 1 || report.Decisions[0].SafeAutoEdit || report.Decisions[0].Mutation != MutationUnclassified {
		t.Fatalf("outside decision=%#v", report.Decisions)
	}
}

func TestBuildIsDeterministicAndSorted(t *testing.T) {
	root := t.TempDir()
	mustWrite(t, filepath.Join(root, "go.mod"), "module example.com/demo\n\ngo 1.25.0\n")
	if err := os.MkdirAll(filepath.Join(root, "contracts", "proto"), 0o755); err != nil {
		t.Fatal(err)
	}
	first, err := Build(root, []string{"internal/z.go", "internal/a.go"})
	if err != nil {
		t.Fatal(err)
	}
	second, err := Build(root, []string{"internal/z.go", "internal/a.go"})
	if err != nil {
		t.Fatal(err)
	}
	if len(first.Decisions) != 2 || first.Decisions[0].Path != "internal/a.go" || first.Decisions[1].Path != "internal/z.go" {
		t.Fatalf("decisions not sorted: %#v", first.Decisions)
	}
	left, _ := render(first, "json")
	right, _ := render(second, "json")
	if left != right {
		t.Fatal("ownership JSON is not deterministic")
	}
}

func assertDecision(t *testing.T, report Report, path, owner, mutation string, safe bool) {
	t.Helper()
	for _, item := range report.Decisions {
		if item.Path != path {
			continue
		}
		if item.Owner != owner || item.Mutation != mutation || item.SafeAutoEdit != safe {
			t.Fatalf("decision %s=%#v want owner=%s mutation=%s safe=%t", path, item, owner, mutation, safe)
		}
		return
	}
	t.Fatalf("decision not found for %s", path)
}

func mustWrite(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}
