// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: legacy/api.proto

package legacy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Api struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsCheck       bool                   `protobuf:"varint,3,opt,name=isCheck,proto3" json:"isCheck,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Api) Reset() {
	*x = Api{}
	mi := &file_legacy_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Api) ProtoMessage() {}

func (x *Api) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Api.ProtoReflect.Descriptor instead.
func (*Api) Descriptor() ([]byte, []int) {
	return file_legacy_api_proto_rawDescGZIP(), []int{0}
}

func (x *Api) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Api) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Api) GetIsCheck() bool {
	if x != nil {
		return x.IsCheck
	}
	return false
}

type GetApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuids         []string               `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiRequest) Reset() {
	*x = GetApiRequest{}
	mi := &file_legacy_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiRequest) ProtoMessage() {}

func (x *GetApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiRequest.ProtoReflect.Descriptor instead.
func (*GetApiRequest) Descriptor() ([]byte, []int) {
	return file_legacy_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetApiRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type GetApiReponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apis          []*Api                 `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApiReponse) Reset() {
	*x = GetApiReponse{}
	mi := &file_legacy_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApiReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApiReponse) ProtoMessage() {}

func (x *GetApiReponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApiReponse.ProtoReflect.Descriptor instead.
func (*GetApiReponse) Descriptor() ([]byte, []int) {
	return file_legacy_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetApiReponse) GetApis() []*Api {
	if x != nil {
		return x.Apis
	}
	return nil
}

type FindAllRuntimeAPIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRuntimeAPIRequest) Reset() {
	*x = FindAllRuntimeAPIRequest{}
	mi := &file_legacy_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRuntimeAPIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRuntimeAPIRequest) ProtoMessage() {}

func (x *FindAllRuntimeAPIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRuntimeAPIRequest.ProtoReflect.Descriptor instead.
func (*FindAllRuntimeAPIRequest) Descriptor() ([]byte, []int) {
	return file_legacy_api_proto_rawDescGZIP(), []int{3}
}

type FindAllRuntimeAPIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apis          []*RuntimeApi          `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRuntimeAPIResponse) Reset() {
	*x = FindAllRuntimeAPIResponse{}
	mi := &file_legacy_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRuntimeAPIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRuntimeAPIResponse) ProtoMessage() {}

func (x *FindAllRuntimeAPIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRuntimeAPIResponse.ProtoReflect.Descriptor instead.
func (*FindAllRuntimeAPIResponse) Descriptor() ([]byte, []int) {
	return file_legacy_api_proto_rawDescGZIP(), []int{4}
}

func (x *FindAllRuntimeAPIResponse) GetApis() []*RuntimeApi {
	if x != nil {
		return x.Apis
	}
	return nil
}

var File_legacy_api_proto protoreflect.FileDescriptor

const file_legacy_api_proto_rawDesc = "" +
	"\n" +
	"\x10legacy/api.proto\x1a\x17legacy/api_common.proto\"G\n" +
	"\x03Api\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aisCheck\x18\x03 \x01(\bR\aisCheck\"%\n" +
	"\rGetApiRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\")\n" +
	"\rGetApiReponse\x12\x18\n" +
	"\x04apis\x18\x01 \x03(\v2\x04.ApiR\x04apis\"\x1a\n" +
	"\x18FindAllRuntimeAPIRequest\"<\n" +
	"\x19FindAllRuntimeAPIResponse\x12\x1f\n" +
	"\x04apis\x18\x01 \x03(\v2\v.RuntimeApiR\x04apis2\x88\x01\n" +
	"\n" +
	"ApiService\x12.\n" +
	"\fGetApiByUUID\x12\x0e.GetApiRequest\x1a\x0e.GetApiReponse\x12J\n" +
	"\x11FindAllRuntimeAPI\x12\x19.FindAllRuntimeAPIRequest\x1a\x1a.FindAllRuntimeAPIResponseB$Z\"yunka.io/pkg/rpcmeta/legacy;legacyb\x06proto3"

var (
	file_legacy_api_proto_rawDescOnce sync.Once
	file_legacy_api_proto_rawDescData []byte
)

func file_legacy_api_proto_rawDescGZIP() []byte {
	file_legacy_api_proto_rawDescOnce.Do(func() {
		file_legacy_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_legacy_api_proto_rawDesc), len(file_legacy_api_proto_rawDesc)))
	})
	return file_legacy_api_proto_rawDescData
}

var file_legacy_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_legacy_api_proto_goTypes = []any{
	(*Api)(nil),                       // 0: Api
	(*GetApiRequest)(nil),             // 1: GetApiRequest
	(*GetApiReponse)(nil),             // 2: GetApiReponse
	(*FindAllRuntimeAPIRequest)(nil),  // 3: FindAllRuntimeAPIRequest
	(*FindAllRuntimeAPIResponse)(nil), // 4: FindAllRuntimeAPIResponse
	(*RuntimeApi)(nil),                // 5: RuntimeApi
}
var file_legacy_api_proto_depIdxs = []int32{
	0, // 0: GetApiReponse.apis:type_name -> Api
	5, // 1: FindAllRuntimeAPIResponse.apis:type_name -> RuntimeApi
	1, // 2: ApiService.GetApiByUUID:input_type -> GetApiRequest
	3, // 3: ApiService.FindAllRuntimeAPI:input_type -> FindAllRuntimeAPIRequest
	2, // 4: ApiService.GetApiByUUID:output_type -> GetApiReponse
	4, // 5: ApiService.FindAllRuntimeAPI:output_type -> FindAllRuntimeAPIResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_legacy_api_proto_init() }
func file_legacy_api_proto_init() {
	if File_legacy_api_proto != nil {
		return
	}
	file_legacy_api_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_legacy_api_proto_rawDesc), len(file_legacy_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_legacy_api_proto_goTypes,
		DependencyIndexes: file_legacy_api_proto_depIdxs,
		MessageInfos:      file_legacy_api_proto_msgTypes,
	}.Build()
	File_legacy_api_proto = out.File
	file_legacy_api_proto_goTypes = nil
	file_legacy_api_proto_depIdxs = nil
}
