// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: legacy/api_common.proto

package legacy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// @Description: TODO
// @date 2019-07-16
// @version V1.0
type CallType int32

const (
	CallType_CallReserve CallType = 0
	CallType_HttpCall    CallType = 1
	CallType_RpcCall     CallType = 2
)

// Enum value maps for CallType.
var (
	CallType_name = map[int32]string{
		0: "CallReserve",
		1: "HttpCall",
		2: "RpcCall",
	}
	CallType_value = map[string]int32{
		"CallReserve": 0,
		"HttpCall":    1,
		"RpcCall":     2,
	}
)

func (x CallType) Enum() *CallType {
	p := new(CallType)
	*p = x
	return p
}

func (x CallType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallType) Descriptor() protoreflect.EnumDescriptor {
	return file_legacy_api_common_proto_enumTypes[0].Descriptor()
}

func (CallType) Type() protoreflect.EnumType {
	return &file_legacy_api_common_proto_enumTypes[0]
}

func (x CallType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallType.Descriptor instead.
func (CallType) EnumDescriptor() ([]byte, []int) {
	return file_legacy_api_common_proto_rawDescGZIP(), []int{0}
}

type AuthStatus int32

const (
	AuthStatus_AuthReserve AuthStatus = 0
	AuthStatus_NotAuth     AuthStatus = 1
	AuthStatus_NeedAuth    AuthStatus = 2
)

// Enum value maps for AuthStatus.
var (
	AuthStatus_name = map[int32]string{
		0: "AuthReserve",
		1: "NotAuth",
		2: "NeedAuth",
	}
	AuthStatus_value = map[string]int32{
		"AuthReserve": 0,
		"NotAuth":     1,
		"NeedAuth":    2,
	}
)

func (x AuthStatus) Enum() *AuthStatus {
	p := new(AuthStatus)
	*p = x
	return p
}

func (x AuthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_legacy_api_common_proto_enumTypes[1].Descriptor()
}

func (AuthStatus) Type() protoreflect.EnumType {
	return &file_legacy_api_common_proto_enumTypes[1]
}

func (x AuthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthStatus.Descriptor instead.
func (AuthStatus) EnumDescriptor() ([]byte, []int) {
	return file_legacy_api_common_proto_rawDescGZIP(), []int{1}
}

type ForceCheckStatus int32

const (
	ForceCheckStatus_ForceReserve   ForceCheckStatus = 0
	ForceCheckStatus_NotForceCheck  ForceCheckStatus = 1
	ForceCheckStatus_NeedForceCheck ForceCheckStatus = 2
)

// Enum value maps for ForceCheckStatus.
var (
	ForceCheckStatus_name = map[int32]string{
		0: "ForceReserve",
		1: "NotForceCheck",
		2: "NeedForceCheck",
	}
	ForceCheckStatus_value = map[string]int32{
		"ForceReserve":   0,
		"NotForceCheck":  1,
		"NeedForceCheck": 2,
	}
)

func (x ForceCheckStatus) Enum() *ForceCheckStatus {
	p := new(ForceCheckStatus)
	*p = x
	return p
}

func (x ForceCheckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForceCheckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_legacy_api_common_proto_enumTypes[2].Descriptor()
}

func (ForceCheckStatus) Type() protoreflect.EnumType {
	return &file_legacy_api_common_proto_enumTypes[2]
}

func (x ForceCheckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForceCheckStatus.Descriptor instead.
func (ForceCheckStatus) EnumDescriptor() ([]byte, []int) {
	return file_legacy_api_common_proto_rawDescGZIP(), []int{2}
}

type ViewRoleLevel int32

const (
	ViewRoleLevel_GOD          ViewRoleLevel = 0
	ViewRoleLevel_Developer    ViewRoleLevel = 1
	ViewRoleLevel_Operater     ViewRoleLevel = 3
	ViewRoleLevel_Entrepreneur ViewRoleLevel = 5
	ViewRoleLevel_Employee     ViewRoleLevel = 67
	ViewRoleLevel_User         ViewRoleLevel = 9
	ViewRoleLevel_Visitor      ViewRoleLevel = 11
)

// Enum value maps for ViewRoleLevel.
var (
	ViewRoleLevel_name = map[int32]string{
		0:  "GOD",
		1:  "Developer",
		3:  "Operater",
		5:  "Entrepreneur",
		67: "Employee",
		9:  "User",
		11: "Visitor",
	}
	ViewRoleLevel_value = map[string]int32{
		"GOD":          0,
		"Developer":    1,
		"Operater":     3,
		"Entrepreneur": 5,
		"Employee":     67,
		"User":         9,
		"Visitor":      11,
	}
)

func (x ViewRoleLevel) Enum() *ViewRoleLevel {
	p := new(ViewRoleLevel)
	*p = x
	return p
}

func (x ViewRoleLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ViewRoleLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_legacy_api_common_proto_enumTypes[3].Descriptor()
}

func (ViewRoleLevel) Type() protoreflect.EnumType {
	return &file_legacy_api_common_proto_enumTypes[3]
}

func (x ViewRoleLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ViewRoleLevel.Descriptor instead.
func (ViewRoleLevel) EnumDescriptor() ([]byte, []int) {
	return file_legacy_api_common_proto_rawDescGZIP(), []int{3}
}

type IsCompose int32

const (
	IsCompose_IsComposeReserve IsCompose = 0
	IsCompose_OneRequest       IsCompose = 1
	IsCompose_Compose          IsCompose = 2
)

// Enum value maps for IsCompose.
var (
	IsCompose_name = map[int32]string{
		0: "IsComposeReserve",
		1: "OneRequest",
		2: "Compose",
	}
	IsCompose_value = map[string]int32{
		"IsComposeReserve": 0,
		"OneRequest":       1,
		"Compose":          2,
	}
)

func (x IsCompose) Enum() *IsCompose {
	p := new(IsCompose)
	*p = x
	return p
}

func (x IsCompose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IsCompose) Descriptor() protoreflect.EnumDescriptor {
	return file_legacy_api_common_proto_enumTypes[4].Descriptor()
}

func (IsCompose) Type() protoreflect.EnumType {
	return &file_legacy_api_common_proto_enumTypes[4]
}

func (x IsCompose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IsCompose.Descriptor instead.
func (IsCompose) EnumDescriptor() ([]byte, []int) {
	return file_legacy_api_common_proto_rawDescGZIP(), []int{4}
}

type IsCommon int32

const (
	IsCommon_Common       IsCommon = 0
	IsCommon_PrivateCheck IsCommon = 1
)

// Enum value maps for IsCommon.
var (
	IsCommon_name = map[int32]string{
		0: "Common",
		1: "PrivateCheck",
	}
	IsCommon_value = map[string]int32{
		"Common":       0,
		"PrivateCheck": 1,
	}
)

func (x IsCommon) Enum() *IsCommon {
	p := new(IsCommon)
	*p = x
	return p
}

func (x IsCommon) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IsCommon) Descriptor() protoreflect.EnumDescriptor {
	return file_legacy_api_common_proto_enumTypes[5].Descriptor()
}

func (IsCommon) Type() protoreflect.EnumType {
	return &file_legacy_api_common_proto_enumTypes[5]
}

func (x IsCommon) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IsCommon.Descriptor instead.
func (IsCommon) EnumDescriptor() ([]byte, []int) {
	return file_legacy_api_common_proto_rawDescGZIP(), []int{5}
}

type RuntimeApi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ServerUuid    string                 `protobuf:"bytes,2,opt,name=serverUuid,proto3" json:"serverUuid,omitempty"`
	ServerName    string                 `protobuf:"bytes,3,opt,name=serverName,proto3" json:"serverName,omitempty"`
	Uri           string                 `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	EngName       string                 `protobuf:"bytes,6,opt,name=engName,proto3" json:"engName,omitempty"`
	CallType      CallType               `protobuf:"varint,7,opt,name=callType,proto3,enum=CallType" json:"callType,omitempty"`
	IsAuth        AuthStatus             `protobuf:"varint,8,opt,name=isAuth,proto3,enum=AuthStatus" json:"isAuth,omitempty"`
	IsForceCheck  ForceCheckStatus       `protobuf:"varint,9,opt,name=isForceCheck,proto3,enum=ForceCheckStatus" json:"isForceCheck,omitempty"`
	ViewRoleLevel ViewRoleLevel          `protobuf:"varint,10,opt,name=viewRoleLevel,proto3,enum=ViewRoleLevel" json:"viewRoleLevel,omitempty"`
	IsCompose     IsCompose              `protobuf:"varint,11,opt,name=isCompose,proto3,enum=IsCompose" json:"isCompose,omitempty"`
	IsCommon      IsCommon               `protobuf:"varint,12,opt,name=isCommon,proto3,enum=IsCommon" json:"isCommon,omitempty"`
	Composes      []*RuntimeApi          `protobuf:"bytes,13,rep,name=composes,proto3" json:"composes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeApi) Reset() {
	*x = RuntimeApi{}
	mi := &file_legacy_api_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeApi) ProtoMessage() {}

func (x *RuntimeApi) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_api_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeApi.ProtoReflect.Descriptor instead.
func (*RuntimeApi) Descriptor() ([]byte, []int) {
	return file_legacy_api_common_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeApi) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RuntimeApi) GetServerUuid() string {
	if x != nil {
		return x.ServerUuid
	}
	return ""
}

func (x *RuntimeApi) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RuntimeApi) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RuntimeApi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeApi) GetEngName() string {
	if x != nil {
		return x.EngName
	}
	return ""
}

func (x *RuntimeApi) GetCallType() CallType {
	if x != nil {
		return x.CallType
	}
	return CallType_CallReserve
}

func (x *RuntimeApi) GetIsAuth() AuthStatus {
	if x != nil {
		return x.IsAuth
	}
	return AuthStatus_AuthReserve
}

func (x *RuntimeApi) GetIsForceCheck() ForceCheckStatus {
	if x != nil {
		return x.IsForceCheck
	}
	return ForceCheckStatus_ForceReserve
}

func (x *RuntimeApi) GetViewRoleLevel() ViewRoleLevel {
	if x != nil {
		return x.ViewRoleLevel
	}
	return ViewRoleLevel_GOD
}

func (x *RuntimeApi) GetIsCompose() IsCompose {
	if x != nil {
		return x.IsCompose
	}
	return IsCompose_IsComposeReserve
}

func (x *RuntimeApi) GetIsCommon() IsCommon {
	if x != nil {
		return x.IsCommon
	}
	return IsCommon_Common
}

func (x *RuntimeApi) GetComposes() []*RuntimeApi {
	if x != nil {
		return x.Composes
	}
	return nil
}

type CircuitCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloseTime     int32                  `protobuf:"varint,1,opt,name=CloseTime,proto3" json:"CloseTime,omitempty"`
	CheckPeriod   int32                  `protobuf:"varint,2,opt,name=CheckPeriod,proto3" json:"CheckPeriod,omitempty"`
	LimitPercent  int32                  `protobuf:"varint,3,opt,name=LimitPercent,proto3" json:"LimitPercent,omitempty"`
	HalfOpen      int32                  `protobuf:"varint,4,opt,name=HalfOpen,proto3" json:"HalfOpen,omitempty"`
	HalfClose     int32                  `protobuf:"varint,5,opt,name=HalfClose,proto3" json:"HalfClose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitCfg) Reset() {
	*x = CircuitCfg{}
	mi := &file_legacy_api_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitCfg) ProtoMessage() {}

func (x *CircuitCfg) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_api_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitCfg.ProtoReflect.Descriptor instead.
func (*CircuitCfg) Descriptor() ([]byte, []int) {
	return file_legacy_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *CircuitCfg) GetCloseTime() int32 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

func (x *CircuitCfg) GetCheckPeriod() int32 {
	if x != nil {
		return x.CheckPeriod
	}
	return 0
}

func (x *CircuitCfg) GetLimitPercent() int32 {
	if x != nil {
		return x.LimitPercent
	}
	return 0
}

func (x *CircuitCfg) GetHalfOpen() int32 {
	if x != nil {
		return x.HalfOpen
	}
	return 0
}

func (x *CircuitCfg) GetHalfClose() int32 {
	if x != nil {
		return x.HalfClose
	}
	return 0
}

type ServerNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpPort        string                 `protobuf:"bytes,1,opt,name=ipPort,proto3" json:"ipPort,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Qps           int32                  `protobuf:"varint,3,opt,name=qps,proto3" json:"qps,omitempty"`
	Circuit       *CircuitCfg            `protobuf:"bytes,4,opt,name=Circuit,proto3" json:"Circuit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerNode) Reset() {
	*x = ServerNode{}
	mi := &file_legacy_api_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerNode) ProtoMessage() {}

func (x *ServerNode) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_api_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerNode.ProtoReflect.Descriptor instead.
func (*ServerNode) Descriptor() ([]byte, []int) {
	return file_legacy_api_common_proto_rawDescGZIP(), []int{2}
}

func (x *ServerNode) GetIpPort() string {
	if x != nil {
		return x.IpPort
	}
	return ""
}

func (x *ServerNode) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ServerNode) GetQps() int32 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *ServerNode) GetCircuit() *CircuitCfg {
	if x != nil {
		return x.Circuit
	}
	return nil
}

var File_legacy_api_common_proto protoreflect.FileDescriptor

const file_legacy_api_common_proto_rawDesc = "" +
	"\n" +
	"\x17legacy/api_common.proto\"\xd3\x03\n" +
	"\n" +
	"RuntimeApi\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1e\n" +
	"\n" +
	"serverUuid\x18\x02 \x01(\tR\n" +
	"serverUuid\x12\x1e\n" +
	"\n" +
	"serverName\x18\x03 \x01(\tR\n" +
	"serverName\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\aengName\x18\x06 \x01(\tR\aengName\x12%\n" +
	"\bcallType\x18\a \x01(\x0e2\t.CallTypeR\bcallType\x12#\n" +
	"\x06isAuth\x18\b \x01(\x0e2\v.AuthStatusR\x06isAuth\x125\n" +
	"\fisForceCheck\x18\t \x01(\x0e2\x11.ForceCheckStatusR\fisForceCheck\x124\n" +
	"\rviewRoleLevel\x18\n" +
	" \x01(\x0e2\x0e.ViewRoleLevelR\rviewRoleLevel\x12(\n" +
	"\tisCompose\x18\v \x01(\x0e2\n" +
	".IsComposeR\tisCompose\x12%\n" +
	"\bisCommon\x18\f \x01(\x0e2\t.IsCommonR\bisCommon\x12'\n" +
	"\bcomposes\x18\r \x03(\v2\v.RuntimeApiR\bcomposes\"\xaa\x01\n" +
	"\n" +
	"CircuitCfg\x12\x1c\n" +
	"\tCloseTime\x18\x01 \x01(\x05R\tCloseTime\x12 \n" +
	"\vCheckPeriod\x18\x02 \x01(\x05R\vCheckPeriod\x12\"\n" +
	"\fLimitPercent\x18\x03 \x01(\x05R\fLimitPercent\x12\x1a\n" +
	"\bHalfOpen\x18\x04 \x01(\x05R\bHalfOpen\x12\x1c\n" +
	"\tHalfClose\x18\x05 \x01(\x05R\tHalfClose\"q\n" +
	"\n" +
	"ServerNode\x12\x16\n" +
	"\x06ipPort\x18\x01 \x01(\tR\x06ipPort\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03qps\x18\x03 \x01(\x05R\x03qps\x12%\n" +
	"\aCircuit\x18\x04 \x01(\v2\v.CircuitCfgR\aCircuit*6\n" +
	"\bCallType\x12\x0f\n" +
	"\vCallReserve\x10\x00\x12\f\n" +
	"\bHttpCall\x10\x01\x12\v\n" +
	"\aRpcCall\x10\x02*8\n" +
	"\n" +
	"AuthStatus\x12\x0f\n" +
	"\vAuthReserve\x10\x00\x12\v\n" +
	"\aNotAuth\x10\x01\x12\f\n" +
	"\bNeedAuth\x10\x02*K\n" +
	"\x10ForceCheckStatus\x12\x10\n" +
	"\fForceReserve\x10\x00\x12\x11\n" +
	"\rNotForceCheck\x10\x01\x12\x12\n" +
	"\x0eNeedForceCheck\x10\x02*l\n" +
	"\rViewRoleLevel\x12\a\n" +
	"\x03GOD\x10\x00\x12\r\n" +
	"\tDeveloper\x10\x01\x12\f\n" +
	"\bOperater\x10\x03\x12\x10\n" +
	"\fEntrepreneur\x10\x05\x12\f\n" +
	"\bEmployee\x10C\x12\b\n" +
	"\x04User\x10\t\x12\v\n" +
	"\aVisitor\x10\v*>\n" +
	"\tIsCompose\x12\x14\n" +
	"\x10IsComposeReserve\x10\x00\x12\x0e\n" +
	"\n" +
	"OneRequest\x10\x01\x12\v\n" +
	"\aCompose\x10\x02*(\n" +
	"\bIsCommon\x12\n" +
	"\n" +
	"\x06Common\x10\x00\x12\x10\n" +
	"\fPrivateCheck\x10\x01B$Z\"yunka.io/pkg/rpcmeta/legacy;legacyb\x06proto3"

var (
	file_legacy_api_common_proto_rawDescOnce sync.Once
	file_legacy_api_common_proto_rawDescData []byte
)

func file_legacy_api_common_proto_rawDescGZIP() []byte {
	file_legacy_api_common_proto_rawDescOnce.Do(func() {
		file_legacy_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_legacy_api_common_proto_rawDesc), len(file_legacy_api_common_proto_rawDesc)))
	})
	return file_legacy_api_common_proto_rawDescData
}

var file_legacy_api_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_legacy_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_legacy_api_common_proto_goTypes = []any{
	(CallType)(0),         // 0: CallType
	(AuthStatus)(0),       // 1: AuthStatus
	(ForceCheckStatus)(0), // 2: ForceCheckStatus
	(ViewRoleLevel)(0),    // 3: ViewRoleLevel
	(IsCompose)(0),        // 4: IsCompose
	(IsCommon)(0),         // 5: IsCommon
	(*RuntimeApi)(nil),    // 6: RuntimeApi
	(*CircuitCfg)(nil),    // 7: CircuitCfg
	(*ServerNode)(nil),    // 8: ServerNode
}
var file_legacy_api_common_proto_depIdxs = []int32{
	0, // 0: RuntimeApi.callType:type_name -> CallType
	1, // 1: RuntimeApi.isAuth:type_name -> AuthStatus
	2, // 2: RuntimeApi.isForceCheck:type_name -> ForceCheckStatus
	3, // 3: RuntimeApi.viewRoleLevel:type_name -> ViewRoleLevel
	4, // 4: RuntimeApi.isCompose:type_name -> IsCompose
	5, // 5: RuntimeApi.isCommon:type_name -> IsCommon
	6, // 6: RuntimeApi.composes:type_name -> RuntimeApi
	7, // 7: ServerNode.Circuit:type_name -> CircuitCfg
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_legacy_api_common_proto_init() }
func file_legacy_api_common_proto_init() {
	if File_legacy_api_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_legacy_api_common_proto_rawDesc), len(file_legacy_api_common_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_legacy_api_common_proto_goTypes,
		DependencyIndexes: file_legacy_api_common_proto_depIdxs,
		EnumInfos:         file_legacy_api_common_proto_enumTypes,
		MessageInfos:      file_legacy_api_common_proto_msgTypes,
	}.Build()
	File_legacy_api_common_proto = out.File
	file_legacy_api_common_proto_goTypes = nil
	file_legacy_api_common_proto_depIdxs = nil
}
