// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: legacy/api.proto

package legacy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApiService_GetApiByUUID_FullMethodName      = "/ApiService/GetApiByUUID"
	ApiService_FindAllRuntimeAPI_FullMethodName = "/ApiService/FindAllRuntimeAPI"
)

// ApiServiceClient is the client API for ApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiServiceClient interface {
	GetApiByUUID(ctx context.Context, in *GetApiRequest, opts ...grpc.CallOption) (*GetApiReponse, error)
	FindAllRuntimeAPI(ctx context.Context, in *FindAllRuntimeAPIRequest, opts ...grpc.CallOption) (*FindAllRuntimeAPIResponse, error)
}

type apiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiServiceClient(cc grpc.ClientConnInterface) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetApiByUUID(ctx context.Context, in *GetApiRequest, opts ...grpc.CallOption) (*GetApiReponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetApiReponse)
	err := c.cc.Invoke(ctx, ApiService_GetApiByUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) FindAllRuntimeAPI(ctx context.Context, in *FindAllRuntimeAPIRequest, opts ...grpc.CallOption) (*FindAllRuntimeAPIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAllRuntimeAPIResponse)
	err := c.cc.Invoke(ctx, ApiService_FindAllRuntimeAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiServiceServer is the server API for ApiService service.
// All implementations should embed UnimplementedApiServiceServer
// for forward compatibility.
type ApiServiceServer interface {
	GetApiByUUID(context.Context, *GetApiRequest) (*GetApiReponse, error)
	FindAllRuntimeAPI(context.Context, *FindAllRuntimeAPIRequest) (*FindAllRuntimeAPIResponse, error)
}

// UnimplementedApiServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServiceServer struct{}

func (UnimplementedApiServiceServer) GetApiByUUID(context.Context, *GetApiRequest) (*GetApiReponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApiByUUID not implemented")
}
func (UnimplementedApiServiceServer) FindAllRuntimeAPI(context.Context, *FindAllRuntimeAPIRequest) (*FindAllRuntimeAPIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindAllRuntimeAPI not implemented")
}
func (UnimplementedApiServiceServer) testEmbeddedByValue() {}

// UnsafeApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServiceServer will
// result in compilation errors.
type UnsafeApiServiceServer interface {
	mustEmbedUnimplementedApiServiceServer()
}

func RegisterApiServiceServer(s grpc.ServiceRegistrar, srv ApiServiceServer) {
	// If the following call panics, it indicates UnimplementedApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiService_ServiceDesc, srv)
}

func _ApiService_GetApiByUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetApiByUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_GetApiByUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetApiByUUID(ctx, req.(*GetApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_FindAllRuntimeAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllRuntimeAPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).FindAllRuntimeAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiService_FindAllRuntimeAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).FindAllRuntimeAPI(ctx, req.(*FindAllRuntimeAPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiService_ServiceDesc is the grpc.ServiceDesc for ApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApiByUUID",
			Handler:    _ApiService_GetApiByUUID_Handler,
		},
		{
			MethodName: "FindAllRuntimeAPI",
			Handler:    _ApiService_FindAllRuntimeAPI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "legacy/api.proto",
}
