// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: legacy/common.proto

package legacy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Switch int32

const (
	Switch_Close Switch = 0
	Switch_Oopen Switch = 1
)

// Enum value maps for Switch.
var (
	Switch_name = map[int32]string{
		0: "Close",
		1: "Oopen",
	}
	Switch_value = map[string]int32{
		"Close": 0,
		"Oopen": 1,
	}
)

func (x Switch) Enum() *Switch {
	p := new(Switch)
	*p = x
	return p
}

func (x Switch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Switch) Descriptor() protoreflect.EnumDescriptor {
	return file_legacy_common_proto_enumTypes[0].Descriptor()
}

func (Switch) Type() protoreflect.EnumType {
	return &file_legacy_common_proto_enumTypes[0]
}

func (x Switch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Switch.Descriptor instead.
func (Switch) EnumDescriptor() ([]byte, []int) {
	return file_legacy_common_proto_rawDescGZIP(), []int{0}
}

type NotParamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotParamRequest) Reset() {
	*x = NotParamRequest{}
	mi := &file_legacy_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotParamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotParamRequest) ProtoMessage() {}

func (x *NotParamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotParamRequest.ProtoReflect.Descriptor instead.
func (*NotParamRequest) Descriptor() ([]byte, []int) {
	return file_legacy_common_proto_rawDescGZIP(), []int{0}
}

type NotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotResponse) Reset() {
	*x = NotResponse{}
	mi := &file_legacy_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotResponse) ProtoMessage() {}

func (x *NotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotResponse.ProtoReflect.Descriptor instead.
func (*NotResponse) Descriptor() ([]byte, []int) {
	return file_legacy_common_proto_rawDescGZIP(), []int{1}
}

var File_legacy_common_proto protoreflect.FileDescriptor

const file_legacy_common_proto_rawDesc = "" +
	"\n" +
	"\x13legacy/common.proto\"\x11\n" +
	"\x0fNotParamRequest\"\r\n" +
	"\vNotResponse*\x1e\n" +
	"\x06Switch\x12\t\n" +
	"\x05Close\x10\x00\x12\t\n" +
	"\x05Oopen\x10\x01B$Z\"github.com/hvritual/yunka.io/pkg/rpcmeta/legacy;legacyb\x06proto3"

var (
	file_legacy_common_proto_rawDescOnce sync.Once
	file_legacy_common_proto_rawDescData []byte
)

func file_legacy_common_proto_rawDescGZIP() []byte {
	file_legacy_common_proto_rawDescOnce.Do(func() {
		file_legacy_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_legacy_common_proto_rawDesc), len(file_legacy_common_proto_rawDesc)))
	})
	return file_legacy_common_proto_rawDescData
}

var file_legacy_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_legacy_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_legacy_common_proto_goTypes = []any{
	(Switch)(0),             // 0: Switch
	(*NotParamRequest)(nil), // 1: NotParamRequest
	(*NotResponse)(nil),     // 2: NotResponse
}
var file_legacy_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_legacy_common_proto_init() }
func file_legacy_common_proto_init() {
	if File_legacy_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_legacy_common_proto_rawDesc), len(file_legacy_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_legacy_common_proto_goTypes,
		DependencyIndexes: file_legacy_common_proto_depIdxs,
		EnumInfos:         file_legacy_common_proto_enumTypes,
		MessageInfos:      file_legacy_common_proto_msgTypes,
	}.Build()
	File_legacy_common_proto = out.File
	file_legacy_common_proto_goTypes = nil
	file_legacy_common_proto_depIdxs = nil
}
