// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: legacy/unit.proto

package legacy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleCanUse int32

const (
	ModuleCanUse_All    ModuleCanUse = 0
	ModuleCanUse_Mobile ModuleCanUse = 1
	ModuleCanUse_Web    ModuleCanUse = 2
)

// Enum value maps for ModuleCanUse.
var (
	ModuleCanUse_name = map[int32]string{
		0: "All",
		1: "Mobile",
		2: "Web",
	}
	ModuleCanUse_value = map[string]int32{
		"All":    0,
		"Mobile": 1,
		"Web":    2,
	}
)

func (x ModuleCanUse) Enum() *ModuleCanUse {
	p := new(ModuleCanUse)
	*p = x
	return p
}

func (x ModuleCanUse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleCanUse) Descriptor() protoreflect.EnumDescriptor {
	return file_legacy_unit_proto_enumTypes[0].Descriptor()
}

func (ModuleCanUse) Type() protoreflect.EnumType {
	return &file_legacy_unit_proto_enumTypes[0]
}

func (x ModuleCanUse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleCanUse.Descriptor instead.
func (ModuleCanUse) EnumDescriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{0}
}

type ModuleCommonStatus int32

const (
	ModuleCommonStatus_AllCanUse     ModuleCommonStatus = 0
	ModuleCommonStatus_KolCanUse     ModuleCommonStatus = 1
	ModuleCommonStatus_ServiceCanUse ModuleCommonStatus = 2
	ModuleCommonStatus_NotCommon     ModuleCommonStatus = 3
)

// Enum value maps for ModuleCommonStatus.
var (
	ModuleCommonStatus_name = map[int32]string{
		0: "AllCanUse",
		1: "KolCanUse",
		2: "ServiceCanUse",
		3: "NotCommon",
	}
	ModuleCommonStatus_value = map[string]int32{
		"AllCanUse":     0,
		"KolCanUse":     1,
		"ServiceCanUse": 2,
		"NotCommon":     3,
	}
)

func (x ModuleCommonStatus) Enum() *ModuleCommonStatus {
	p := new(ModuleCommonStatus)
	*p = x
	return p
}

func (x ModuleCommonStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleCommonStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_legacy_unit_proto_enumTypes[1].Descriptor()
}

func (ModuleCommonStatus) Type() protoreflect.EnumType {
	return &file_legacy_unit_proto_enumTypes[1]
}

func (x ModuleCommonStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleCommonStatus.Descriptor instead.
func (ModuleCommonStatus) EnumDescriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{1}
}

type BasicModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	WebRouterName string                 `protobuf:"bytes,5,opt,name=webRouterName,proto3" json:"webRouterName,omitempty"`
	MobilePage    string                 `protobuf:"bytes,6,opt,name=mobilePage,proto3" json:"mobilePage,omitempty"`
	CanUse        ModuleCanUse           `protobuf:"varint,7,opt,name=canUse,proto3,enum=ModuleCanUse" json:"canUse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicModule) Reset() {
	*x = BasicModule{}
	mi := &file_legacy_unit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicModule) ProtoMessage() {}

func (x *BasicModule) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicModule.ProtoReflect.Descriptor instead.
func (*BasicModule) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{0}
}

func (x *BasicModule) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BasicModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BasicModule) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *BasicModule) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *BasicModule) GetWebRouterName() string {
	if x != nil {
		return x.WebRouterName
	}
	return ""
}

func (x *BasicModule) GetMobilePage() string {
	if x != nil {
		return x.MobilePage
	}
	return ""
}

func (x *BasicModule) GetCanUse() ModuleCanUse {
	if x != nil {
		return x.CanUse
	}
	return ModuleCanUse_All
}

type SimpleModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	BasicFee      uint32                 `protobuf:"varint,6,opt,name=basicFee,proto3" json:"basicFee,omitempty"`
	UnitFee       uint32                 `protobuf:"varint,7,opt,name=unitFee,proto3" json:"unitFee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleModule) Reset() {
	*x = SimpleModule{}
	mi := &file_legacy_unit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleModule) ProtoMessage() {}

func (x *SimpleModule) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleModule.ProtoReflect.Descriptor instead.
func (*SimpleModule) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleModule) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SimpleModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleModule) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *SimpleModule) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *SimpleModule) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *SimpleModule) GetBasicFee() uint32 {
	if x != nil {
		return x.BasicFee
	}
	return 0
}

func (x *SimpleModule) GetUnitFee() uint32 {
	if x != nil {
		return x.UnitFee
	}
	return 0
}

type BasicModuleSort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Modules       []*BasicModule         `protobuf:"bytes,5,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicModuleSort) Reset() {
	*x = BasicModuleSort{}
	mi := &file_legacy_unit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicModuleSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicModuleSort) ProtoMessage() {}

func (x *BasicModuleSort) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicModuleSort.ProtoReflect.Descriptor instead.
func (*BasicModuleSort) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{2}
}

func (x *BasicModuleSort) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BasicModuleSort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BasicModuleSort) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *BasicModuleSort) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *BasicModuleSort) GetModules() []*BasicModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

type FindBasicModuleSortByMoudleUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleUUIDs   []string               `protobuf:"bytes,1,rep,name=moduleUUIDs,proto3" json:"moduleUUIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindBasicModuleSortByMoudleUUIDRequest) Reset() {
	*x = FindBasicModuleSortByMoudleUUIDRequest{}
	mi := &file_legacy_unit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindBasicModuleSortByMoudleUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBasicModuleSortByMoudleUUIDRequest) ProtoMessage() {}

func (x *FindBasicModuleSortByMoudleUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBasicModuleSortByMoudleUUIDRequest.ProtoReflect.Descriptor instead.
func (*FindBasicModuleSortByMoudleUUIDRequest) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{3}
}

func (x *FindBasicModuleSortByMoudleUUIDRequest) GetModuleUUIDs() []string {
	if x != nil {
		return x.ModuleUUIDs
	}
	return nil
}

type FindBasicModuleSortByMoudleUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleSort    []*BasicModuleSort     `protobuf:"bytes,1,rep,name=moduleSort,proto3" json:"moduleSort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindBasicModuleSortByMoudleUUIDResponse) Reset() {
	*x = FindBasicModuleSortByMoudleUUIDResponse{}
	mi := &file_legacy_unit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindBasicModuleSortByMoudleUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindBasicModuleSortByMoudleUUIDResponse) ProtoMessage() {}

func (x *FindBasicModuleSortByMoudleUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindBasicModuleSortByMoudleUUIDResponse.ProtoReflect.Descriptor instead.
func (*FindBasicModuleSortByMoudleUUIDResponse) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{4}
}

func (x *FindBasicModuleSortByMoudleUUIDResponse) GetModuleSort() []*BasicModuleSort {
	if x != nil {
		return x.ModuleSort
	}
	return nil
}

type FindModuleApiUuidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindModuleApiUuidRequest) Reset() {
	*x = FindModuleApiUuidRequest{}
	mi := &file_legacy_unit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindModuleApiUuidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindModuleApiUuidRequest) ProtoMessage() {}

func (x *FindModuleApiUuidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindModuleApiUuidRequest.ProtoReflect.Descriptor instead.
func (*FindModuleApiUuidRequest) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{5}
}

func (x *FindModuleApiUuidRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type FindModuleApiUuidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []string               `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindModuleApiUuidResponse) Reset() {
	*x = FindModuleApiUuidResponse{}
	mi := &file_legacy_unit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindModuleApiUuidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindModuleApiUuidResponse) ProtoMessage() {}

func (x *FindModuleApiUuidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindModuleApiUuidResponse.ProtoReflect.Descriptor instead.
func (*FindModuleApiUuidResponse) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{6}
}

func (x *FindModuleApiUuidResponse) GetUuid() []string {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type ModuleUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []string               `protobuf:"bytes,1,rep,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleUUIDRequest) Reset() {
	*x = ModuleUUIDRequest{}
	mi := &file_legacy_unit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleUUIDRequest) ProtoMessage() {}

func (x *ModuleUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleUUIDRequest.ProtoReflect.Descriptor instead.
func (*ModuleUUIDRequest) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{7}
}

func (x *ModuleUUIDRequest) GetUuid() []string {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type BaseModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*BasicModule         `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseModuleResponse) Reset() {
	*x = BaseModuleResponse{}
	mi := &file_legacy_unit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseModuleResponse) ProtoMessage() {}

func (x *BaseModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseModuleResponse.ProtoReflect.Descriptor instead.
func (*BaseModuleResponse) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{8}
}

func (x *BaseModuleResponse) GetModules() []*BasicModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

type FindModulesByModuleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ModuleCommonStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=ModuleCommonStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindModulesByModuleStatusRequest) Reset() {
	*x = FindModulesByModuleStatusRequest{}
	mi := &file_legacy_unit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindModulesByModuleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindModulesByModuleStatusRequest) ProtoMessage() {}

func (x *FindModulesByModuleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindModulesByModuleStatusRequest.ProtoReflect.Descriptor instead.
func (*FindModulesByModuleStatusRequest) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{9}
}

func (x *FindModulesByModuleStatusRequest) GetStatus() ModuleCommonStatus {
	if x != nil {
		return x.Status
	}
	return ModuleCommonStatus_AllCanUse
}

type SimpleModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*SimpleModule        `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleModuleResponse) Reset() {
	*x = SimpleModuleResponse{}
	mi := &file_legacy_unit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleModuleResponse) ProtoMessage() {}

func (x *SimpleModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleModuleResponse.ProtoReflect.Descriptor instead.
func (*SimpleModuleResponse) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{10}
}

func (x *SimpleModuleResponse) GetModules() []*SimpleModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

type FindAllModuleSortResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Modules        []*SimpleModule        `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	ModuleSortName []*BasicModuleSort     `protobuf:"bytes,2,rep,name=moduleSortName,proto3" json:"moduleSortName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindAllModuleSortResponse) Reset() {
	*x = FindAllModuleSortResponse{}
	mi := &file_legacy_unit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllModuleSortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllModuleSortResponse) ProtoMessage() {}

func (x *FindAllModuleSortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllModuleSortResponse.ProtoReflect.Descriptor instead.
func (*FindAllModuleSortResponse) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{11}
}

func (x *FindAllModuleSortResponse) GetModules() []*SimpleModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *FindAllModuleSortResponse) GetModuleSortName() []*BasicModuleSort {
	if x != nil {
		return x.ModuleSortName
	}
	return nil
}

type FindModuleSimpleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModuleSortUUID string                 `protobuf:"bytes,1,opt,name=moduleSortUUID,proto3" json:"moduleSortUUID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindModuleSimpleRequest) Reset() {
	*x = FindModuleSimpleRequest{}
	mi := &file_legacy_unit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindModuleSimpleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindModuleSimpleRequest) ProtoMessage() {}

func (x *FindModuleSimpleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindModuleSimpleRequest.ProtoReflect.Descriptor instead.
func (*FindModuleSimpleRequest) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{12}
}

func (x *FindModuleSimpleRequest) GetModuleSortUUID() string {
	if x != nil {
		return x.ModuleSortUUID
	}
	return ""
}

type BusinessFreeModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleUuid    string                 `protobuf:"bytes,1,opt,name=ModuleUuid,proto3" json:"ModuleUuid,omitempty"`
	ApiUuids      []string               `protobuf:"bytes,2,rep,name=apiUuids,proto3" json:"apiUuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessFreeModule) Reset() {
	*x = BusinessFreeModule{}
	mi := &file_legacy_unit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessFreeModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessFreeModule) ProtoMessage() {}

func (x *BusinessFreeModule) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessFreeModule.ProtoReflect.Descriptor instead.
func (*BusinessFreeModule) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{13}
}

func (x *BusinessFreeModule) GetModuleUuid() string {
	if x != nil {
		return x.ModuleUuid
	}
	return ""
}

func (x *BusinessFreeModule) GetApiUuids() []string {
	if x != nil {
		return x.ApiUuids
	}
	return nil
}

type ModulesApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*BusinessFreeModule  `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModulesApiResponse) Reset() {
	*x = ModulesApiResponse{}
	mi := &file_legacy_unit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModulesApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModulesApiResponse) ProtoMessage() {}

func (x *ModulesApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModulesApiResponse.ProtoReflect.Descriptor instead.
func (*ModulesApiResponse) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{14}
}

func (x *ModulesApiResponse) GetModules() []*BusinessFreeModule {
	if x != nil {
		return x.Modules
	}
	return nil
}

type FindModulesByStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ModuleCommonStatus     `protobuf:"varint,1,opt,name=status,proto3,enum=ModuleCommonStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindModulesByStatusRequest) Reset() {
	*x = FindModulesByStatusRequest{}
	mi := &file_legacy_unit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindModulesByStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindModulesByStatusRequest) ProtoMessage() {}

func (x *FindModulesByStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legacy_unit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindModulesByStatusRequest.ProtoReflect.Descriptor instead.
func (*FindModulesByStatusRequest) Descriptor() ([]byte, []int) {
	return file_legacy_unit_proto_rawDescGZIP(), []int{15}
}

func (x *FindModulesByStatusRequest) GetStatus() ModuleCommonStatus {
	if x != nil {
		return x.Status
	}
	return ModuleCommonStatus_AllCanUse
}

var File_legacy_unit_proto protoreflect.FileDescriptor

const file_legacy_unit_proto_rawDesc = "" +
	"\n" +
	"\x11legacy/unit.proto\x1a\x13legacy/common.proto\"\xcc\x01\n" +
	"\vBasicModule\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12$\n" +
	"\rwebRouterName\x18\x05 \x01(\tR\rwebRouterName\x12\x1e\n" +
	"\n" +
	"mobilePage\x18\x06 \x01(\tR\n" +
	"mobilePage\x12%\n" +
	"\x06canUse\x18\a \x01(\x0e2\r.ModuleCanUseR\x06canUse\"\xae\x01\n" +
	"\fSimpleModule\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x12\x1a\n" +
	"\bbasicFee\x18\x06 \x01(\rR\bbasicFee\x12\x18\n" +
	"\aunitFee\x18\a \x01(\rR\aunitFee\"\x8b\x01\n" +
	"\x0fBasicModuleSort\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12&\n" +
	"\amodules\x18\x05 \x03(\v2\f.BasicModuleR\amodules\"J\n" +
	"&FindBasicModuleSortByMoudleUUIDRequest\x12 \n" +
	"\vmoduleUUIDs\x18\x01 \x03(\tR\vmoduleUUIDs\"[\n" +
	"'FindBasicModuleSortByMoudleUUIDResponse\x120\n" +
	"\n" +
	"moduleSort\x18\x01 \x03(\v2\x10.BasicModuleSortR\n" +
	"moduleSort\".\n" +
	"\x18FindModuleApiUuidRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"/\n" +
	"\x19FindModuleApiUuidResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x03(\tR\x04uuid\"'\n" +
	"\x11ModuleUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x03(\tR\x04uuid\"<\n" +
	"\x12BaseModuleResponse\x12&\n" +
	"\amodules\x18\x01 \x03(\v2\f.BasicModuleR\amodules\"O\n" +
	" FindModulesByModuleStatusRequest\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.ModuleCommonStatusR\x06status\"?\n" +
	"\x14SimpleModuleResponse\x12'\n" +
	"\amodules\x18\x01 \x03(\v2\r.SimpleModuleR\amodules\"~\n" +
	"\x19FindAllModuleSortResponse\x12'\n" +
	"\amodules\x18\x01 \x03(\v2\r.SimpleModuleR\amodules\x128\n" +
	"\x0emoduleSortName\x18\x02 \x03(\v2\x10.BasicModuleSortR\x0emoduleSortName\"A\n" +
	"\x17FindModuleSimpleRequest\x12&\n" +
	"\x0emoduleSortUUID\x18\x01 \x01(\tR\x0emoduleSortUUID\"P\n" +
	"\x12BusinessFreeModule\x12\x1e\n" +
	"\n" +
	"ModuleUuid\x18\x01 \x01(\tR\n" +
	"ModuleUuid\x12\x1a\n" +
	"\bapiUuids\x18\x02 \x03(\tR\bapiUuids\"C\n" +
	"\x12ModulesApiResponse\x12-\n" +
	"\amodules\x18\x01 \x03(\v2\x13.BusinessFreeModuleR\amodules\"I\n" +
	"\x1aFindModulesByStatusRequest\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.ModuleCommonStatusR\x06status*,\n" +
	"\fModuleCanUse\x12\a\n" +
	"\x03All\x10\x00\x12\n" +
	"\n" +
	"\x06Mobile\x10\x01\x12\a\n" +
	"\x03Web\x10\x02*T\n" +
	"\x12ModuleCommonStatus\x12\r\n" +
	"\tAllCanUse\x10\x00\x12\r\n" +
	"\tKolCanUse\x10\x01\x12\x11\n" +
	"\rServiceCanUse\x10\x02\x12\r\n" +
	"\tNotCommon\x10\x032\xad\x05\n" +
	"\vUnitService\x12s\n" +
	"\x1eFindBaseModuleSortByModuleUUID\x12'.FindBasicModuleSortByMoudleUUIDRequest\x1a(.FindBasicModuleSortByMoudleUUIDResponse\x12J\n" +
	"\x11FindModuleApiUuid\x12\x19.FindModuleApiUuidRequest\x1a\x1a.FindModuleApiUuidResponse\x127\n" +
	"\x0eFindFreeModule\x12\x10.NotParamRequest\x1a\x13.ModulesApiResponse\x12<\n" +
	"\x11FindModulesByUUID\x12\x12.ModuleUUIDRequest\x1a\x13.BaseModuleResponse\x12S\n" +
	"\x19FindModulesByModuleStatus\x12!.FindModulesByModuleStatusRequest\x1a\x13.BaseModuleResponse\x12>\n" +
	"\x11FindSimpleModules\x12\x12.ModuleUUIDRequest\x1a\x15.SimpleModuleResponse\x12A\n" +
	"\x11FindAllModuleSort\x12\x10.NotParamRequest\x1a\x1a.FindAllModuleSortResponse\x12S\n" +
	" FindModuleSimpleByModuleSortUUID\x12\x18.FindModuleSimpleRequest\x1a\x15.SimpleModuleResponse\x129\n" +
	"\x0eFindModulesApi\x12\x12.ModuleUUIDRequest\x1a\x13.ModulesApiResponseB$Z\"github.com/hvritual/yunka.io/pkg/rpcmeta/legacy;legacyb\x06proto3"

var (
	file_legacy_unit_proto_rawDescOnce sync.Once
	file_legacy_unit_proto_rawDescData []byte
)

func file_legacy_unit_proto_rawDescGZIP() []byte {
	file_legacy_unit_proto_rawDescOnce.Do(func() {
		file_legacy_unit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_legacy_unit_proto_rawDesc), len(file_legacy_unit_proto_rawDesc)))
	})
	return file_legacy_unit_proto_rawDescData
}

var file_legacy_unit_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_legacy_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_legacy_unit_proto_goTypes = []any{
	(ModuleCanUse)(0),                               // 0: ModuleCanUse
	(ModuleCommonStatus)(0),                         // 1: ModuleCommonStatus
	(*BasicModule)(nil),                             // 2: BasicModule
	(*SimpleModule)(nil),                            // 3: SimpleModule
	(*BasicModuleSort)(nil),                         // 4: BasicModuleSort
	(*FindBasicModuleSortByMoudleUUIDRequest)(nil),  // 5: FindBasicModuleSortByMoudleUUIDRequest
	(*FindBasicModuleSortByMoudleUUIDResponse)(nil), // 6: FindBasicModuleSortByMoudleUUIDResponse
	(*FindModuleApiUuidRequest)(nil),                // 7: FindModuleApiUuidRequest
	(*FindModuleApiUuidResponse)(nil),               // 8: FindModuleApiUuidResponse
	(*ModuleUUIDRequest)(nil),                       // 9: ModuleUUIDRequest
	(*BaseModuleResponse)(nil),                      // 10: BaseModuleResponse
	(*FindModulesByModuleStatusRequest)(nil),        // 11: FindModulesByModuleStatusRequest
	(*SimpleModuleResponse)(nil),                    // 12: SimpleModuleResponse
	(*FindAllModuleSortResponse)(nil),               // 13: FindAllModuleSortResponse
	(*FindModuleSimpleRequest)(nil),                 // 14: FindModuleSimpleRequest
	(*BusinessFreeModule)(nil),                      // 15: BusinessFreeModule
	(*ModulesApiResponse)(nil),                      // 16: ModulesApiResponse
	(*FindModulesByStatusRequest)(nil),              // 17: FindModulesByStatusRequest
	(*NotParamRequest)(nil),                         // 18: NotParamRequest
}
var file_legacy_unit_proto_depIdxs = []int32{
	0,  // 0: BasicModule.canUse:type_name -> ModuleCanUse
	2,  // 1: BasicModuleSort.modules:type_name -> BasicModule
	4,  // 2: FindBasicModuleSortByMoudleUUIDResponse.moduleSort:type_name -> BasicModuleSort
	2,  // 3: BaseModuleResponse.modules:type_name -> BasicModule
	1,  // 4: FindModulesByModuleStatusRequest.status:type_name -> ModuleCommonStatus
	3,  // 5: SimpleModuleResponse.modules:type_name -> SimpleModule
	3,  // 6: FindAllModuleSortResponse.modules:type_name -> SimpleModule
	4,  // 7: FindAllModuleSortResponse.moduleSortName:type_name -> BasicModuleSort
	15, // 8: ModulesApiResponse.modules:type_name -> BusinessFreeModule
	1,  // 9: FindModulesByStatusRequest.status:type_name -> ModuleCommonStatus
	5,  // 10: UnitService.FindBaseModuleSortByModuleUUID:input_type -> FindBasicModuleSortByMoudleUUIDRequest
	7,  // 11: UnitService.FindModuleApiUuid:input_type -> FindModuleApiUuidRequest
	18, // 12: UnitService.FindFreeModule:input_type -> NotParamRequest
	9,  // 13: UnitService.FindModulesByUUID:input_type -> ModuleUUIDRequest
	11, // 14: UnitService.FindModulesByModuleStatus:input_type -> FindModulesByModuleStatusRequest
	9,  // 15: UnitService.FindSimpleModules:input_type -> ModuleUUIDRequest
	18, // 16: UnitService.FindAllModuleSort:input_type -> NotParamRequest
	14, // 17: UnitService.FindModuleSimpleByModuleSortUUID:input_type -> FindModuleSimpleRequest
	9,  // 18: UnitService.FindModulesApi:input_type -> ModuleUUIDRequest
	6,  // 19: UnitService.FindBaseModuleSortByModuleUUID:output_type -> FindBasicModuleSortByMoudleUUIDResponse
	8,  // 20: UnitService.FindModuleApiUuid:output_type -> FindModuleApiUuidResponse
	16, // 21: UnitService.FindFreeModule:output_type -> ModulesApiResponse
	10, // 22: UnitService.FindModulesByUUID:output_type -> BaseModuleResponse
	10, // 23: UnitService.FindModulesByModuleStatus:output_type -> BaseModuleResponse
	12, // 24: UnitService.FindSimpleModules:output_type -> SimpleModuleResponse
	13, // 25: UnitService.FindAllModuleSort:output_type -> FindAllModuleSortResponse
	12, // 26: UnitService.FindModuleSimpleByModuleSortUUID:output_type -> SimpleModuleResponse
	16, // 27: UnitService.FindModulesApi:output_type -> ModulesApiResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_legacy_unit_proto_init() }
func file_legacy_unit_proto_init() {
	if File_legacy_unit_proto != nil {
		return
	}
	file_legacy_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_legacy_unit_proto_rawDesc), len(file_legacy_unit_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_legacy_unit_proto_goTypes,
		DependencyIndexes: file_legacy_unit_proto_depIdxs,
		EnumInfos:         file_legacy_unit_proto_enumTypes,
		MessageInfos:      file_legacy_unit_proto_msgTypes,
	}.Build()
	File_legacy_unit_proto = out.File
	file_legacy_unit_proto_goTypes = nil
	file_legacy_unit_proto_depIdxs = nil
}
