package module

import (
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"yunka.io/pkg/architecturepolicy"
	"yunka.io/pkg/modulespec"
)

var requiredModuleFiles = []string{
	"config.go",
	"dependencies.go",
	"module.go",
	"zz_yunka_module_gen.go",
	filepath.Join("autoload", "register.go"),
}

func Check(root string) error {
	root = strings.TrimSpace(root)
	if root == "" {
		root = "modules"
	}
	info, err := os.Stat(root)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("module: check root %s is not a directory", root)
	}
	entries, err := os.ReadDir(root)
	if err != nil {
		return err
	}
	sort.Slice(entries, func(left, right int) bool { return entries[left].Name() < entries[right].Name() })
	var failures []error
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		moduleRoot := filepath.Join(root, entry.Name())
		specFile := filepath.Join(moduleRoot, modulespec.Filename)
		if _, statErr := os.Stat(specFile); statErr == nil {
			legacy, legacyErr := hasLegacyModuleSource(moduleRoot)
			if legacyErr != nil {
				failures = append(failures, fmt.Errorf("%s: declarative module: %w", entry.Name(), legacyErr))
				continue
			}
			if legacy {
				failures = append(failures, fmt.Errorf("%s: %s cannot coexist with legacy generated module files", entry.Name(), modulespec.Filename))
				continue
			}
			spec, loadErr := modulespec.Load(specFile)
			if loadErr != nil {
				failures = append(failures, fmt.Errorf("%s: declarative module: %w", entry.Name(), loadErr))
				continue
			}
			if validateErr := modulespec.ValidateForModule(entry.Name(), spec); validateErr != nil {
				failures = append(failures, fmt.Errorf("%s: declarative module: %w", entry.Name(), validateErr))
			}
			continue
		} else if !os.IsNotExist(statErr) {
			failures = append(failures, fmt.Errorf("%s: declarative module stat: %w", entry.Name(), statErr))
			continue
		}

		for _, relative := range requiredModuleFiles {
			path := filepath.Join(moduleRoot, relative)
			if _, err := os.Stat(path); err != nil {
				failures = append(failures, fmt.Errorf("%s: required file %s: %w", entry.Name(), relative, err))
			}
		}
		generatedPath := filepath.Join(moduleRoot, "zz_yunka_module_gen.go")
		if generated, err := os.ReadFile(generatedPath); err == nil {
			text := string(generated)
			if !strings.Contains(text, "Code generated by yunka module; DO NOT EDIT.") ||
				!strings.Contains(text, "func GeneratedDescriptor() modulecatalog.Descriptor") {
				failures = append(failures, fmt.Errorf("%s: generated descriptor marker or function is missing", entry.Name()))
			}
		}
		err := filepath.WalkDir(moduleRoot, func(path string, current os.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if current.IsDir() || !strings.HasSuffix(current.Name(), ".go") {
				return nil
			}
			if _, parseErr := parser.ParseFile(token.NewFileSet(), path, nil, parser.AllErrors); parseErr != nil {
				failures = append(failures, fmt.Errorf("%s: parse %s: %w", entry.Name(), path, parseErr))
			}
			return nil
		})
		if err != nil {
			failures = append(failures, fmt.Errorf("%s: walk: %w", entry.Name(), err))
		}
		autoloadPath := filepath.Join(moduleRoot, "autoload", "register.go")
		if diagnostics, err := architecturepolicy.CheckAutoloadFile(autoloadPath); err != nil {
			failures = append(failures, fmt.Errorf("%s: autoload: %w", entry.Name(), err))
		} else {
			for _, diagnostic := range diagnostics {
				failures = append(failures, fmt.Errorf("%s: autoload: %s", entry.Name(), diagnostic.Message))
			}
		}
	}
	return errors.Join(failures...)
}
