// Code generated by yunka domain; DO NOT EDIT.

package application

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	domain "github.com/hvritual/biz/internal/device/domain"
	ports "github.com/hvritual/biz/internal/device/ports"
	"time"
	"yunka.io/framework/requestscope"
)

type Service interface {
	CreateDevice(context.Context, CreateDeviceInput) (DeviceOutput, error)
	GetDevice(context.Context, GetDeviceInput) (DeviceOutput, error)
	ListDevices(context.Context, ListDevicesInput) (ListDevicesOutput, error)
	UpdateDevice(context.Context, UpdateDeviceInput) (DeviceOutput, error)
	DeleteDevice(context.Context, DeleteDeviceInput) error
}

type CreateDeviceInput struct {
	CreatedBy string `json:"createdBy"`
	Name      string `json:"name"`
	Serial    string `json:"serial"`
	SiteID    string `json:"siteId"`
}
type GetDeviceInput struct{ ID string }
type ListDevicesInput struct {
	Limit  int
	Offset int
}
type UpdateDeviceInput struct {
	ID        string
	Version   uint64
	CreatedBy string `json:"createdBy"`
	Name      string `json:"name"`
	Serial    string `json:"serial"`
	SiteID    string `json:"siteId"`
}
type DeleteDeviceInput struct {
	ID      string
	Version uint64
}
type DeviceOutput struct {
	Value domain.Device `json:"value"`
}
type ListDevicesOutput struct {
	Items []domain.Device `json:"items"`
}

type DefaultService struct {
	scopes requestscope.ScopeFactory[ports.Repositories]
}

func NewService(scopes requestscope.ScopeFactory[ports.Repositories]) (*DefaultService, error) {
	if scopes == nil {
		return nil, errors.New("domain application: request scope factory is required")
	}
	return &DefaultService{scopes: scopes}, nil
}

func (service *DefaultService) CreateDevice(ctx context.Context, input CreateDeviceInput) (DeviceOutput, error) {
	value := domain.Device{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC(), CreatedBy: input.CreatedBy, Name: input.Name, Serial: input.Serial, SiteID: input.SiteID}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Device, error) {
		if err := scope.Repositories().Device.Create(scope.Context(), &value); err != nil {
			return domain.Device{}, err
		}
		return value, nil
	})
	return DeviceOutput{Value: created}, err
}
func (service *DefaultService) GetDevice(ctx context.Context, input GetDeviceInput) (DeviceOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Device, error) {
		return scope.Repositories().Device.Get(scope.Context(), input.ID)
	})
	return DeviceOutput{Value: value}, err
}
func (service *DefaultService) ListDevices(ctx context.Context, input ListDevicesInput) (ListDevicesOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.Device, error) {
		return scope.Repositories().Device.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListDevicesOutput{Items: items}, err
}
func (service *DefaultService) UpdateDevice(ctx context.Context, input UpdateDeviceInput) (DeviceOutput, error) {
	value := domain.Device{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC(), CreatedBy: input.CreatedBy, Name: input.Name, Serial: input.Serial, SiteID: input.SiteID}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Device, error) {
		repository := scope.Repositories().Device
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.Device{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return DeviceOutput{Value: updated}, err
}
func (service *DefaultService) DeleteDevice(ctx context.Context, input DeleteDeviceInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().Device.Delete(scope.Context(), input.ID, input.Version)
	})
}

func newID() string {
	var value [16]byte
	if _, err := rand.Read(value[:]); err != nil {
		panic(err)
	}
	return hex.EncodeToString(value[:])
}
