// Code generated by yunka module; DO NOT EDIT.

package outboxruntime

import (
	"fmt"
	"github.com/hvritual/yunka.io/framework/core/modulecatalog"
)

func GeneratedDescriptor() modulecatalog.Descriptor {
	return modulecatalog.Descriptor{
		Name:    ModuleName,
		Version: "v0.1.0",
		Requirements: modulecatalog.Requirements{
			ConfigKey: "modules.outboxruntime",
			Logger:    true,
			Databases: []modulecatalog.DatabaseRequirement{{Name: "primary"}},
			EventBus:  true,
		},
		Build: generatedBuild,
	}
}

func generatedBuild(context modulecatalog.BuildContext) (modulecatalog.Instance, error) {
	dependencies := Dependencies{}
	config := DefaultConfig()
	if err := context.Config().Decode(ModuleName, "modules.outboxruntime", &config); err != nil {
		return nil, fmt.Errorf("%s config: %w", ModuleName, err)
	}
	if err := config.Validate(); err != nil {
		return nil, fmt.Errorf("%s config validation: %w", ModuleName, err)
	}
	dependencies.Config = config
	dependencies.Logger = context.Logger()
	primaryDatabase, err := context.Databases().GORM("primary")
	if err != nil {
		return nil, fmt.Errorf("%s database primary: %w", ModuleName, err)
	}
	dependencies.PrimaryDatabase = primaryDatabase
	dependencies.EventBus = context.EventBus()
	return NewModule(dependencies)
}
