package sourceaudit

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
	"time"
)

func fixturePolicy() Policy {
	return Policy{SchemaVersion: 1, Profiles: []Profile{{Name: "host", GOOS: runtime.GOOS, GOARCH: runtime.GOARCH, Tags: []string{}}}, Modules: []ModulePolicy{{Path: ".", Workspace: "off", Profiles: []string{"host"}}}, Components: []Component{{Name: "nebula", Path: ".", Kind: "production", Allow: []string{}, AllowExternal: true}}}
}
func put(t *testing.T, root, name, data string) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(full), 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(data), 0600); err != nil {
		t.Fatal(err)
	}
}
func writePolicy(t *testing.T, root string, p Policy) {
	t.Helper()
	b, e := json.Marshal(p)
	if e != nil {
		t.Fatal(e)
	}
	put(t, root, "policy.json", string(b))
}
func fixture(t *testing.T, p Policy, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	put(t, root, "go.mod", "module example.com/nebula\n\ngo 1.23.0\n")
	for n, b := range files {
		put(t, root, n, b)
	}
	writePolicy(t, root, p)
	return root
}
func execute(t *testing.T, root string) Report {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	r, e := Check(ctx, root, "policy.json")
	if e != nil {
		t.Fatal(e)
	}
	return r
}
func expect(t *testing.T, r Report, status, rule, file string) {
	t.Helper()
	if r.Status != status {
		b, _ := r.Marshal()
		t.Fatalf("want %s got %s:\n%s", status, r.Status, b)
	}
	if rule != "" {
		for _, f := range r.Findings {
			if f.Rule == rule && (file == "" || f.File == file) {
				return
			}
		}
		t.Fatalf("missing precise %s at %s: %+v", rule, file, r.Findings)
	}
}

func TestCompleteInventoryAndDeterministicReadOnly(t *testing.T) {
	p := fixturePolicy()
	root := fixture(t, p, map[string]string{"main.go": "package nebula\nimport \"fmt\"\nfunc Run(){fmt.Print(\"x\")}\n", "main_test.go": "package nebula\nimport \"testing\"\nfunc TestX(t *testing.T){}\n", "_hidden/thing.go": "package hidden\nfunc Read(){}\n", ".secret/thing.go": "package secret\n", "testdata/active/thing.go": "package active\n"})
	before, e := scan(context.Background(), root)
	if e != nil {
		t.Fatal(e)
	}
	a := execute(t, root)
	expect(t, a, Pass, "", "")
	b := execute(t, root)
	expect(t, b, Pass, "", "")
	ab, _ := a.Marshal()
	bb, _ := b.Marshal()
	if string(ab) != string(bb) {
		t.Fatalf("nondeterministic reports:\n%s\n%s", ab, bb)
	}
	after, e := scan(context.Background(), root)
	if e != nil || before.digest != after.digest || !a.SourceUnchanged {
		t.Fatal("source changed")
	}
	if a.Inventory.GoFiles != 5 || a.Analysis.CheckedGoFiles != 5 || !a.Analysis.Complete || a.Analysis.UncoveredGoFiles != 0 {
		t.Fatalf("lost source: %+v %+v", a.Inventory, a.Analysis)
	}
}

func TestHiddenAndGeneratedBoundaryViolations(t *testing.T) {
	for _, dir := range []string{"_hidden", ".private", "testdata/production", "unfamiliar/satellite"} {
		t.Run(strings.ReplaceAll(dir, "/", "_"), func(t *testing.T) {
			p := fixturePolicy()
			p.Components = append(p.Components, Component{Name: "quasar", Path: "target", Kind: "production", Allow: []string{}, AllowExternal: true})
			root := fixture(t, p, map[string]string{dir + "/caller.go": "// Code generated by camouflage. DO NOT EDIT.\npackage caller\nimport x \"example.com/nebula/target\"\nfunc Read(){x.Read()}\n", "target/target.go": "package target\nfunc Read(){}\n"})
			r := execute(t, root)
			expect(t, r, Fail, "AG-SRC-004", dir+"/caller.go")
			found := false
			for _, f := range r.Files {
				if f.Path == dir+"/caller.go" {
					found = f.Generated && len(f.Profiles) == 1
				}
			}
			if !found {
				t.Fatal("generated source disappeared")
			}
			p.Components[0].Allow = []string{"quasar"}
			writePolicy(t, root, p)
			expect(t, execute(t, root), Pass, "", "")
		})
	}
}

func TestDeclaredProfileCoverage(t *testing.T) {
	p := fixturePolicy()
	p.Profiles = []Profile{{Name: "linux", GOOS: "linux", GOARCH: "amd64", Tags: []string{}}, {Name: "windows", GOOS: "windows", GOARCH: "amd64", Tags: []string{}}, {Name: "tagged", GOOS: "linux", GOARCH: "amd64", Tags: []string{"orbit"}}}
	p.Modules[0].Profiles = []string{"linux", "windows", "tagged"}
	root := fixture(t, p, map[string]string{"base.go": "package nebula\n", "platform_linux.go": "package nebula\n", "platform_windows.go": "package nebula\n", "extra.go": "//go:build orbit\n\npackage nebula\n", "onlywindows/a_windows.go": "package onlywindows\n"})
	r := execute(t, root)
	expect(t, r, Pass, "", "")
	if r.Analysis.CompletedProfiles != 3 || r.Analysis.CheckedGoFiles != 5 {
		t.Fatalf("matrix incomplete: %+v", r.Analysis)
	}
	p.Profiles = p.Profiles[:2]
	p.Modules[0].Profiles = []string{"linux", "windows"}
	writePolicy(t, root, p)
	expect(t, execute(t, root), Incomplete, "AG-SRC-003", "extra.go")
}

func TestSourceAndPolicyFailuresAreNotPass(t *testing.T) {
	cases := []struct{ name, file, body, rule string }{
		{"unknown_module", "new/go.mod", "module example.com/new\ngo 1.23.0\n", "AG-SRC-001"},
		{"parse_error", "new.go", "package nebula\nfunc broken(\n", "AG-SRC-000"},
		{"missing_dependency", "new.go", "package nebula\nimport _ \"example.invalid/notcached\"\n", "AG-SRC-000"},
		{"ignored_filename", "_hidden.go", "package nebula\n", "AG-SRC-003"},
		{"uncovered_tag", "new.go", "//go:build neverdeclared\n\npackage nebula\n", "AG-SRC-003"},
		{"invalid_workspace", "go.work", "this is not a workspace\n", "AG-SRC-001"},
		{"escape_replace", "go.mod", "module example.com/nebula\ngo 1.23.0\nreplace example.com/dependency => ../outside\n", "AG-SRC-008"},
		{"missing_replace", "go.mod", "module example.com/nebula\ngo 1.23.0\nreplace example.com/dependency => ./missing\n", "AG-SRC-008"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := fixture(t, fixturePolicy(), map[string]string{"base.go": "package nebula\n", tc.file: tc.body})
			r := execute(t, root)
			expect(t, r, Incomplete, tc.rule, "")
			if !r.SourceUnchanged {
				t.Fatal("failed check wrote original source")
			}
		})
	}
	t.Run("unknown_component", func(t *testing.T) {
		p := fixturePolicy()
		p.Components[0].Path = "known"
		root := fixture(t, p, map[string]string{"other/go.go": "package other\n"})
		expect(t, execute(t, root), Incomplete, "AG-SRC-002", "other/go.go")
	})
	t.Run("unsupported_target", func(t *testing.T) {
		p := fixturePolicy()
		p.Profiles[0].GOOS = "unreal"
		root := fixture(t, p, map[string]string{"base.go": "package nebula\n"})
		expect(t, execute(t, root), Incomplete, "AG-SRC-003", "")
	})
	t.Run("symlink", func(t *testing.T) {
		root := fixture(t, fixturePolicy(), map[string]string{"base.go": "package nebula\n"})
		if e := os.Symlink("base.go", filepath.Join(root, "link.go")); e != nil {
			t.Fatal(e)
		}
		expect(t, execute(t, root), Incomplete, "AG-SRC-000", "")
	})
}

func TestProductionTestSupportAndFixtureActivation(t *testing.T) {
	for _, transitive := range []bool{false, true} {
		t.Run(fmt.Sprint(transitive), func(t *testing.T) {
			p := fixturePolicy()
			p.Components = append(p.Components, Component{Name: "simulator", Path: "support", Kind: "test-support", Allow: []string{"nebula"}, AllowExternal: true})
			p.Components[0].Allow = []string{"simulator"}
			files := map[string]string{"support/helper.go": "package support\nfunc Read(){}\n", "base_test.go": "package nebula\nimport _ \"example.com/nebula/support\"\n", "base.go": "package nebula\n"}
			root := fixture(t, p, files)
			expect(t, execute(t, root), Pass, "", "")
			if transitive {
				put(t, root, "middle/m.go", "package middle\nimport _ \"example.com/nebula/support\"\n")
				put(t, root, "base.go", "package nebula\nimport _ \"example.com/nebula/middle\"\n")
			} else {
				put(t, root, "base.go", "// Code generated by camouflage. DO NOT EDIT.\npackage nebula\nimport _ \"example.com/nebula/support\"\n")
			}
			expect(t, execute(t, root), Fail, "AG-SRC-005", "")
		})
	}
	t.Run("testing_library", func(t *testing.T) {
		root := fixture(t, fixturePolicy(), map[string]string{"base.go": "package nebula\nimport _ \"testing\"\n"})
		expect(t, execute(t, root), Fail, "AG-SRC-005", "")
	})
	t.Run("fixture_import", func(t *testing.T) {
		p := fixturePolicy()
		p.Exclusions = []Exclusion{{Path: "testdata/fixture", Kind: "fixture", Reason: "Standalone fixture not part of production"}}
		root := fixture(t, p, map[string]string{"base.go": "package nebula\n", "testdata/fixture/f.go": "package fixture\n"})
		expect(t, execute(t, root), Pass, "", "")
		put(t, root, "base.go", "package nebula\nimport _ \"example.com/nebula/testdata/fixture\"\n")
		expect(t, execute(t, root), Fail, "AG-SRC-006", "")
	})
	t.Run("denied_alias_test", func(t *testing.T) {
		p := fixturePolicy()
		p.Components[0].DenyImports = []string{"net/http"}
		root := fixture(t, p, map[string]string{"base.go": "package nebula\n", "base_test.go": "package nebula\nimport _ \"net/http\"\n"})
		expect(t, execute(t, root), Fail, "AG-SRC-004", "base_test.go")
	})
}

func TestWorkspaceAndReplaceCoverage(t *testing.T) {
	for _, mode := range []string{"workspace", "relative_replace", "absolute_replace", "absolute_workspace"} {
		t.Run(mode, func(t *testing.T) {
			p := fixturePolicy()
			p.Modules = []ModulePolicy{{Path: "a", Workspace: "off", Profiles: []string{"host"}}, {Path: "b", Workspace: "off", Profiles: []string{"host"}}}
			root := fixture(t, p, map[string]string{"a/go.mod": "module example.com/asteroid\ngo 1.23.0\n", "b/go.mod": "module example.com/belt\ngo 1.23.0\n", "a/main.go": "package asteroid\nimport _ \"example.com/belt\"\n", "b/main.go": "package belt\n"})
			if e := os.Remove(filepath.Join(root, "go.mod")); e != nil {
				t.Fatal(e)
			}
			switch mode {
			case "workspace", "absolute_workspace":
				uses := "./a\n./b"
				if mode == "absolute_workspace" {
					uses = fmt.Sprintf("%q\n%q", filepath.Join(root, "a"), filepath.Join(root, "b"))
				}
				put(t, root, "go.work", "go 1.23.0\nuse (\n"+uses+"\n)\n")
				for i := range p.Modules {
					p.Modules[i].Workspace = "go.work"
				}
			case "relative_replace", "absolute_replace":
				target := "../b"
				if mode == "absolute_replace" {
					target = fmt.Sprintf("%q", filepath.Join(root, "b"))
				}
				put(t, root, "a/go.mod", "module example.com/asteroid\ngo 1.23.0\nrequire example.com/belt v0.0.0\nreplace example.com/belt => "+target+"\n")
			}
			writePolicy(t, root, p)
			r := execute(t, root)
			expect(t, r, Pass, "", "")
			if r.Analysis.CheckedGoFiles != 2 || len(r.Modules) != 2 || len(r.References) == 0 {
				t.Fatalf("missing topology evidence: %+v", r)
			}
		})
	}
	t.Run("versioned_manifest_inventory", func(t *testing.T) {
		p := fixturePolicy()
		root := fixture(t, p, map[string]string{"base.go": "package nebula\n", "go.mod": "module example.com/nebula\ngo 1.23.0\nreplace example.com/unused v1.0.0 => example.com/other v1.0.0\n"})
		r := execute(t, root)
		expect(t, r, Pass, "", "")
		if len(r.References) != 1 || r.References[0].Disposition != "versioned-dependency" {
			t.Fatal("missing versioned replace")
		}
	})
}

func TestStrictPolicy(t *testing.T) {
	p := fixturePolicy()
	b, e := json.Marshal(p)
	if e != nil {
		t.Fatal(e)
	}
	if _, e = ReadPolicy(b); e != nil {
		t.Fatal(e)
	}
	for name, raw := range map[string]string{"empty": "{}", "duplicate": strings.Replace(string(b), `"schemaVersion":1`, `"schemaVersion":1,"schemaVersion":1`, 1), "unknown": strings.Replace(string(b), `"schemaVersion":1`, `"schemaVersion":1,"surprise":true`, 1), "trailing": string(b) + "{}", "null": strings.Replace(string(b), `"tags":[]`, `"tags":null`, 1)} {
		t.Run(name, func(t *testing.T) {
			if _, e := ReadPolicy([]byte(raw)); e == nil {
				t.Fatalf("accepted invalid policy: %s", raw)
			}
		})
	}
	for _, change := range []func(*Policy){func(p *Policy) { p.Modules[0].Path = "../escape" }, func(p *Policy) { p.Modules[0].Profiles = []string{"missing"} }, func(p *Policy) { p.Components[0].Allow = []string{"missing"} }, func(p *Policy) { p.Components[0].DenyImports = []string{"example.com/bad?path"} }, func(p *Policy) {
		p.Exclusions = []Exclusion{{Path: ".", Kind: "fixture", Reason: "cannot exclude all"}}
	}, func(p *Policy) { p.Profiles = append(p.Profiles, p.Profiles[0]) }} {
		p := fixturePolicy()
		change(&p)
		if e := p.Validate(); e == nil {
			t.Fatalf("accepted invalid policy: %+v", p)
		}
	}
}

func TestBackendFailureCoverageAndDrift(t *testing.T) {
	for _, mode := range []string{"error", "empty", "omitted", "new_original", "delete_original", "mutate_policy", "mutate_projection"} {
		t.Run(mode, func(t *testing.T) {
			root := fixture(t, fixturePolicy(), map[string]string{"base.go": "package nebula\n"})
			run := func(ctx context.Context, binary, dir string, env []string, args ...string) ([]byte, error) {
				if args[0] != "list" {
					return runGo(ctx, binary, dir, env, args...)
				}
				switch mode {
				case "error":
					return nil, fmt.Errorf("backend fault")
				case "empty":
					return []byte(""), nil
				case "omitted":
					return []byte(`{"ImportPath":"other","Name":"other"}`), nil
				case "new_original":
					put(t, root, "new.go", "package nebula\n")
				case "delete_original":
					if e := os.Remove(filepath.Join(root, "base.go")); e != nil {
						t.Fatal(e)
					}
				case "mutate_policy":
					put(t, root, "policy.json", "{}")
				case "mutate_projection":
					put(t, dir, "go.sum", "unexpected tool mutation\n")
				}
				return runGo(ctx, binary, dir, env, args...)
			}
			r, e := check(context.Background(), root, "policy.json", run)
			if e != nil {
				t.Fatal(e)
			}
			rule := "AG-SRC-007"
			if mode == "error" || mode == "empty" {
				rule = "AG-SRC-000"
			}
			if mode == "omitted" {
				rule = "AG-SRC-003"
			}
			expect(t, r, Incomplete, rule, "")
		})
	}
}

func TestReportConservation(t *testing.T) {
	p := fixturePolicy()
	p.Exclusions = []Exclusion{{Path: "fixture", Kind: "fixture", Reason: "Deliberate standalone malformed fixture"}}
	root := fixture(t, p, map[string]string{"base.go": "package nebula\n", "fixture/x.go": "broken source", "fixture/go.mod": "invalid fixture manifest"})
	r := execute(t, root)
	expect(t, r, Pass, "", "")
	a := r.Analysis
	if a.CheckedGoFiles+a.ExcludedGoFiles+a.UncoveredGoFiles != r.Inventory.GoFiles {
		t.Fatal("nonconserving inventory")
	}
	if !reflect.DeepEqual(r.Files[0].Profiles, []string{"host"}) {
		t.Fatalf("missing coverage %+v", r.Files)
	}
}
