// Code generated by protoc-gen-xr v0.1, DO NOT EDIT.
// source: server

/*
Package server is a generated rpc stub package.

It is generated from these files:
	api_common.proto
	common.proto
	gateway.proto
*/
package server

const (
	GatewayServiceName = `GatewayService`
)
