CREATE TABLE IF NOT EXISTS `yunka_outbox` (
  `id` varchar(64) NOT NULL,
  `topic` varchar(255) NOT NULL,
  `event_type` varchar(255) NOT NULL,
  `event_json` longblob NOT NULL,
  `status` varchar(32) NOT NULL,
  `attempts` int NOT NULL DEFAULT 0,
  `next_attempt_at` datetime NOT NULL,
  `lease_owner` varchar(128) NOT NULL DEFAULT '',
  `lease_until` datetime NULL,
  `last_error` text NULL,
  `published_at` datetime NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_yunka_outbox_ready` (`status`, `next_attempt_at`),
  KEY `idx_yunka_outbox_topic` (`topic`),
  KEY `idx_yunka_outbox_lease_until` (`lease_until`),
  KEY `idx_yunka_outbox_published_at` (`published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
