// Code generated by yunka domain; DO NOT EDIT.

package ports

import (
	"context"
	"errors"
	domain "github.com/hvritual/biz/internal/iam/domain"
)

var (
	ErrNotFound = errors.New("domain repository: not found")
	ErrConflict = errors.New("domain repository: version conflict")
)

type APITokenRepository interface {
	Create(context.Context, *domain.APIToken) error
	Get(context.Context, string) (domain.APIToken, error)
	List(context.Context, int, int) ([]domain.APIToken, error)
	Update(context.Context, *domain.APIToken, uint64) error
	Delete(context.Context, string, uint64) error
}
type MemberRoleRepository interface {
	Create(context.Context, *domain.MemberRole) error
	Get(context.Context, string) (domain.MemberRole, error)
	List(context.Context, int, int) ([]domain.MemberRole, error)
	Update(context.Context, *domain.MemberRole, uint64) error
	Delete(context.Context, string, uint64) error
}
type MemberSiteRepository interface {
	Create(context.Context, *domain.MemberSite) error
	Get(context.Context, string) (domain.MemberSite, error)
	List(context.Context, int, int) ([]domain.MemberSite, error)
	Update(context.Context, *domain.MemberSite, uint64) error
	Delete(context.Context, string, uint64) error
}
type MembershipRepository interface {
	Create(context.Context, *domain.Membership) error
	Get(context.Context, string) (domain.Membership, error)
	List(context.Context, int, int) ([]domain.Membership, error)
	Update(context.Context, *domain.Membership, uint64) error
	Delete(context.Context, string, uint64) error
}
type RoleRepository interface {
	Create(context.Context, *domain.Role) error
	Get(context.Context, string) (domain.Role, error)
	List(context.Context, int, int) ([]domain.Role, error)
	Update(context.Context, *domain.Role, uint64) error
	Delete(context.Context, string, uint64) error
}
type RolePermissionRepository interface {
	Create(context.Context, *domain.RolePermission) error
	Get(context.Context, string) (domain.RolePermission, error)
	List(context.Context, int, int) ([]domain.RolePermission, error)
	Update(context.Context, *domain.RolePermission, uint64) error
	Delete(context.Context, string, uint64) error
}
type TenantRepository interface {
	Create(context.Context, *domain.Tenant) error
	Get(context.Context, string) (domain.Tenant, error)
	List(context.Context, int, int) ([]domain.Tenant, error)
	Update(context.Context, *domain.Tenant, uint64) error
	Delete(context.Context, string, uint64) error
}
type UserRepository interface {
	Create(context.Context, *domain.User) error
	Get(context.Context, string) (domain.User, error)
	List(context.Context, int, int) ([]domain.User, error)
	Update(context.Context, *domain.User, uint64) error
	Delete(context.Context, string, uint64) error
}
type Repositories struct {
	APIToken       APITokenRepository
	MemberRole     MemberRoleRepository
	MemberSite     MemberSiteRepository
	Membership     MembershipRepository
	Role           RoleRepository
	RolePermission RolePermissionRepository
	Tenant         TenantRepository
	User           UserRepository
}
