// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: yunka/dsl/v1/options.proto

package contractdslv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DTOKind int32

const (
	DTOKind_DTO_UNSPECIFIED  DTOKind = 0
	DTOKind_DTO_INPUT        DTOKind = 1
	DTOKind_DTO_OUTPUT       DTOKind = 2
	DTOKind_DTO_SHARED       DTOKind = 3
	DTOKind_DTO_EVENT        DTOKind = 4
	DTOKind_DTO_VALUE_OBJECT DTOKind = 5
)

// Enum value maps for DTOKind.
var (
	DTOKind_name = map[int32]string{
		0: "DTO_UNSPECIFIED",
		1: "DTO_INPUT",
		2: "DTO_OUTPUT",
		3: "DTO_SHARED",
		4: "DTO_EVENT",
		5: "DTO_VALUE_OBJECT",
	}
	DTOKind_value = map[string]int32{
		"DTO_UNSPECIFIED":  0,
		"DTO_INPUT":        1,
		"DTO_OUTPUT":       2,
		"DTO_SHARED":       3,
		"DTO_EVENT":        4,
		"DTO_VALUE_OBJECT": 5,
	}
)

func (x DTOKind) Enum() *DTOKind {
	p := new(DTOKind)
	*p = x
	return p
}

func (x DTOKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DTOKind) Descriptor() protoreflect.EnumDescriptor {
	return file_yunka_dsl_v1_options_proto_enumTypes[0].Descriptor()
}

func (DTOKind) Type() protoreflect.EnumType {
	return &file_yunka_dsl_v1_options_proto_enumTypes[0]
}

func (x DTOKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DTOKind.Descriptor instead.
func (DTOKind) EnumDescriptor() ([]byte, []int) {
	return file_yunka_dsl_v1_options_proto_rawDescGZIP(), []int{0}
}

type PermissionMode int32

const (
	PermissionMode_PERMISSION_ALL PermissionMode = 0
	PermissionMode_PERMISSION_ANY PermissionMode = 1
)

// Enum value maps for PermissionMode.
var (
	PermissionMode_name = map[int32]string{
		0: "PERMISSION_ALL",
		1: "PERMISSION_ANY",
	}
	PermissionMode_value = map[string]int32{
		"PERMISSION_ALL": 0,
		"PERMISSION_ANY": 1,
	}
)

func (x PermissionMode) Enum() *PermissionMode {
	p := new(PermissionMode)
	*p = x
	return p
}

func (x PermissionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_yunka_dsl_v1_options_proto_enumTypes[1].Descriptor()
}

func (PermissionMode) Type() protoreflect.EnumType {
	return &file_yunka_dsl_v1_options_proto_enumTypes[1]
}

func (x PermissionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionMode.Descriptor instead.
func (PermissionMode) EnumDescriptor() ([]byte, []int) {
	return file_yunka_dsl_v1_options_proto_rawDescGZIP(), []int{1}
}

type Authentication int32

const (
	Authentication_AUTHENTICATION_UNSPECIFIED Authentication = 0
	Authentication_AUTHENTICATION_JWT         Authentication = 1
	Authentication_AUTHENTICATION_API_KEY     Authentication = 2
	Authentication_AUTHENTICATION_SERVICE     Authentication = 3
)

// Enum value maps for Authentication.
var (
	Authentication_name = map[int32]string{
		0: "AUTHENTICATION_UNSPECIFIED",
		1: "AUTHENTICATION_JWT",
		2: "AUTHENTICATION_API_KEY",
		3: "AUTHENTICATION_SERVICE",
	}
	Authentication_value = map[string]int32{
		"AUTHENTICATION_UNSPECIFIED": 0,
		"AUTHENTICATION_JWT":         1,
		"AUTHENTICATION_API_KEY":     2,
		"AUTHENTICATION_SERVICE":     3,
	}
)

func (x Authentication) Enum() *Authentication {
	p := new(Authentication)
	*p = x
	return p
}

func (x Authentication) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Authentication) Descriptor() protoreflect.EnumDescriptor {
	return file_yunka_dsl_v1_options_proto_enumTypes[2].Descriptor()
}

func (Authentication) Type() protoreflect.EnumType {
	return &file_yunka_dsl_v1_options_proto_enumTypes[2]
}

func (x Authentication) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Authentication.Descriptor instead.
func (Authentication) EnumDescriptor() ([]byte, []int) {
	return file_yunka_dsl_v1_options_proto_rawDescGZIP(), []int{2}
}

type DomainDeclaration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainDeclaration) Reset() {
	*x = DomainDeclaration{}
	mi := &file_yunka_dsl_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainDeclaration) ProtoMessage() {}

func (x *DomainDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_yunka_dsl_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainDeclaration.ProtoReflect.Descriptor instead.
func (*DomainDeclaration) Descriptor() ([]byte, []int) {
	return file_yunka_dsl_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *DomainDeclaration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomainDeclaration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DTODeclaration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          DTOKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=yunka.dsl.v1.DTOKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DTODeclaration) Reset() {
	*x = DTODeclaration{}
	mi := &file_yunka_dsl_v1_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DTODeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DTODeclaration) ProtoMessage() {}

func (x *DTODeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_yunka_dsl_v1_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DTODeclaration.ProtoReflect.Descriptor instead.
func (*DTODeclaration) Descriptor() ([]byte, []int) {
	return file_yunka_dsl_v1_options_proto_rawDescGZIP(), []int{1}
}

func (x *DTODeclaration) GetKind() DTOKind {
	if x != nil {
		return x.Kind
	}
	return DTOKind_DTO_UNSPECIFIED
}

type ApplicationDeclaration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationDeclaration) Reset() {
	*x = ApplicationDeclaration{}
	mi := &file_yunka_dsl_v1_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationDeclaration) ProtoMessage() {}

func (x *ApplicationDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_yunka_dsl_v1_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationDeclaration.ProtoReflect.Descriptor instead.
func (*ApplicationDeclaration) Descriptor() ([]byte, []int) {
	return file_yunka_dsl_v1_options_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationDeclaration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OperationDeclaration struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UseCase        string                 `protobuf:"bytes,2,opt,name=use_case,json=useCase,proto3" json:"use_case,omitempty"`
	Permissions    []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	PermissionMode PermissionMode         `protobuf:"varint,4,opt,name=permission_mode,json=permissionMode,proto3,enum=yunka.dsl.v1.PermissionMode" json:"permission_mode,omitempty"`
	TenantRequired bool                   `protobuf:"varint,5,opt,name=tenant_required,json=tenantRequired,proto3" json:"tenant_required,omitempty"`
	Authentication []Authentication       `protobuf:"varint,6,rep,packed,name=authentication,proto3,enum=yunka.dsl.v1.Authentication" json:"authentication,omitempty"`
	Public         bool                   `protobuf:"varint,7,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperationDeclaration) Reset() {
	*x = OperationDeclaration{}
	mi := &file_yunka_dsl_v1_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationDeclaration) ProtoMessage() {}

func (x *OperationDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_yunka_dsl_v1_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationDeclaration.ProtoReflect.Descriptor instead.
func (*OperationDeclaration) Descriptor() ([]byte, []int) {
	return file_yunka_dsl_v1_options_proto_rawDescGZIP(), []int{3}
}

func (x *OperationDeclaration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OperationDeclaration) GetUseCase() string {
	if x != nil {
		return x.UseCase
	}
	return ""
}

func (x *OperationDeclaration) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *OperationDeclaration) GetPermissionMode() PermissionMode {
	if x != nil {
		return x.PermissionMode
	}
	return PermissionMode_PERMISSION_ALL
}

func (x *OperationDeclaration) GetTenantRequired() bool {
	if x != nil {
		return x.TenantRequired
	}
	return false
}

func (x *OperationDeclaration) GetAuthentication() []Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *OperationDeclaration) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

var file_yunka_dsl_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*DomainDeclaration)(nil),
		Field:         51001,
		Name:          "yunka.dsl.v1.domain",
		Tag:           "bytes,51001,opt,name=domain",
		Filename:      "yunka/dsl/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*DTODeclaration)(nil),
		Field:         51002,
		Name:          "yunka.dsl.v1.dto",
		Tag:           "bytes,51002,opt,name=dto",
		Filename:      "yunka/dsl/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ApplicationDeclaration)(nil),
		Field:         51003,
		Name:          "yunka.dsl.v1.application",
		Tag:           "bytes,51003,opt,name=application",
		Filename:      "yunka/dsl/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*OperationDeclaration)(nil),
		Field:         51004,
		Name:          "yunka.dsl.v1.operation",
		Tag:           "bytes,51004,opt,name=operation",
		Filename:      "yunka/dsl/v1/options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional yunka.dsl.v1.DomainDeclaration domain = 51001;
	E_Domain = &file_yunka_dsl_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional yunka.dsl.v1.DTODeclaration dto = 51002;
	E_Dto = &file_yunka_dsl_v1_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional yunka.dsl.v1.ApplicationDeclaration application = 51003;
	E_Application = &file_yunka_dsl_v1_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional yunka.dsl.v1.OperationDeclaration operation = 51004;
	E_Operation = &file_yunka_dsl_v1_options_proto_extTypes[3]
)

var File_yunka_dsl_v1_options_proto protoreflect.FileDescriptor

const file_yunka_dsl_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x1ayunka/dsl/v1/options.proto\x12\fyunka.dsl.v1\x1a google/protobuf/descriptor.proto\"A\n" +
	"\x11DomainDeclaration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\";\n" +
	"\x0eDTODeclaration\x12)\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x15.yunka.dsl.v1.DTOKindR\x04kind\",\n" +
	"\x16ApplicationDeclaration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xb1\x02\n" +
	"\x14OperationDeclaration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\buse_case\x18\x02 \x01(\tR\auseCase\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\x12E\n" +
	"\x0fpermission_mode\x18\x04 \x01(\x0e2\x1c.yunka.dsl.v1.PermissionModeR\x0epermissionMode\x12'\n" +
	"\x0ftenant_required\x18\x05 \x01(\bR\x0etenantRequired\x12D\n" +
	"\x0eauthentication\x18\x06 \x03(\x0e2\x1c.yunka.dsl.v1.AuthenticationR\x0eauthentication\x12\x16\n" +
	"\x06public\x18\a \x01(\bR\x06public*r\n" +
	"\aDTOKind\x12\x13\n" +
	"\x0fDTO_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tDTO_INPUT\x10\x01\x12\x0e\n" +
	"\n" +
	"DTO_OUTPUT\x10\x02\x12\x0e\n" +
	"\n" +
	"DTO_SHARED\x10\x03\x12\r\n" +
	"\tDTO_EVENT\x10\x04\x12\x14\n" +
	"\x10DTO_VALUE_OBJECT\x10\x05*8\n" +
	"\x0ePermissionMode\x12\x12\n" +
	"\x0ePERMISSION_ALL\x10\x00\x12\x12\n" +
	"\x0ePERMISSION_ANY\x10\x01*\x80\x01\n" +
	"\x0eAuthentication\x12\x1e\n" +
	"\x1aAUTHENTICATION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12AUTHENTICATION_JWT\x10\x01\x12\x1a\n" +
	"\x16AUTHENTICATION_API_KEY\x10\x02\x12\x1a\n" +
	"\x16AUTHENTICATION_SERVICE\x10\x03:W\n" +
	"\x06domain\x12\x1c.google.protobuf.FileOptions\x18\xb9\x8e\x03 \x01(\v2\x1f.yunka.dsl.v1.DomainDeclarationR\x06domain:Q\n" +
	"\x03dto\x12\x1f.google.protobuf.MessageOptions\x18\xba\x8e\x03 \x01(\v2\x1c.yunka.dsl.v1.DTODeclarationR\x03dto:i\n" +
	"\vapplication\x12\x1f.google.protobuf.ServiceOptions\x18\xbb\x8e\x03 \x01(\v2$.yunka.dsl.v1.ApplicationDeclarationR\vapplication:b\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xbc\x8e\x03 \x01(\v2\".yunka.dsl.v1.OperationDeclarationR\toperationB+Z)yunka.io/pkg/contractdsl/v1;contractdslv1b\x06proto3"

var (
	file_yunka_dsl_v1_options_proto_rawDescOnce sync.Once
	file_yunka_dsl_v1_options_proto_rawDescData []byte
)

func file_yunka_dsl_v1_options_proto_rawDescGZIP() []byte {
	file_yunka_dsl_v1_options_proto_rawDescOnce.Do(func() {
		file_yunka_dsl_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yunka_dsl_v1_options_proto_rawDesc), len(file_yunka_dsl_v1_options_proto_rawDesc)))
	})
	return file_yunka_dsl_v1_options_proto_rawDescData
}

var file_yunka_dsl_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_yunka_dsl_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_yunka_dsl_v1_options_proto_goTypes = []any{
	(DTOKind)(0),                        // 0: yunka.dsl.v1.DTOKind
	(PermissionMode)(0),                 // 1: yunka.dsl.v1.PermissionMode
	(Authentication)(0),                 // 2: yunka.dsl.v1.Authentication
	(*DomainDeclaration)(nil),           // 3: yunka.dsl.v1.DomainDeclaration
	(*DTODeclaration)(nil),              // 4: yunka.dsl.v1.DTODeclaration
	(*ApplicationDeclaration)(nil),      // 5: yunka.dsl.v1.ApplicationDeclaration
	(*OperationDeclaration)(nil),        // 6: yunka.dsl.v1.OperationDeclaration
	(*descriptorpb.FileOptions)(nil),    // 7: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 8: google.protobuf.MessageOptions
	(*descriptorpb.ServiceOptions)(nil), // 9: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 10: google.protobuf.MethodOptions
}
var file_yunka_dsl_v1_options_proto_depIdxs = []int32{
	0,  // 0: yunka.dsl.v1.DTODeclaration.kind:type_name -> yunka.dsl.v1.DTOKind
	1,  // 1: yunka.dsl.v1.OperationDeclaration.permission_mode:type_name -> yunka.dsl.v1.PermissionMode
	2,  // 2: yunka.dsl.v1.OperationDeclaration.authentication:type_name -> yunka.dsl.v1.Authentication
	7,  // 3: yunka.dsl.v1.domain:extendee -> google.protobuf.FileOptions
	8,  // 4: yunka.dsl.v1.dto:extendee -> google.protobuf.MessageOptions
	9,  // 5: yunka.dsl.v1.application:extendee -> google.protobuf.ServiceOptions
	10, // 6: yunka.dsl.v1.operation:extendee -> google.protobuf.MethodOptions
	3,  // 7: yunka.dsl.v1.domain:type_name -> yunka.dsl.v1.DomainDeclaration
	4,  // 8: yunka.dsl.v1.dto:type_name -> yunka.dsl.v1.DTODeclaration
	5,  // 9: yunka.dsl.v1.application:type_name -> yunka.dsl.v1.ApplicationDeclaration
	6,  // 10: yunka.dsl.v1.operation:type_name -> yunka.dsl.v1.OperationDeclaration
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	7,  // [7:11] is the sub-list for extension type_name
	3,  // [3:7] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_yunka_dsl_v1_options_proto_init() }
func file_yunka_dsl_v1_options_proto_init() {
	if File_yunka_dsl_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yunka_dsl_v1_options_proto_rawDesc), len(file_yunka_dsl_v1_options_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_yunka_dsl_v1_options_proto_goTypes,
		DependencyIndexes: file_yunka_dsl_v1_options_proto_depIdxs,
		EnumInfos:         file_yunka_dsl_v1_options_proto_enumTypes,
		MessageInfos:      file_yunka_dsl_v1_options_proto_msgTypes,
		ExtensionInfos:    file_yunka_dsl_v1_options_proto_extTypes,
	}.Build()
	File_yunka_dsl_v1_options_proto = out.File
	file_yunka_dsl_v1_options_proto_goTypes = nil
	file_yunka_dsl_v1_options_proto_depIdxs = nil
}
