// Code generated by protoc-gen-xr v0.1, DO NOT EDIT.
// source: base

package memory

import (
	"errors"
	"fmt"

	"yunka.io/pkg/trie"
	"yunka.io/gateway/rpc/meta"
	"yunka.io/gateway/rpc/server"
	"yunka.io/pkg/invoke"
)

var (
	MethodExistErr    = errors.New("method has exist")
	MethodNotExistErr = errors.New("method not exist")
)

type memoryInvoke struct {
	node    *trie.RuneTrie
	methods map[string]invoke.SrvHandler
}

func NewMemoryInvoke(tree *trie.RuneTrie) *memoryInvoke {
	return &memoryInvoke{
		node: tree,
	}
}

func (m *memoryInvoke) RegisterServer(name string, srv interface{}) error {
	switch name {
	case server.GatewayServiceName:
		return m.registerGatewayServiceServer(srv.(meta.GatewayServiceServer))
	}
	return errors.New(fmt.Sprintf("%s handler has not register", name))
}

func (m *memoryInvoke) register(method string, handler invoke.SrvHandler) error {
	if m.node.Get(method) != nil {
		return MethodExistErr
	}

	m.node.Put(method, handler)
	return nil
}
