// Code generated by protoc-gen-xr v0.1, DO NOT EDIT.
// source: gateway.proto

package memory

import (
	"context"
	"errors"

	"github.com/golang/protobuf/proto"
	"yunka.io/gateway/rpc/meta"
	"yunka.io/gateway/rpc/method"
	"yunka.io/pkg/invoke"
)

// GatewayServiceHandler is the Hook  for GatewayService service register.
type _GatewayServiceHook func(srv meta.GatewayServiceServer) invoke.SrvHandler

// GatewayServiceServer is the server API for GatewayService service.
func (s *memoryInvoke) registerGatewayServiceServer(server meta.GatewayServiceServer) error {
	if server == nil {
		return errors.New(`interface is nil`)
	}

	for key, value := range _GatewayServiceDescs {
		err := s.register(key, value(server))
		if err != nil {
			return err
		}
	}

	return nil
}
func _BatchAddRuntimeApi(srv meta.GatewayServiceServer) invoke.SrvHandler {
	return func(ctx context.Context, args proto.Message) (reply proto.Message, err error) {
		return srv.BatchAddRuntimeApi(ctx, args.(*meta.BatchRuntimeApiRequest))
	}
}
func _DeleteRuntimeApi(srv meta.GatewayServiceServer) invoke.SrvHandler {
	return func(ctx context.Context, args proto.Message) (reply proto.Message, err error) {
		return srv.DeleteRuntimeApi(ctx, args.(*meta.DeleteRuntimeApiRequest))
	}
}
func _OperateRoleAPI(srv meta.GatewayServiceServer) invoke.SrvHandler {
	return func(ctx context.Context, args proto.Message) (reply proto.Message, err error) {
		return srv.OperateRoleAPI(ctx, args.(*meta.RoleModuleBtn))
	}
}

// register invoke server to hooks
var (
	_GatewayServiceDescs = map[string]_GatewayServiceHook{
		method.BatchAddRuntimeApi: _BatchAddRuntimeApi,
		method.DeleteRuntimeApi:   _DeleteRuntimeApi,
		method.OperateRoleAPI:     _OperateRoleAPI,
	}
)
