// Code generated by protoc-gen-xr v0.1, DO NOT EDIT.
// source: memory

package memory

import (
	"context"
	"github.com/golang/protobuf/proto"
	"yunka.io/pkg/invoke"
)

func (m *memoryInvoke) Invoke(ctx context.Context, method string, args, reply proto.Message,
	param ...interface{}) error {

	iHandler := m.node.Get(method)
	if iHandler == nil {
		return MethodNotExistErr
	}
	handler := iHandler.(invoke.SrvHandler)
	result, err := handler(ctx, args)
	if err != nil {
		return err
	}
	buf := proto.Buffer{}
	err = buf.EncodeMessage(result)
	if err != nil {
		return err
	}
	return buf.DecodeMessage(reply)
}

func (m *memoryInvoke) InvokeNode(ctx context.Context, nodeId, method string, args, reply proto.Message,
	param ...interface{}) error {
	return m.Invoke(ctx, method, args, reply, param...)
}
