// Code generated by protoc-gen-xr v0.1, DO NOT EDIT.
// source: gateway.proto

package handle

const (
	BatchAddRuntimeApi = `/GatewayService/BatchAddRuntimeApi`
	DeleteRuntimeApi   = `/GatewayService/DeleteRuntimeApi`
	OperateRoleAPI     = `/GatewayService/OperateRoleAPI`
)
