package domain

import (
	"fmt"
	"strings"
)

func poBaseTemplate(spec Spec, packageImport string) string {
	object := exportedIdentifier(spec.Object)
	base := object + "POBase"
	var b strings.Builder
	b.WriteString("// Code generated by yunka domain; DO NOT EDIT.\n\n")
	b.WriteString("package persistence\n\n")
	fmt.Fprintf(&b, "import (\n\t\"time\"\n\t\"gorm.io/gorm\"\n\tdomain %q\n)\n\n", packageImport+"/domain")
	fmt.Fprintf(&b, "const %sTableName = %q\n\n", lowerFirst(object), spec.TableName)
	fmt.Fprintf(&b, "// %s contains framework-owned persistence columns. Embed it in %sPO and add application-owned columns there.\n", base, object)
	fmt.Fprintf(&b, "type %s struct {\n", base)
	b.WriteString("\tID string `gorm:\"column:id;type:varchar(64);primaryKey\"`\n")
	if spec.TenantScoped {
		b.WriteString("\tTenantID string `gorm:\"column:tenant_id;type:varchar(64);not null;index\"`\n")
	}
	for _, field := range spec.Fields {
		typeName, _ := goType(field.Type)
		fmt.Fprintf(&b, "\t%s %s `gorm:\"column:%s;%s\"`\n", exportedIdentifier(field.Name), typeName, field.Name, columnType(field))
	}
	b.WriteString("\tVersion uint64 `gorm:\"column:version;type:bigint unsigned;not null;default:1\"`\n")
	b.WriteString("\tCreatedAt time.Time `gorm:\"column:created_at;type:datetime(3);not null\"`\n")
	b.WriteString("\tUpdatedAt time.Time `gorm:\"column:updated_at;type:datetime(3);not null\"`\n")
	b.WriteString("\tDeletedAt gorm.DeletedAt `gorm:\"column:deleted_at;type:datetime(3);index\"`\n")
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "func (%sPO) TableName() string { return %sTableName }\n\n", object, lowerFirst(object))
	fmt.Fprintf(&b, "func (po %sPO) Domain() domain.%s {\n", object, object)
	fmt.Fprintf(&b, "\treturn domain.%s{\n\t\tID: po.ID,\n", object)
	if spec.TenantScoped {
		b.WriteString("\t\tTenantID: po.TenantID,\n")
	}
	for _, field := range spec.Fields {
		f := exportedIdentifier(field.Name)
		fmt.Fprintf(&b, "\t\t%s: po.%s,\n", f, f)
	}
	b.WriteString("\t\tVersion: po.Version, CreatedAt: po.CreatedAt, UpdatedAt: po.UpdatedAt,\n\t}\n}\n\n")
	fmt.Fprintf(&b, "func %sPOFromDomain(value domain.%s) %sPO {\n", object, object, object)
	fmt.Fprintf(&b, "\treturn %sPO{%s: %s{\n\t\tID: value.ID,\n", object, base, base)
	if spec.TenantScoped {
		b.WriteString("\t\tTenantID: value.TenantID,\n")
	}
	for _, field := range spec.Fields {
		f := exportedIdentifier(field.Name)
		fmt.Fprintf(&b, "\t\t%s: value.%s,\n", f, f)
	}
	b.WriteString("\t\tVersion: value.Version, CreatedAt: value.CreatedAt, UpdatedAt: value.UpdatedAt,\n\t}}\n}\n")
	return b.String()
}

func developerPOTemplate(spec Spec) string {
	object := exportedIdentifier(spec.Object)
	base := object + "POBase"
	var b strings.Builder
	b.WriteString("// Scaffolded by yunka domain. Application-owned; safe to add persistence fields.\n\n")
	b.WriteString("package persistence\n\n")
	fmt.Fprintf(&b, "// %sPO is the editable persistence model. Add persistence-only fields here.\n", object)
	b.WriteString("// Table naming stays framework-owned and wire.Build automatically runs GORM AutoMigrate against this final type.\n")
	fmt.Fprintf(&b, "type %sPO struct {\n\t%s `gorm:\"embedded\"`\n", object, base)
	b.WriteString("\t// Add application-owned PO fields below. Example:\n")
	b.WriteString("\t// ExternalCode string `gorm:\"column:external_code;type:varchar(64);index\"`\n")
	b.WriteString("}\n")
	return b.String()
}

func persistenceRepositoryV2Template(spec Spec, packageImport string) string {
	object := exportedIdentifier(spec.Object)
	var b strings.Builder
	b.WriteString("// Code generated by yunka domain; DO NOT EDIT.\n\n")
	b.WriteString("package persistence\n\n")
	fmt.Fprintf(&b, "import (\n\t\"context\"\n\t\"errors\"\n\t\"time\"\n\t\"gorm.io/gorm\"\n\tdomain %q\n\tports %q\n\t\"yunka.io/framework/requestscope\"\n", packageImport+"/domain", packageImport+"/ports")
	if spec.TenantScoped {
		b.WriteString("\tidentity \"yunka.io/framework/core/identity\"\n")
	}
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "type %sRepository struct { database *gorm.DB }\n\n", object)
	fmt.Fprintf(&b, "func AutoMigrate(ctx context.Context, database *gorm.DB) error {\n\tif database == nil { return errors.New(\"domain persistence: database is required\") }\n\tif ctx == nil { ctx = context.Background() }\n\treturn database.WithContext(ctx).AutoMigrate(&%sPO{})\n}\n\n", object)
	fmt.Fprintf(&b, "func New%sRepository(database *gorm.DB) (*%sRepository, error) {\n", object, object)
	b.WriteString("\tif database == nil { return nil, errors.New(\"domain persistence: database is required\") }\n")
	fmt.Fprintf(&b, "\treturn &%sRepository{database: database}, nil\n}\n\n", object)
	b.WriteString("func NewScopeFactory(database *gorm.DB) (requestscope.ScopeFactory[ports.Repositories], error) {\n")
	b.WriteString("\tunitOfWork, err := requestscope.NewGORMFactory(database, nil)\n\tif err != nil { return nil, err }\n")
	b.WriteString("\treturn requestscope.NewFactory(requestscope.FactoryOptions[ports.Repositories]{UnitOfWork: unitOfWork, Repositories: requestscope.GORMRepositories(func(ctx context.Context, transaction *gorm.DB) (ports.Repositories, error) {\n")
	fmt.Fprintf(&b, "\t\trepository, err := New%sRepository(transaction)\n\t\tif err != nil { return ports.Repositories{}, err }\n\t\treturn ports.Repositories{%s: repository}, nil\n\t})})\n}\n\n", object, object)
	fmt.Fprintf(&b, "func (repository *%sRepository) scoped(ctx context.Context) (*gorm.DB, error) {\n", object)
	b.WriteString("\tquery := repository.database.WithContext(ctx)\n")
	if spec.TenantScoped {
		b.WriteString("\ttenantID, err := trustedTenant(ctx)\n\tif err != nil { return nil, err }\n\tquery = query.Where(\"tenant_id = ?\", tenantID)\n")
	}
	b.WriteString("\treturn query, nil\n}\n\n")
	if spec.TenantScoped {
		b.WriteString("func trustedTenant(ctx context.Context) (string, error) {\n\tprincipal, ok := identity.FromContext(ctx)\n\tif !ok || !principal.Authenticated || principal.TenantID == \"\" { return \"\", errors.New(\"domain persistence: trusted tenant principal is required\") }\n\treturn principal.TenantID, nil\n}\n\n")
	}
	fmt.Fprintf(&b, "func (repository *%sRepository) Create(ctx context.Context, value *domain.%s) error {\n", object, object)
	b.WriteString("\tif value == nil { return errors.New(\"domain persistence: value is required\") }\n")
	if spec.TenantScoped {
		b.WriteString("\ttenantID, err := trustedTenant(ctx)\n\tif err != nil { return err }\n\tvalue.TenantID = tenantID\n")
	}
	b.WriteString("\tif value.Version == 0 { value.Version = 1 }; now := time.Now().UTC(); if value.CreatedAt.IsZero() { value.CreatedAt = now }; value.UpdatedAt = now\n")
	fmt.Fprintf(&b, "\tpo := %sPOFromDomain(*value)\n\tif err := repository.database.WithContext(ctx).Create(&po).Error; err != nil { return err }\n\t*value = po.Domain()\n\treturn nil\n}\n\n", object)
	fmt.Fprintf(&b, "func (repository *%sRepository) Get(ctx context.Context, id string) (domain.%s, error) {\n", object, object)
	fmt.Fprintf(&b, "\tquery, err := repository.scoped(ctx); if err != nil { return domain.%s{}, err }; var po %sPO\n", object, object)
	fmt.Fprintf(&b, "\tif err := query.Where(\"id = ?\", id).First(&po).Error; err != nil { if errors.Is(err, gorm.ErrRecordNotFound) { return domain.%s{}, ports.ErrNotFound }; return domain.%s{}, err }; return po.Domain(), nil\n}\n\n", object, object)
	fmt.Fprintf(&b, "func (repository *%sRepository) List(ctx context.Context, limit, offset int) ([]domain.%s, error) {\n", object, object)
	fmt.Fprintf(&b, "\tquery, err := repository.scoped(ctx); if err != nil { return nil, err }; var rows []%sPO; if limit > 0 { query = query.Limit(limit) }; if offset > 0 { query = query.Offset(offset) }; if err := query.Order(\"created_at DESC\").Find(&rows).Error; err != nil { return nil, err }; result := make([]domain.%s, 0, len(rows)); for _, row := range rows { result = append(result, row.Domain()) }; return result, nil\n}\n\n", object, object)
	fmt.Fprintf(&b, "func (repository *%sRepository) Update(ctx context.Context, value *domain.%s, expectedVersion uint64) error {\n", object, object)
	b.WriteString("\tif value == nil || value.ID == \"\" { return errors.New(\"domain persistence: update value/id is required\") }; query, err := repository.scoped(ctx); if err != nil { return err }\n")
	b.WriteString("\tupdates := map[string]any{\"version\": gorm.Expr(\"version + 1\"), \"updated_at\": time.Now().UTC(),\n")
	for _, field := range spec.Fields {
		fmt.Fprintf(&b, "\t\t%q: value.%s,\n", field.Name, exportedIdentifier(field.Name))
	}
	b.WriteString("\t}\n")
	fmt.Fprintf(&b, "\tresult := query.Model(&%sPO{}).Where(\"id = ? AND version = ?\", value.ID, expectedVersion).Updates(updates); if result.Error != nil { return result.Error }; if result.RowsAffected != 1 { return ports.ErrConflict }; return nil\n}\n\n", object)
	fmt.Fprintf(&b, "func (repository *%sRepository) Delete(ctx context.Context, id string, expectedVersion uint64) error {\n", object)
	b.WriteString("\tquery, err := repository.scoped(ctx); if err != nil { return err }; ")
	fmt.Fprintf(&b, "result := query.Where(\"id = ? AND version = ?\", id, expectedVersion).Delete(&%sPO{}); if result.Error != nil { return result.Error }; if result.RowsAffected != 1 { return ports.ErrConflict }; return nil\n}\n", object)
	return b.String()
}

func wireV2Template(spec Spec, packageImport string) string {
	var b strings.Builder
	b.WriteString("// Code generated by yunka domain; DO NOT EDIT.\n\n")
	b.WriteString("package wire\n\n")
	fmt.Fprintf(&b, "import (\n\t\"context\"\n\t\"fmt\"\n\t\"gorm.io/gorm\"\n\tapplication %q\n\tpersistence %q\n", packageImport+"/application", packageImport+"/infrastructure/persistence")
	if spec.REST.Enabled {
		fmt.Fprintf(&b, "\trest %q\n", packageImport+"/transport/rest")
	}
	if spec.RPC.Enabled {
		fmt.Fprintf(&b, "\trpc %q\n", packageImport+"/transport/rpc")
	}
	b.WriteString(")\n\n")
	b.WriteString("type Bundle struct {\n\tService application.Service\n")
	if spec.REST.Enabled {
		b.WriteString("\tREST *rest.Handler\n")
	}
	if spec.RPC.Enabled {
		b.WriteString("\tRPC *rpc.Server\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("// Build is the one-line domain composition seam. It automatically reconciles the editable final PO with the database before constructing request scopes.\n")
	b.WriteString("func Build(database *gorm.DB) (Bundle, error) {\n")
	b.WriteString("\tif err := persistence.AutoMigrate(context.Background(), database); err != nil { return Bundle{}, fmt.Errorf(\"domain wire: auto migrate: %w\", err) }\n")
	b.WriteString("\tscopes, err := persistence.NewScopeFactory(database)\n\tif err != nil { return Bundle{}, err }\n\tservice, err := application.NewService(scopes)\n\tif err != nil { return Bundle{}, err }\n\tbundle := Bundle{Service: service}\n")
	if spec.REST.Enabled {
		b.WriteString("\tbundle.REST = rest.New(service)\n")
	}
	if spec.RPC.Enabled {
		b.WriteString("\tbundle.RPC = rpc.New(service)\n")
	}
	b.WriteString("\treturn bundle, nil\n}\n")
	return b.String()
}
