package domain

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

const generatedDomainMarker = "// Code generated by yunka domain; DO NOT EDIT."

func scanPOObjects(domainRoot string, prior []ObjectSpec, tablePrefix, domainName string) ([]ObjectSpec, error) {
	persistenceRoot := filepath.Join(domainRoot, "infrastructure", "persistence")
	entries, err := os.ReadDir(persistenceRoot)
	if err != nil {
		return nil, fmt.Errorf("domain: scan PO directory %s: %w", persistenceRoot, err)
	}
	priorByName := make(map[string]ObjectSpec, len(prior))
	for _, object := range prior {
		priorByName[object.Name] = object
	}
	objects := make([]ObjectSpec, 0)
	seen := map[string]string{}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" || strings.HasSuffix(entry.Name(), "_test.go") || strings.HasPrefix(entry.Name(), "zz_yunka_") {
			continue
		}
		path := filepath.Join(persistenceRoot, entry.Name())
		contents, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		if strings.HasPrefix(string(contents), generatedDomainMarker) {
			continue
		}
		object, found, err := scanPOFile(path, entry.Name(), priorByName)
		if err != nil {
			return nil, err
		}
		if !found {
			continue
		}
		if previous, duplicate := seen[object.Name]; duplicate {
			return nil, fmt.Errorf("domain: PO object %q appears in both %s and %s", object.Name, previous, entry.Name())
		}
		seen[object.Name] = entry.Name()
		object.TableName = tableName(tablePrefix, domainName, object.Name)
		objects = append(objects, object)
	}
	if len(objects) == 0 {
		return nil, fmt.Errorf("domain: no *PO structs found under %s", persistenceRoot)
	}
	sort.Slice(objects, func(i, j int) bool { return objects[i].Name < objects[j].Name })
	return objects, nil
}

func scanPOFile(path, filename string, priorByName map[string]ObjectSpec) (ObjectSpec, bool, error) {
	fileSet := token.NewFileSet()
	parsed, err := parser.ParseFile(fileSet, path, nil, parser.ParseComments)
	if err != nil {
		return ObjectSpec{}, false, fmt.Errorf("domain: parse PO file %s: %w", path, err)
	}
	var foundName string
	var foundStruct *ast.StructType
	for _, declaration := range parsed.Decls {
		general, ok := declaration.(*ast.GenDecl)
		if !ok || general.Tok != token.TYPE {
			continue
		}
		for _, rawSpec := range general.Specs {
			typeSpec, ok := rawSpec.(*ast.TypeSpec)
			if !ok || !strings.HasSuffix(typeSpec.Name.Name, "PO") {
				continue
			}
			structure, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				return ObjectSpec{}, false, fmt.Errorf("domain: %s must declare %s as a struct", filename, typeSpec.Name.Name)
			}
			if foundStruct != nil {
				return ObjectSpec{}, false, fmt.Errorf("domain: %s contains more than one *PO struct; one PO object per file is required", filename)
			}
			foundName = strings.TrimSuffix(typeSpec.Name.Name, "PO")
			foundStruct = structure
		}
	}
	if foundStruct == nil {
		return ObjectSpec{}, false, nil
	}
	objectName := snakeCase(foundName)
	if !namePattern.MatchString(objectName) {
		return ObjectSpec{}, false, fmt.Errorf("domain: PO type %sPO resolves to invalid object name %q", foundName, objectName)
	}
	expectedFile := snakeCase(foundName) + ".go"
	if filename != expectedFile && filename != "po.go" {
		return ObjectSpec{}, false, fmt.Errorf("domain: PO %sPO must be stored in %s, got %s", foundName, expectedFile, filename)
	}
	prior := priorByName[objectName]
	fields, embedsBase, err := scanPOFields(foundStruct, foundName, prior)
	if err != nil {
		return ObjectSpec{}, false, fmt.Errorf("domain: %s: %w", filename, err)
	}
	return ObjectSpec{
		Name:         objectName,
		GoName:       foundName,
		File:         expectedFile,
		Fields:       fields,
		POEmbedsBase: embedsBase,
	}, true, nil
}

func scanPOFields(structure *ast.StructType, objectType string, prior ObjectSpec) ([]Field, bool, error) {
	direct := make([]Field, 0)
	embedsBase := false
	seen := map[string]struct{}{}
	for _, rawField := range structure.Fields.List {
		if len(rawField.Names) == 0 {
			if embeddedTypeName(rawField.Type) == objectType+"POBase" {
				embedsBase = true
			}
			continue
		}
		for _, name := range rawField.Names {
			if !name.IsExported() {
				continue
			}
			fieldName := snakeCase(name.Name)
			if _, reserved := reservedFields[fieldName]; reserved {
				return nil, false, fmt.Errorf("field %s is framework-owned; remove it from the developer PO", name.Name)
			}
			tags, err := parseStructTag(rawField.Tag)
			if err != nil {
				return nil, false, fmt.Errorf("field %s tag: %w", name.Name, err)
			}
			gormTag := tags.Get("gorm")
			if gormTag == "-" || hasTagOption(gormTag, "-") {
				continue
			}
			if tags.Get("yunka") == "-" {
				continue
			}
			kind, ok := astBusinessType(rawField.Type)
			if !ok {
				return nil, false, fmt.Errorf("field %s has unsupported domain type; use a supported scalar or tag it `yunka:\"-\"` for persistence-only use", name.Name)
			}
			if _, duplicate := seen[fieldName]; duplicate {
				return nil, false, fmt.Errorf("duplicate scanned field %q", fieldName)
			}
			seen[fieldName] = struct{}{}
			column := gormColumn(gormTag)
			if column == "" {
				column = fieldName
			}
			direct = append(direct, Field{Name: fieldName, GoName: name.Name, Type: kind, Column: column, POOwned: true})
		}
	}
	if embedsBase {
		// V1/V2 scaffolds embedded a generated POBase. During deterministic
		// migration retain those already-declared persistence fields until the
		// developer rewrites the PO as a standalone V3 persistence object.
		merged := make(map[string]Field, len(prior.Fields)+len(direct))
		for _, field := range prior.Fields {
			merged[field.Name] = field
		}
		for _, field := range direct {
			merged[field.Name] = field
		}
		direct = direct[:0]
		for _, field := range merged {
			direct = append(direct, field)
		}
	}
	sort.Slice(direct, func(i, j int) bool { return direct[i].Name < direct[j].Name })
	return direct, embedsBase, nil
}

func parseStructTag(literal *ast.BasicLit) (reflect.StructTag, error) {
	if literal == nil {
		return "", nil
	}
	value, err := strconv.Unquote(literal.Value)
	if err != nil {
		return "", err
	}
	return reflect.StructTag(value), nil
}

func hasTagOption(tag, option string) bool {
	for _, item := range strings.Split(tag, ";") {
		if strings.TrimSpace(item) == option {
			return true
		}
	}
	return false
}

func gormColumn(tag string) string {
	for _, item := range strings.Split(tag, ";") {
		item = strings.TrimSpace(item)
		if strings.HasPrefix(item, "column:") {
			return strings.TrimSpace(strings.TrimPrefix(item, "column:"))
		}
	}
	return ""
}

func embeddedTypeName(expression ast.Expr) string {
	switch typed := expression.(type) {
	case *ast.Ident:
		return typed.Name
	case *ast.StarExpr:
		return embeddedTypeName(typed.X)
	case *ast.SelectorExpr:
		return typed.Sel.Name
	default:
		return ""
	}
}

func astBusinessType(expression ast.Expr) (string, bool) {
	switch typed := expression.(type) {
	case *ast.Ident:
		switch typed.Name {
		case "string", "int64", "uint64", "bool", "float64":
			return typed.Name, true
		default:
			return "", false
		}
	case *ast.SelectorExpr:
		if identifier, ok := typed.X.(*ast.Ident); ok && identifier.Name == "time" && typed.Sel.Name == "Time" {
			return "time", true
		}
	}
	return "", false
}

func migrateLegacyPOFilename(domainRoot string, spec Spec) error {
	upgraded := upgradeSpec(spec)
	if len(upgraded.Objects) != 1 {
		return nil
	}
	persistenceRoot := filepath.Join(domainRoot, "infrastructure", "persistence")
	legacy := filepath.Join(persistenceRoot, "po.go")
	if _, err := os.Stat(legacy); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return err
	}
	expected := filepath.Join(persistenceRoot, upgraded.Objects[0].File)
	if _, err := os.Stat(expected); err == nil {
		return fmt.Errorf("domain: both legacy %s and canonical %s exist", legacy, expected)
	} else if !os.IsNotExist(err) {
		return err
	}
	return os.Rename(legacy, expected)
}

func poContractEqual(left, right []ObjectSpec) bool {
	if len(left) != len(right) {
		return false
	}
	for i := range left {
		if left[i].Name != right[i].Name || left[i].File != right[i].File || left[i].TableName != right[i].TableName || left[i].POEmbedsBase != right[i].POEmbedsBase || len(left[i].Fields) != len(right[i].Fields) {
			return false
		}
		for j := range left[i].Fields {
			l, r := left[i].Fields[j], right[i].Fields[j]
			if l.Name != r.Name || l.Type != r.Type || l.Column != r.Column || l.POOwned != r.POOwned {
				return false
			}
		}
	}
	return true
}
