package domain

import (
	"fmt"
	"strings"
)

func restTemplate(spec Spec, packageImport string) string {
	object := exportedIdentifier(spec.Object)
	plural := exportedIdentifier(pluralize(spec.Object))
	var b strings.Builder
	b.WriteString("// Code generated by yunka domain; DO NOT EDIT.\n\n")
	b.WriteString("package rest\n\n")
	fmt.Fprintf(&b, "import (\n\t\"encoding/json\"\n\t\"net/http\"\n\t\"strconv\"\n\tapplication %q\n)\n\n", packageImport+"/application")
	b.WriteString("type Handler struct { service application.Service }\n\n")
	b.WriteString("func New(service application.Service) *Handler { return &Handler{service: service} }\n\n")
	b.WriteString("func (handler *Handler) Register(mux *http.ServeMux) {\n")
	fmt.Fprintf(&b, "\tmux.HandleFunc(\"POST %s\", handler.create)\n", spec.REST.BasePath)
	fmt.Fprintf(&b, "\tmux.HandleFunc(\"GET %s\", handler.list)\n", spec.REST.BasePath)
	fmt.Fprintf(&b, "\tmux.HandleFunc(\"GET %s/{id}\", handler.get)\n", spec.REST.BasePath)
	fmt.Fprintf(&b, "\tmux.HandleFunc(\"PUT %s/{id}\", handler.update)\n", spec.REST.BasePath)
	fmt.Fprintf(&b, "\tmux.HandleFunc(\"DELETE %s/{id}\", handler.delete)\n", spec.REST.BasePath)
	b.WriteString("}\n\n")
	b.WriteString("type createRequest struct {\n")
	writeBusinessFields(&b, spec.Fields)
	b.WriteString("}\n\n")
	b.WriteString("type updateRequest struct {\n\tVersion uint64 `json:\"version\"`\n")
	writeBusinessFields(&b, spec.Fields)
	b.WriteString("}\n\n")
	b.WriteString("func (handler *Handler) create(writer http.ResponseWriter, request *http.Request) {\n")
	b.WriteString("\tvar wire createRequest\n\tif err := json.NewDecoder(request.Body).Decode(&wire); err != nil { http.Error(writer, err.Error(), http.StatusBadRequest); return }\n")
	fmt.Fprintf(&b, "\toutput, err := handler.service.Create%s(request.Context(), application.Create%sInput{\n", object, object)
	writeFieldAssignments(&b, spec.Fields, "wire")
	b.WriteString("\t})\n\twriteJSON(writer, output, err)\n}\n\n")
	b.WriteString("func (handler *Handler) get(writer http.ResponseWriter, request *http.Request) {\n")
	fmt.Fprintf(&b, "\toutput, err := handler.service.Get%s(request.Context(), application.Get%sInput{ID: request.PathValue(\"id\")})\n", object, object)
	b.WriteString("\twriteJSON(writer, output, err)\n}\n\n")
	b.WriteString("func (handler *Handler) list(writer http.ResponseWriter, request *http.Request) {\n")
	b.WriteString("\tlimit, _ := strconv.Atoi(request.URL.Query().Get(\"limit\")); offset, _ := strconv.Atoi(request.URL.Query().Get(\"offset\"))\n")
	fmt.Fprintf(&b, "\toutput, err := handler.service.List%s(request.Context(), application.List%sInput{Limit: limit, Offset: offset})\n", plural, plural)
	b.WriteString("\twriteJSON(writer, output, err)\n}\n\n")
	b.WriteString("func (handler *Handler) update(writer http.ResponseWriter, request *http.Request) {\n")
	b.WriteString("\tvar wire updateRequest\n\tif err := json.NewDecoder(request.Body).Decode(&wire); err != nil { http.Error(writer, err.Error(), http.StatusBadRequest); return }\n")
	fmt.Fprintf(&b, "\toutput, err := handler.service.Update%s(request.Context(), application.Update%sInput{ID: request.PathValue(\"id\"), Version: wire.Version,\n", object, object)
	writeFieldAssignments(&b, spec.Fields, "wire")
	b.WriteString("\t})\n\twriteJSON(writer, output, err)\n}\n\n")
	b.WriteString("func (handler *Handler) delete(writer http.ResponseWriter, request *http.Request) {\n")
	b.WriteString("\tversion, _ := strconv.ParseUint(request.URL.Query().Get(\"version\"), 10, 64)\n")
	fmt.Fprintf(&b, "\terr := handler.service.Delete%s(request.Context(), application.Delete%sInput{ID: request.PathValue(\"id\"), Version: version})\n", object, object)
	b.WriteString("\tif err != nil { http.Error(writer, err.Error(), http.StatusBadRequest); return }; writer.WriteHeader(http.StatusNoContent)\n}\n\n")
	b.WriteString("func writeJSON(writer http.ResponseWriter, value any, err error) {\n")
	b.WriteString("\tif err != nil { http.Error(writer, err.Error(), http.StatusBadRequest); return }\n")
	b.WriteString("\twriter.Header().Set(\"Content-Type\", \"application/json\"); _ = json.NewEncoder(writer).Encode(value)\n}\n")
	return b.String()
}

func writeFieldAssignments(b *strings.Builder, fields []Field, source string) {
	for _, field := range fields {
		f := exportedIdentifier(field.Name)
		fmt.Fprintf(b, "\t\t%s: %s.%s,\n", f, source, f)
	}
}

func rpcTemplate(spec Spec, packageImport string) string {
	object := exportedIdentifier(spec.Object)
	plural := exportedIdentifier(pluralize(spec.Object))
	var b strings.Builder
	b.WriteString("// Code generated by yunka domain; DO NOT EDIT.\n\n")
	b.WriteString("package rpc\n\n")
	fmt.Fprintf(&b, "import (\n\t\"context\"\n\tapplication %q\n)\n\n", packageImport+"/application")
	b.WriteString("// Server is the generated RPC application adapter. Standard protobuf/gRPC wire code delegates here; business logic remains in application.Service.\n")
	b.WriteString("type Server struct { service application.Service }\n\n")
	b.WriteString("func New(service application.Service) *Server { return &Server{service: service} }\n\n")
	fmt.Fprintf(&b, "type Create%sRequest struct {\n", object)
	writeBusinessFields(&b, spec.Fields)
	b.WriteString("}\n")
	fmt.Fprintf(&b, "type Get%sRequest struct { ID string `json:\"id\"` }\n", object)
	fmt.Fprintf(&b, "type List%sRequest struct { Limit int `json:\"limit\"`; Offset int `json:\"offset\"` }\n", plural)
	fmt.Fprintf(&b, "type Update%sRequest struct { ID string `json:\"id\"`; Version uint64 `json:\"version\"`\n", object)
	writeBusinessFields(&b, spec.Fields)
	b.WriteString("}\n")
	fmt.Fprintf(&b, "type Delete%sRequest struct { ID string `json:\"id\"`; Version uint64 `json:\"version\"` }\n\n", object)
	fmt.Fprintf(&b, "func (server *Server) Create%s(ctx context.Context, request Create%sRequest) (application.%sOutput, error) {\n", object, object, object)
	fmt.Fprintf(&b, "\treturn server.service.Create%s(ctx, application.Create%sInput{\n", object, object)
	writeFieldAssignments(&b, spec.Fields, "request")
	b.WriteString("\t})\n}\n\n")
	fmt.Fprintf(&b, "func (server *Server) Get%s(ctx context.Context, request Get%sRequest) (application.%sOutput, error) { return server.service.Get%s(ctx, application.Get%sInput{ID: request.ID}) }\n\n", object, object, object, object, object)
	fmt.Fprintf(&b, "func (server *Server) List%s(ctx context.Context, request List%sRequest) (application.List%sOutput, error) { return server.service.List%s(ctx, application.List%sInput{Limit: request.Limit, Offset: request.Offset}) }\n\n", plural, plural, plural, plural, plural)
	fmt.Fprintf(&b, "func (server *Server) Update%s(ctx context.Context, request Update%sRequest) (application.%sOutput, error) {\n", object, object, object)
	fmt.Fprintf(&b, "\treturn server.service.Update%s(ctx, application.Update%sInput{ID: request.ID, Version: request.Version,\n", object, object)
	writeFieldAssignments(&b, spec.Fields, "request")
	b.WriteString("\t})\n}\n\n")
	fmt.Fprintf(&b, "func (server *Server) Delete%s(ctx context.Context, request Delete%sRequest) error { return server.service.Delete%s(ctx, application.Delete%sInput{ID: request.ID, Version: request.Version}) }\n", object, object, object, object)
	return b.String()
}

func protoTemplate(spec Spec, packageImport string) string {
	object := exportedIdentifier(spec.Object)
	plural := exportedIdentifier(pluralize(spec.Object))
	protoPackage := strings.ReplaceAll(spec.Domain, "_", ".") + ".v1"
	var b strings.Builder
	b.WriteString("// Code generated by yunka domain; DO NOT EDIT.\n")
	b.WriteString("syntax = \"proto3\";\n\n")
	fmt.Fprintf(&b, "package %s;\n\n", protoPackage)
	b.WriteString("import \"google/protobuf/timestamp.proto\";\n\n")
	fmt.Fprintf(&b, "option go_package = %q;\n\n", packageImport+"/transport/rpc/pb;pb")
	fmt.Fprintf(&b, "service %s {\n", spec.RPC.Service)
	fmt.Fprintf(&b, "  rpc Create%s(Create%sRequest) returns (%sMessage);\n", object, object, object)
	fmt.Fprintf(&b, "  rpc Get%s(Get%sRequest) returns (%sMessage);\n", object, object, object)
	fmt.Fprintf(&b, "  rpc List%s(List%sRequest) returns (List%sResponse);\n", plural, plural, plural)
	fmt.Fprintf(&b, "  rpc Update%s(Update%sRequest) returns (%sMessage);\n", object, object, object)
	fmt.Fprintf(&b, "  rpc Delete%s(Delete%sRequest) returns (Delete%sResponse);\n", object, object, object)
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "message %sMessage {\n  string id = 1;\n", object)
	index := 2
	if spec.TenantScoped {
		fmt.Fprintf(&b, "  string tenant_id = %d;\n", index)
		index++
	}
	for _, field := range spec.Fields {
		fmt.Fprintf(&b, "  %s %s = %d;\n", protoType(field.Type), field.Name, index)
		index++
	}
	fmt.Fprintf(&b, "  uint64 version = %d;\n", index)
	index++
	fmt.Fprintf(&b, "  google.protobuf.Timestamp created_at = %d;\n", index)
	index++
	fmt.Fprintf(&b, "  google.protobuf.Timestamp updated_at = %d;\n", index)
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "message Create%sRequest {\n", object)
	writeProtoFields(&b, spec.Fields, 1)
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "message Get%sRequest { string id = 1; }\n", object)
	fmt.Fprintf(&b, "message List%sRequest { int32 limit = 1; int32 offset = 2; }\n", plural)
	fmt.Fprintf(&b, "message List%sResponse { repeated %sMessage items = 1; }\n", plural, object)
	fmt.Fprintf(&b, "message Update%sRequest { string id = 1; uint64 version = 2;\n", object)
	writeProtoFields(&b, spec.Fields, 3)
	b.WriteString("}\n")
	fmt.Fprintf(&b, "message Delete%sRequest { string id = 1; uint64 version = 2; }\n", object)
	fmt.Fprintf(&b, "message Delete%sResponse {}\n", object)
	return b.String()
}

func writeProtoFields(b *strings.Builder, fields []Field, start int) {
	index := start
	for _, field := range fields {
		fmt.Fprintf(b, "  %s %s = %d;\n", protoType(field.Type), field.Name, index)
		index++
	}
}
