package audit

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestCollectGoSourceIsDeterministicAndNormalized(t *testing.T) {
	root := t.TempDir()
	writeAuditSource(t, filepath.Join(root, "internal", "tenant", "application", "service.go"), `package application

import (
	"example.com/demo/internal/device/ports"
	"context"
)

var _ = context.Background
var _ ports.DeviceRepository
`)
	writeAuditSource(t, filepath.Join(root, "internal", "tenant", "application", "service_test.go"), `package application

import "testing"

var _ *testing.T
`)
	writeAuditSource(t, filepath.Join(root, "internal", "tenant", "application", "zz_yunka_port_gen.go"), `// Code generated by yunka contract; DO NOT EDIT.
package application

import "context"

var _ = context.Background
`)
	writeAuditSource(t, filepath.Join(root, "internal", "device", "application", "read.go"), `package application

import (
	"strings"
	"context"
	"strings"
)

var _ = context.Background
var _ = strings.TrimSpace
`)
	writeAuditSource(t, filepath.Join(root, "internal", "vendor", "ignored.go"), "package vendor\n")

	first, err := CollectGoSource(root, "internal")
	if err != nil {
		t.Fatal(err)
	}
	second, err := CollectGoSource(root, filepath.Join(root, "internal"))
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatalf("source evidence is not deterministic:\nfirst=%#v\nsecond=%#v", first, second)
	}
	if first.SourceRoot != "internal" {
		t.Fatalf("source root=%q", first.SourceRoot)
	}
	if len(first.Files) != 4 {
		t.Fatalf("files=%d want=4: %#v", len(first.Files), first.Files)
	}
	wantPaths := []string{
		"internal/device/application/read.go",
		"internal/tenant/application/service.go",
		"internal/tenant/application/service_test.go",
		"internal/tenant/application/zz_yunka_port_gen.go",
	}
	for index, want := range wantPaths {
		if first.Files[index].Path != want {
			t.Fatalf("file[%d]=%q want=%q", index, first.Files[index].Path, want)
		}
	}
	if first.Files[0].Imports[0] != "context" || first.Files[0].Imports[1] != "strings" || len(first.Files[0].Imports) != 2 {
		t.Fatalf("imports were not normalized: %#v", first.Files[0].Imports)
	}
	if !first.Files[2].Test {
		t.Fatal("test file was not identified")
	}
	if !first.Files[3].Generated {
		t.Fatal("canonical generated marker was not identified")
	}
}

func TestCollectGoSourceMissingRootIsEmptyEvidence(t *testing.T) {
	root := t.TempDir()
	snapshot, err := CollectGoSource(root, "internal")
	if err != nil {
		t.Fatal(err)
	}
	if snapshot.SourceRoot != "internal" || len(snapshot.Files) != 0 {
		t.Fatalf("unexpected missing-root snapshot: %#v", snapshot)
	}
}

func TestCollectGoSourceRejectsSourceOutsideProject(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	_, err := CollectGoSource(root, outside)
	if err == nil || !strings.Contains(err.Error(), "outside project root") {
		t.Fatalf("expected outside-root rejection, got %v", err)
	}
}

func writeAuditSource(t *testing.T, path, contents string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}
