// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/site/domain"
	"gorm.io/gorm"
	"time"
)

type SitePOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	TenantID  string         `gorm:"column:tenant_id;type:varchar(64);not null;index"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type SitePORecord struct {
	SitePO     `gorm:"embedded"`
	SitePOBase `gorm:"embedded"`
}

func (SitePORecord) TableName() string { return "biz_site_site" }
func (record SitePORecord) Domain() domain.Site {
	return domain.Site{ID: record.ID, TenantID: record.TenantID, Name: record.SitePO.Name, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func siteRecordFromDomain(value domain.Site) SitePORecord {
	record := SitePORecord{}
	record.ID = value.ID
	record.TenantID = value.TenantID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	record.SitePO.Name = value.Name
	return record
}
