// Code generated by yunka domain; DO NOT EDIT.

package application

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	domain "github.com/hvritual/biz/internal/iam/domain"
	ports "github.com/hvritual/biz/internal/iam/ports"
	"time"
	"yunka.io/framework/requestscope"
)

type Service interface {
	CreateAPIToken(context.Context, CreateAPITokenInput) (APITokenOutput, error)
	GetAPIToken(context.Context, GetAPITokenInput) (APITokenOutput, error)
	ListApiTokens(context.Context, ListApiTokensInput) (ListApiTokensOutput, error)
	UpdateAPIToken(context.Context, UpdateAPITokenInput) (APITokenOutput, error)
	DeleteAPIToken(context.Context, DeleteAPITokenInput) error
	CreateMemberRole(context.Context, CreateMemberRoleInput) (MemberRoleOutput, error)
	GetMemberRole(context.Context, GetMemberRoleInput) (MemberRoleOutput, error)
	ListMemberRoles(context.Context, ListMemberRolesInput) (ListMemberRolesOutput, error)
	UpdateMemberRole(context.Context, UpdateMemberRoleInput) (MemberRoleOutput, error)
	DeleteMemberRole(context.Context, DeleteMemberRoleInput) error
	CreateMemberSite(context.Context, CreateMemberSiteInput) (MemberSiteOutput, error)
	GetMemberSite(context.Context, GetMemberSiteInput) (MemberSiteOutput, error)
	ListMemberSites(context.Context, ListMemberSitesInput) (ListMemberSitesOutput, error)
	UpdateMemberSite(context.Context, UpdateMemberSiteInput) (MemberSiteOutput, error)
	DeleteMemberSite(context.Context, DeleteMemberSiteInput) error
	CreateMembership(context.Context, CreateMembershipInput) (MembershipOutput, error)
	GetMembership(context.Context, GetMembershipInput) (MembershipOutput, error)
	ListMemberships(context.Context, ListMembershipsInput) (ListMembershipsOutput, error)
	UpdateMembership(context.Context, UpdateMembershipInput) (MembershipOutput, error)
	DeleteMembership(context.Context, DeleteMembershipInput) error
	CreateRole(context.Context, CreateRoleInput) (RoleOutput, error)
	GetRole(context.Context, GetRoleInput) (RoleOutput, error)
	ListRoles(context.Context, ListRolesInput) (ListRolesOutput, error)
	UpdateRole(context.Context, UpdateRoleInput) (RoleOutput, error)
	DeleteRole(context.Context, DeleteRoleInput) error
	CreateRolePermission(context.Context, CreateRolePermissionInput) (RolePermissionOutput, error)
	GetRolePermission(context.Context, GetRolePermissionInput) (RolePermissionOutput, error)
	ListRolePermissions(context.Context, ListRolePermissionsInput) (ListRolePermissionsOutput, error)
	UpdateRolePermission(context.Context, UpdateRolePermissionInput) (RolePermissionOutput, error)
	DeleteRolePermission(context.Context, DeleteRolePermissionInput) error
	CreateTenant(context.Context, CreateTenantInput) (TenantOutput, error)
	GetTenant(context.Context, GetTenantInput) (TenantOutput, error)
	ListTenants(context.Context, ListTenantsInput) (ListTenantsOutput, error)
	UpdateTenant(context.Context, UpdateTenantInput) (TenantOutput, error)
	DeleteTenant(context.Context, DeleteTenantInput) error
	CreateUser(context.Context, CreateUserInput) (UserOutput, error)
	GetUser(context.Context, GetUserInput) (UserOutput, error)
	ListUsers(context.Context, ListUsersInput) (ListUsersOutput, error)
	UpdateUser(context.Context, UpdateUserInput) (UserOutput, error)
	DeleteUser(context.Context, DeleteUserInput) error
}

type CreateAPITokenInput struct {
}
type GetAPITokenInput struct{ ID string }
type ListApiTokensInput struct {
	Limit  int
	Offset int
}
type UpdateAPITokenInput struct {
	ID      string
	Version uint64
}
type DeleteAPITokenInput struct {
	ID      string
	Version uint64
}
type APITokenOutput struct {
	Value domain.APIToken `json:"value"`
}
type ListApiTokensOutput struct {
	Items []domain.APIToken `json:"items"`
}

type CreateMemberRoleInput struct {
}
type GetMemberRoleInput struct{ ID string }
type ListMemberRolesInput struct {
	Limit  int
	Offset int
}
type UpdateMemberRoleInput struct {
	ID      string
	Version uint64
}
type DeleteMemberRoleInput struct {
	ID      string
	Version uint64
}
type MemberRoleOutput struct {
	Value domain.MemberRole `json:"value"`
}
type ListMemberRolesOutput struct {
	Items []domain.MemberRole `json:"items"`
}

type CreateMemberSiteInput struct {
}
type GetMemberSiteInput struct{ ID string }
type ListMemberSitesInput struct {
	Limit  int
	Offset int
}
type UpdateMemberSiteInput struct {
	ID      string
	Version uint64
}
type DeleteMemberSiteInput struct {
	ID      string
	Version uint64
}
type MemberSiteOutput struct {
	Value domain.MemberSite `json:"value"`
}
type ListMemberSitesOutput struct {
	Items []domain.MemberSite `json:"items"`
}

type CreateMembershipInput struct {
	Status string `json:"status"`
}
type GetMembershipInput struct{ ID string }
type ListMembershipsInput struct {
	Limit  int
	Offset int
}
type UpdateMembershipInput struct {
	ID      string
	Version uint64
	Status  string `json:"status"`
}
type DeleteMembershipInput struct {
	ID      string
	Version uint64
}
type MembershipOutput struct {
	Value domain.Membership `json:"value"`
}
type ListMembershipsOutput struct {
	Items []domain.Membership `json:"items"`
}

type CreateRoleInput struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}
type GetRoleInput struct{ ID string }
type ListRolesInput struct {
	Limit  int
	Offset int
}
type UpdateRoleInput struct {
	ID      string
	Version uint64
	Name    string `json:"name"`
	Status  string `json:"status"`
}
type DeleteRoleInput struct {
	ID      string
	Version uint64
}
type RoleOutput struct {
	Value domain.Role `json:"value"`
}
type ListRolesOutput struct {
	Items []domain.Role `json:"items"`
}

type CreateRolePermissionInput struct {
	DataScope  string `json:"dataScope"`
	Permission string `json:"permission"`
}
type GetRolePermissionInput struct{ ID string }
type ListRolePermissionsInput struct {
	Limit  int
	Offset int
}
type UpdateRolePermissionInput struct {
	ID         string
	Version    uint64
	DataScope  string `json:"dataScope"`
	Permission string `json:"permission"`
}
type DeleteRolePermissionInput struct {
	ID      string
	Version uint64
}
type RolePermissionOutput struct {
	Value domain.RolePermission `json:"value"`
}
type ListRolePermissionsOutput struct {
	Items []domain.RolePermission `json:"items"`
}

type CreateTenantInput struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}
type GetTenantInput struct{ ID string }
type ListTenantsInput struct {
	Limit  int
	Offset int
}
type UpdateTenantInput struct {
	ID      string
	Version uint64
	Name    string `json:"name"`
	Status  string `json:"status"`
}
type DeleteTenantInput struct {
	ID      string
	Version uint64
}
type TenantOutput struct {
	Value domain.Tenant `json:"value"`
}
type ListTenantsOutput struct {
	Items []domain.Tenant `json:"items"`
}

type CreateUserInput struct {
	Email  string `json:"email"`
	Status string `json:"status"`
}
type GetUserInput struct{ ID string }
type ListUsersInput struct {
	Limit  int
	Offset int
}
type UpdateUserInput struct {
	ID      string
	Version uint64
	Email   string `json:"email"`
	Status  string `json:"status"`
}
type DeleteUserInput struct {
	ID      string
	Version uint64
}
type UserOutput struct {
	Value domain.User `json:"value"`
}
type ListUsersOutput struct {
	Items []domain.User `json:"items"`
}

type DefaultService struct {
	scopes requestscope.ScopeFactory[ports.Repositories]
}

func NewService(scopes requestscope.ScopeFactory[ports.Repositories]) (*DefaultService, error) {
	if scopes == nil {
		return nil, errors.New("domain application: request scope factory is required")
	}
	return &DefaultService{scopes: scopes}, nil
}

func (service *DefaultService) CreateAPIToken(ctx context.Context, input CreateAPITokenInput) (APITokenOutput, error) {
	value := domain.APIToken{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC()}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.APIToken, error) {
		if err := scope.Repositories().APIToken.Create(scope.Context(), &value); err != nil {
			return domain.APIToken{}, err
		}
		return value, nil
	})
	return APITokenOutput{Value: created}, err
}
func (service *DefaultService) GetAPIToken(ctx context.Context, input GetAPITokenInput) (APITokenOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.APIToken, error) {
		return scope.Repositories().APIToken.Get(scope.Context(), input.ID)
	})
	return APITokenOutput{Value: value}, err
}
func (service *DefaultService) ListApiTokens(ctx context.Context, input ListApiTokensInput) (ListApiTokensOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.APIToken, error) {
		return scope.Repositories().APIToken.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListApiTokensOutput{Items: items}, err
}
func (service *DefaultService) UpdateAPIToken(ctx context.Context, input UpdateAPITokenInput) (APITokenOutput, error) {
	value := domain.APIToken{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC()}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.APIToken, error) {
		repository := scope.Repositories().APIToken
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.APIToken{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return APITokenOutput{Value: updated}, err
}
func (service *DefaultService) DeleteAPIToken(ctx context.Context, input DeleteAPITokenInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().APIToken.Delete(scope.Context(), input.ID, input.Version)
	})
}

func (service *DefaultService) CreateMemberRole(ctx context.Context, input CreateMemberRoleInput) (MemberRoleOutput, error) {
	value := domain.MemberRole{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC()}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.MemberRole, error) {
		if err := scope.Repositories().MemberRole.Create(scope.Context(), &value); err != nil {
			return domain.MemberRole{}, err
		}
		return value, nil
	})
	return MemberRoleOutput{Value: created}, err
}
func (service *DefaultService) GetMemberRole(ctx context.Context, input GetMemberRoleInput) (MemberRoleOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.MemberRole, error) {
		return scope.Repositories().MemberRole.Get(scope.Context(), input.ID)
	})
	return MemberRoleOutput{Value: value}, err
}
func (service *DefaultService) ListMemberRoles(ctx context.Context, input ListMemberRolesInput) (ListMemberRolesOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.MemberRole, error) {
		return scope.Repositories().MemberRole.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListMemberRolesOutput{Items: items}, err
}
func (service *DefaultService) UpdateMemberRole(ctx context.Context, input UpdateMemberRoleInput) (MemberRoleOutput, error) {
	value := domain.MemberRole{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC()}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.MemberRole, error) {
		repository := scope.Repositories().MemberRole
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.MemberRole{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return MemberRoleOutput{Value: updated}, err
}
func (service *DefaultService) DeleteMemberRole(ctx context.Context, input DeleteMemberRoleInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().MemberRole.Delete(scope.Context(), input.ID, input.Version)
	})
}

func (service *DefaultService) CreateMemberSite(ctx context.Context, input CreateMemberSiteInput) (MemberSiteOutput, error) {
	value := domain.MemberSite{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC()}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.MemberSite, error) {
		if err := scope.Repositories().MemberSite.Create(scope.Context(), &value); err != nil {
			return domain.MemberSite{}, err
		}
		return value, nil
	})
	return MemberSiteOutput{Value: created}, err
}
func (service *DefaultService) GetMemberSite(ctx context.Context, input GetMemberSiteInput) (MemberSiteOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.MemberSite, error) {
		return scope.Repositories().MemberSite.Get(scope.Context(), input.ID)
	})
	return MemberSiteOutput{Value: value}, err
}
func (service *DefaultService) ListMemberSites(ctx context.Context, input ListMemberSitesInput) (ListMemberSitesOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.MemberSite, error) {
		return scope.Repositories().MemberSite.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListMemberSitesOutput{Items: items}, err
}
func (service *DefaultService) UpdateMemberSite(ctx context.Context, input UpdateMemberSiteInput) (MemberSiteOutput, error) {
	value := domain.MemberSite{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC()}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.MemberSite, error) {
		repository := scope.Repositories().MemberSite
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.MemberSite{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return MemberSiteOutput{Value: updated}, err
}
func (service *DefaultService) DeleteMemberSite(ctx context.Context, input DeleteMemberSiteInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().MemberSite.Delete(scope.Context(), input.ID, input.Version)
	})
}

func (service *DefaultService) CreateMembership(ctx context.Context, input CreateMembershipInput) (MembershipOutput, error) {
	value := domain.Membership{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC(), Status: input.Status}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Membership, error) {
		if err := scope.Repositories().Membership.Create(scope.Context(), &value); err != nil {
			return domain.Membership{}, err
		}
		return value, nil
	})
	return MembershipOutput{Value: created}, err
}
func (service *DefaultService) GetMembership(ctx context.Context, input GetMembershipInput) (MembershipOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Membership, error) {
		return scope.Repositories().Membership.Get(scope.Context(), input.ID)
	})
	return MembershipOutput{Value: value}, err
}
func (service *DefaultService) ListMemberships(ctx context.Context, input ListMembershipsInput) (ListMembershipsOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.Membership, error) {
		return scope.Repositories().Membership.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListMembershipsOutput{Items: items}, err
}
func (service *DefaultService) UpdateMembership(ctx context.Context, input UpdateMembershipInput) (MembershipOutput, error) {
	value := domain.Membership{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC(), Status: input.Status}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Membership, error) {
		repository := scope.Repositories().Membership
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.Membership{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return MembershipOutput{Value: updated}, err
}
func (service *DefaultService) DeleteMembership(ctx context.Context, input DeleteMembershipInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().Membership.Delete(scope.Context(), input.ID, input.Version)
	})
}

func (service *DefaultService) CreateRole(ctx context.Context, input CreateRoleInput) (RoleOutput, error) {
	value := domain.Role{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC(), Name: input.Name, Status: input.Status}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Role, error) {
		if err := scope.Repositories().Role.Create(scope.Context(), &value); err != nil {
			return domain.Role{}, err
		}
		return value, nil
	})
	return RoleOutput{Value: created}, err
}
func (service *DefaultService) GetRole(ctx context.Context, input GetRoleInput) (RoleOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Role, error) {
		return scope.Repositories().Role.Get(scope.Context(), input.ID)
	})
	return RoleOutput{Value: value}, err
}
func (service *DefaultService) ListRoles(ctx context.Context, input ListRolesInput) (ListRolesOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.Role, error) {
		return scope.Repositories().Role.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListRolesOutput{Items: items}, err
}
func (service *DefaultService) UpdateRole(ctx context.Context, input UpdateRoleInput) (RoleOutput, error) {
	value := domain.Role{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC(), Name: input.Name, Status: input.Status}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Role, error) {
		repository := scope.Repositories().Role
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.Role{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return RoleOutput{Value: updated}, err
}
func (service *DefaultService) DeleteRole(ctx context.Context, input DeleteRoleInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().Role.Delete(scope.Context(), input.ID, input.Version)
	})
}

func (service *DefaultService) CreateRolePermission(ctx context.Context, input CreateRolePermissionInput) (RolePermissionOutput, error) {
	value := domain.RolePermission{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC(), DataScope: input.DataScope, Permission: input.Permission}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.RolePermission, error) {
		if err := scope.Repositories().RolePermission.Create(scope.Context(), &value); err != nil {
			return domain.RolePermission{}, err
		}
		return value, nil
	})
	return RolePermissionOutput{Value: created}, err
}
func (service *DefaultService) GetRolePermission(ctx context.Context, input GetRolePermissionInput) (RolePermissionOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.RolePermission, error) {
		return scope.Repositories().RolePermission.Get(scope.Context(), input.ID)
	})
	return RolePermissionOutput{Value: value}, err
}
func (service *DefaultService) ListRolePermissions(ctx context.Context, input ListRolePermissionsInput) (ListRolePermissionsOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.RolePermission, error) {
		return scope.Repositories().RolePermission.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListRolePermissionsOutput{Items: items}, err
}
func (service *DefaultService) UpdateRolePermission(ctx context.Context, input UpdateRolePermissionInput) (RolePermissionOutput, error) {
	value := domain.RolePermission{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC(), DataScope: input.DataScope, Permission: input.Permission}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.RolePermission, error) {
		repository := scope.Repositories().RolePermission
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.RolePermission{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return RolePermissionOutput{Value: updated}, err
}
func (service *DefaultService) DeleteRolePermission(ctx context.Context, input DeleteRolePermissionInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().RolePermission.Delete(scope.Context(), input.ID, input.Version)
	})
}

func (service *DefaultService) CreateTenant(ctx context.Context, input CreateTenantInput) (TenantOutput, error) {
	value := domain.Tenant{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC(), Name: input.Name, Status: input.Status}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Tenant, error) {
		if err := scope.Repositories().Tenant.Create(scope.Context(), &value); err != nil {
			return domain.Tenant{}, err
		}
		return value, nil
	})
	return TenantOutput{Value: created}, err
}
func (service *DefaultService) GetTenant(ctx context.Context, input GetTenantInput) (TenantOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Tenant, error) {
		return scope.Repositories().Tenant.Get(scope.Context(), input.ID)
	})
	return TenantOutput{Value: value}, err
}
func (service *DefaultService) ListTenants(ctx context.Context, input ListTenantsInput) (ListTenantsOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.Tenant, error) {
		return scope.Repositories().Tenant.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListTenantsOutput{Items: items}, err
}
func (service *DefaultService) UpdateTenant(ctx context.Context, input UpdateTenantInput) (TenantOutput, error) {
	value := domain.Tenant{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC(), Name: input.Name, Status: input.Status}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.Tenant, error) {
		repository := scope.Repositories().Tenant
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.Tenant{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return TenantOutput{Value: updated}, err
}
func (service *DefaultService) DeleteTenant(ctx context.Context, input DeleteTenantInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().Tenant.Delete(scope.Context(), input.ID, input.Version)
	})
}

func (service *DefaultService) CreateUser(ctx context.Context, input CreateUserInput) (UserOutput, error) {
	value := domain.User{ID: newID(), Version: 1, CreatedAt: time.Now().UTC(), UpdatedAt: time.Now().UTC(), Email: input.Email, Status: input.Status}
	created, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.User, error) {
		if err := scope.Repositories().User.Create(scope.Context(), &value); err != nil {
			return domain.User{}, err
		}
		return value, nil
	})
	return UserOutput{Value: created}, err
}
func (service *DefaultService) GetUser(ctx context.Context, input GetUserInput) (UserOutput, error) {
	value, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.User, error) {
		return scope.Repositories().User.Get(scope.Context(), input.ID)
	})
	return UserOutput{Value: value}, err
}
func (service *DefaultService) ListUsers(ctx context.Context, input ListUsersInput) (ListUsersOutput, error) {
	items, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) ([]domain.User, error) {
		return scope.Repositories().User.List(scope.Context(), input.Limit, input.Offset)
	})
	return ListUsersOutput{Items: items}, err
}
func (service *DefaultService) UpdateUser(ctx context.Context, input UpdateUserInput) (UserOutput, error) {
	value := domain.User{ID: input.ID, Version: input.Version, UpdatedAt: time.Now().UTC(), Email: input.Email, Status: input.Status}
	updated, err := requestscope.ExecuteValue(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) (domain.User, error) {
		repository := scope.Repositories().User
		if err := repository.Update(scope.Context(), &value, input.Version); err != nil {
			return domain.User{}, err
		}
		return repository.Get(scope.Context(), input.ID)
	})
	return UserOutput{Value: updated}, err
}
func (service *DefaultService) DeleteUser(ctx context.Context, input DeleteUserInput) error {
	return requestscope.Execute(ctx, service.scopes, func(scope *requestscope.Scope[ports.Repositories]) error {
		return scope.Repositories().User.Delete(scope.Context(), input.ID, input.Version)
	})
}

func newID() string {
	var value [16]byte
	if _, err := rand.Read(value[:]); err != nil {
		panic(err)
	}
	return hex.EncodeToString(value[:])
}
