// Code generated by yunka module; DO NOT EDIT.

package deviceops

import (
	"fmt"

	"yunka.io/framework/core/modulecatalog"
)

func GeneratedDescriptor() modulecatalog.Descriptor {
	return modulecatalog.Descriptor{
		Name:    ModuleName,
		Version: "v0.1.0",
		Requirements: modulecatalog.Requirements{
			ConfigKey: "modules.deviceops",
			Logger:    true,
			Databases: []modulecatalog.DatabaseRequirement{{Name: "primary"}},
		},
		Build: generatedBuild,
	}
}

func generatedBuild(context modulecatalog.BuildContext) (modulecatalog.Instance, error) {
	config := DefaultConfig()
	if err := context.Config().Decode(ModuleName, "modules.deviceops", &config); err != nil {
		return nil, fmt.Errorf("%s config: %w", ModuleName, err)
	}
	if err := config.Validate(); err != nil {
		return nil, fmt.Errorf("%s config validation: %w", ModuleName, err)
	}
	database, err := context.Databases().GORM("primary")
	if err != nil {
		return nil, fmt.Errorf("%s database primary: %w", ModuleName, err)
	}
	return NewModule(Dependencies{
		Config:          config,
		Logger:          context.Logger(),
		PrimaryDatabase: database,
	})
}
