// Code generated by protoc-gen-go. DO NOT EDIT.
// source: environment.proto

package sms

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Environment struct {
	ClientIP             string   `protobuf:"bytes,1,opt,name=clientIP,proto3" json:"clientIP,omitempty"`
	Browser              string   `protobuf:"bytes,2,opt,name=browser,proto3" json:"browser,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Environment) Reset()         { *m = Environment{} }
func (m *Environment) String() string { return proto.CompactTextString(m) }
func (*Environment) ProtoMessage()    {}
func (*Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_64e647b85623514a, []int{0}
}

func (m *Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Environment.Unmarshal(m, b)
}
func (m *Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Environment.Marshal(b, m, deterministic)
}
func (m *Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Environment.Merge(m, src)
}
func (m *Environment) XXX_Size() int {
	return xxx_messageInfo_Environment.Size(m)
}
func (m *Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Environment proto.InternalMessageInfo

func (m *Environment) GetClientIP() string {
	if m != nil {
		return m.ClientIP
	}
	return ""
}

func (m *Environment) GetBrowser() string {
	if m != nil {
		return m.Browser
	}
	return ""
}

func (m *Environment) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*Environment)(nil), "Environment")
}

func init() { proto.RegisterFile("environment.proto", fileDescriptor_64e647b85623514a) }

var fileDescriptor_64e647b85623514a = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0xcd, 0x2b, 0xcb,
	0x2c, 0xca, 0xcf, 0xcb, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe7,
	0xe2, 0x76, 0x45, 0x08, 0x0a, 0x49, 0x71, 0x71, 0x24, 0xe7, 0x64, 0xa6, 0xe6, 0x95, 0x78, 0x06,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x42, 0x12, 0x5c, 0xec, 0x49, 0x45, 0xf9,
	0xe5, 0xc5, 0xa9, 0x45, 0x12, 0x4c, 0x60, 0x29, 0x18, 0x57, 0x48, 0x88, 0x8b, 0x25, 0x39, 0x3f,
	0x25, 0x55, 0x82, 0x19, 0x2c, 0x0c, 0x66, 0x3b, 0xb1, 0x46, 0x31, 0x17, 0xe7, 0x16, 0x27, 0xb1,
	0x81, 0xad, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x76, 0x6e, 0x45, 0xe7, 0x7b, 0x00, 0x00,
	0x00,
}
