package change

import (
	"path/filepath"
	"strings"
	"testing"

	"yunka.io/app/cmd/add"
)

func TestT4CreateChangeSetBindsLegacyProtobufOutputsAndNormalizesAPIKey(t *testing.T) {
	fixture := newPressureFixture(t)
	writePressureFile(t, filepath.Join(fixture.Root, "contracts", "tenant", "tenant.pb.go"), "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage tenantv1\n")
	writePressureFile(t, filepath.Join(fixture.Root, "contracts", "tenant", "tenant_grpc.pb.go"), "// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\npackage tenantv1\n")
	gitPressure(t, fixture.Root, "add", "contracts/tenant/tenant.pb.go", "contracts/tenant/tenant_grpc.pb.go")
	gitPressure(t, fixture.Root, "commit", "-m", "legacy protobuf generated outputs")

	options := apiKeyArchiveOptions(fixture.Root)
	planPath := writePlanReport(t, fixture.Root, options, "t4-biz-legacy-plan.json")
	value, _, err := BuildChangeSet(fixture.Root, "HEAD", nil, []string{planPath})
	if err != nil {
		t.Fatal(err)
	}
	assertGeneratedPaths(t, value, []string{
		"contracts/tenant/tenant.pb.go",
		"contracts/tenant/tenant_grpc.pb.go",
	})

	if _, err := add.AddOperation(options); err != nil {
		t.Fatal(err)
	}
	generatePressureProject(t, fixture)
	report, err := ReconcileChangeSet(fixture.Root, value)
	if err != nil {
		t.Fatal(err)
	}
	if !report.Conformant || len(report.Reconciliation.Violations) != 0 || len(report.Semantic.Violations) != 0 {
		t.Fatalf("matching api-key create ChangeSet did not reconcile: %#v", report)
	}
}

func TestT4CreateChangeSetRejectsSpoofedLegacyProtobufOutput(t *testing.T) {
	fixture := newPressureFixture(t)
	writePressureFile(t, filepath.Join(fixture.Root, "contracts", "tenant", "tenant.pb.go"), "package tenantv1\n\n// handwritten file using a generated-looking name\n")
	gitPressure(t, fixture.Root, "add", "contracts/tenant/tenant.pb.go")
	gitPressure(t, fixture.Root, "commit", "-m", "spoof protobuf output")

	planPath := writePlanReport(t, fixture.Root, apiKeyArchiveOptions(fixture.Root), "t4-biz-spoof-plan.json")
	_, _, err := BuildChangeSet(fixture.Root, "HEAD", nil, []string{planPath})
	if err == nil || !strings.Contains(err.Error(), "does not prove generator ownership") {
		t.Fatalf("spoofed protobuf output was not rejected: %v", err)
	}
}

func TestT4CreateChangeSetStrictManifestBindsOnlyCurrentSourceOutputs(t *testing.T) {
	fixture := newPressureFixture(t)
	writePressureFile(t, filepath.Join(fixture.Root, ".yunka", "protobuf-go.json"), `{
  "schemaVersion": 1,
  "files": [
    "contracts/other/other.pb.go",
    "contracts/tenant/tenant.pb.go",
    "contracts/tenant/tenant_grpc.pb.go"
  ]
}
`)

	planPath := writePlanReport(t, fixture.Root, apiKeyArchiveOptions(fixture.Root), "t4-biz-strict-plan.json")
	value, _, err := BuildChangeSet(fixture.Root, "HEAD", nil, []string{planPath})
	if err != nil {
		t.Fatal(err)
	}
	assertGeneratedPaths(t, value, []string{
		"contracts/tenant/tenant.pb.go",
		"contracts/tenant/tenant_grpc.pb.go",
	})
	for _, path := range value.Subjects[0].Create.GeneratedPaths {
		if path == "contracts/other/other.pb.go" {
			t.Fatalf("unrelated manifest output escaped source-specific ChangeSet boundary: %#v", value.Subjects[0].Create.GeneratedPaths)
		}
	}
}

func apiKeyArchiveOptions(root string) add.OperationOptions {
	return add.OperationOptions{
		Root: root, ApplicationKey: "tenant/lifecycle", OperationID: "tenant.archive", UseCase: "archive_tenant",
		Access: "protected", Permissions: []string{"tenant.archive"}, PermissionMode: "all", Tenant: "required",
		Authentication: []string{"api-key"}, Transaction: "local", Idempotency: "none", Composition: "local",
	}
}

func writePlanReport(t *testing.T, root string, options add.OperationOptions, filename string) string {
	t.Helper()
	plan, err := add.PlanOperation(options)
	if err != nil {
		t.Fatal(err)
	}
	planJSON, err := add.Render(plan, add.FormatAgentJSON)
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.ToSlash(filepath.Join(".yunka", filename))
	writePressureFile(t, filepath.Join(root, filepath.FromSlash(path)), planJSON)
	return path
}

func assertGeneratedPaths(t *testing.T, value ChangeSet, expected []string) {
	t.Helper()
	if len(value.Subjects) != 1 || value.Subjects[0].Create == nil {
		t.Fatalf("create subject=%#v", value.Subjects)
	}
	paths := map[string]bool{}
	for _, path := range value.Subjects[0].Create.GeneratedPaths {
		paths[path] = true
	}
	for _, path := range expected {
		if !paths[path] {
			t.Fatalf("exact protobuf Go ownership path %s missing from create ChangeSet: %#v", path, value.Subjects[0].Create.GeneratedPaths)
		}
	}
}
