// Code generated by yunka domain; DO NOT EDIT.

package rest

import (
	"encoding/json"
	application "github.com/hvritual/biz/internal/device/application"
	"net/http"
	"strconv"
)

func Register(mux *http.ServeMux, service application.Service) {
	mux.HandleFunc("POST /v1/devices", func(w http.ResponseWriter, r *http.Request) { createDevice(w, r, service) })
	mux.HandleFunc("GET /v1/devices", func(w http.ResponseWriter, r *http.Request) { listDevice(w, r, service) })
	mux.HandleFunc("GET /v1/devices/{id}", func(w http.ResponseWriter, r *http.Request) { getDevice(w, r, service) })
	mux.HandleFunc("PUT /v1/devices/{id}", func(w http.ResponseWriter, r *http.Request) { updateDevice(w, r, service) })
	mux.HandleFunc("DELETE /v1/devices/{id}", func(w http.ResponseWriter, r *http.Request) { deleteDevice(w, r, service) })
}

type createDeviceRequest struct {
	CreatedBy string `json:"createdBy"`
	Name      string `json:"name"`
	Serial    string `json:"serial"`
	SiteID    string `json:"siteId"`
}
type updateDeviceRequest struct {
	Version   uint64 `json:"version"`
	CreatedBy string `json:"createdBy"`
	Name      string `json:"name"`
	Serial    string `json:"serial"`
	SiteID    string `json:"siteId"`
}

func createDevice(w http.ResponseWriter, r *http.Request, service application.Service) {
	var wire createDeviceRequest
	if err := json.NewDecoder(r.Body).Decode(&wire); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	output, err := service.CreateDevice(r.Context(), application.CreateDeviceInput{CreatedBy: wire.CreatedBy, Name: wire.Name, Serial: wire.Serial, SiteID: wire.SiteID})
	writeJSON(w, output, err)
}
func getDevice(w http.ResponseWriter, r *http.Request, service application.Service) {
	output, err := service.GetDevice(r.Context(), application.GetDeviceInput{ID: r.PathValue("id")})
	writeJSON(w, output, err)
}
func listDevice(w http.ResponseWriter, r *http.Request, service application.Service) {
	limit, _ := strconv.Atoi(r.URL.Query().Get("limit"))
	offset, _ := strconv.Atoi(r.URL.Query().Get("offset"))
	output, err := service.ListDevices(r.Context(), application.ListDevicesInput{Limit: limit, Offset: offset})
	writeJSON(w, output, err)
}
func updateDevice(w http.ResponseWriter, r *http.Request, service application.Service) {
	var wire updateDeviceRequest
	if err := json.NewDecoder(r.Body).Decode(&wire); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	output, err := service.UpdateDevice(r.Context(), application.UpdateDeviceInput{ID: r.PathValue("id"), Version: wire.Version, CreatedBy: wire.CreatedBy, Name: wire.Name, Serial: wire.Serial, SiteID: wire.SiteID})
	writeJSON(w, output, err)
}
func deleteDevice(w http.ResponseWriter, r *http.Request, service application.Service) {
	version, _ := strconv.ParseUint(r.URL.Query().Get("version"), 10, 64)
	if err := service.DeleteDevice(r.Context(), application.DeleteDeviceInput{ID: r.PathValue("id"), Version: version}); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
func writeJSON(w http.ResponseWriter, value any, err error) {
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(value)
}
