syntax = "proto3";

import "api_common.proto";
option go_package = "meta";

message Api {
    string uuid = 1;
    string name = 2;
    bool isCheck = 3;
}

message GetApiRequest {
    repeated string uuids = 1;
}

message GetApiReponse {
    repeated Api apis = 1;
};

message FindAllRuntimeAPIRequest {
}

message FindAllRuntimeAPIResponse {
    repeated RuntimeApi apis = 1;
}


service ApiService {
    rpc GetApiByUUID (GetApiRequest) returns (GetApiReponse);
    rpc FindAllRuntimeAPI (FindAllRuntimeAPIRequest) returns (FindAllRuntimeAPIResponse);
}