// Code generated by yunka domain; DO NOT EDIT.

package wire

import (
	"context"
	"fmt"
	application "github.com/hvritual/biz/internal/device/application"
	persistence "github.com/hvritual/biz/internal/device/infrastructure/persistence"
	rest "github.com/hvritual/biz/internal/device/transport/rest"
	rpc "github.com/hvritual/biz/internal/device/transport/rpc"
	grpc "google.golang.org/grpc"
	"gorm.io/gorm"
	"net/http"
)

type Bundle struct{ Service application.Service }

func Build(database *gorm.DB) (Bundle, error) {
	if err := persistence.AutoMigrate(context.Background(), database); err != nil {
		return Bundle{}, fmt.Errorf("domain wire: auto migrate: %w", err)
	}
	scopes, err := persistence.NewScopeFactory(database)
	if err != nil {
		return Bundle{}, err
	}
	service, err := application.NewService(scopes)
	if err != nil {
		return Bundle{}, err
	}
	return Bundle{Service: service}, nil
}
func (bundle Bundle) RegisterREST(mux *http.ServeMux) { rest.Register(mux, bundle.Service) }
func (bundle Bundle) RegisterGRPC(registrar grpc.ServiceRegistrar) {
	rpc.Register(registrar, bundle.Service)
}
