// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/iam/domain"
	"gorm.io/gorm"
	"time"
)

type RolePermissionPOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type RolePermissionPORecord struct {
	RolePermissionPO     `gorm:"embedded"`
	RolePermissionPOBase `gorm:"embedded"`
}

func (RolePermissionPORecord) TableName() string { return "biz_iam_role_permission" }
func (record RolePermissionPORecord) Domain() domain.RolePermission {
	return domain.RolePermission{ID: record.ID, DataScope: record.RolePermissionPO.DataScope, Permission: record.RolePermissionPO.Permission, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func rolePermissionRecordFromDomain(value domain.RolePermission) RolePermissionPORecord {
	record := RolePermissionPORecord{}
	record.ID = value.ID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	record.RolePermissionPO.DataScope = value.DataScope
	record.RolePermissionPO.Permission = value.Permission
	return record
}
