// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/iam/domain"
	"gorm.io/gorm"
	"time"
)

type RolePOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type RolePORecord struct {
	RolePO     `gorm:"embedded"`
	RolePOBase `gorm:"embedded"`
}

func (RolePORecord) TableName() string { return "biz_iam_role" }
func (record RolePORecord) Domain() domain.Role {
	return domain.Role{ID: record.ID, Name: record.RolePO.Name, Status: record.RolePO.Status, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func roleRecordFromDomain(value domain.Role) RolePORecord {
	record := RolePORecord{}
	record.ID = value.ID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	record.RolePO.Name = value.Name
	record.RolePO.Status = value.Status
	return record
}
