// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/iam/domain"
	"gorm.io/gorm"
	"time"
)

type TenantPOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type TenantPORecord struct {
	TenantPO     `gorm:"embedded"`
	TenantPOBase `gorm:"embedded"`
}

func (TenantPORecord) TableName() string { return "biz_iam_tenant" }
func (record TenantPORecord) Domain() domain.Tenant {
	return domain.Tenant{ID: record.ID, Name: record.TenantPO.Name, Status: record.TenantPO.Status, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func tenantRecordFromDomain(value domain.Tenant) TenantPORecord {
	record := TenantPORecord{}
	record.ID = value.ID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	record.TenantPO.Name = value.Name
	record.TenantPO.Status = value.Status
	return record
}
