// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/iam/domain"
	"gorm.io/gorm"
	"time"
)

type MemberSitePOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type MemberSitePORecord struct {
	MemberSitePO     `gorm:"embedded"`
	MemberSitePOBase `gorm:"embedded"`
}

func (MemberSitePORecord) TableName() string { return "biz_iam_member_site" }
func (record MemberSitePORecord) Domain() domain.MemberSite {
	return domain.MemberSite{ID: record.ID, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func memberSiteRecordFromDomain(value domain.MemberSite) MemberSitePORecord {
	record := MemberSitePORecord{}
	record.ID = value.ID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	return record
}
