// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/iam/domain"
	"gorm.io/gorm"
	"time"
)

type MembershipPOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type MembershipPORecord struct {
	MembershipPO     `gorm:"embedded"`
	MembershipPOBase `gorm:"embedded"`
}

func (MembershipPORecord) TableName() string { return "biz_iam_membership" }
func (record MembershipPORecord) Domain() domain.Membership {
	return domain.Membership{ID: record.ID, Status: record.MembershipPO.Status, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func membershipRecordFromDomain(value domain.Membership) MembershipPORecord {
	record := MembershipPORecord{}
	record.ID = value.ID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	record.MembershipPO.Status = value.Status
	return record
}
