// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/iam/domain"
	"gorm.io/gorm"
	"time"
)

type MemberRolePOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type MemberRolePORecord struct {
	MemberRolePO     `gorm:"embedded"`
	MemberRolePOBase `gorm:"embedded"`
}

func (MemberRolePORecord) TableName() string { return "biz_iam_member_role" }
func (record MemberRolePORecord) Domain() domain.MemberRole {
	return domain.MemberRole{ID: record.ID, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func memberRoleRecordFromDomain(value domain.MemberRole) MemberRolePORecord {
	record := MemberRolePORecord{}
	record.ID = value.ID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	return record
}
