// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/iam/domain"
	"gorm.io/gorm"
	"time"
)

type APITokenPOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type APITokenPORecord struct {
	APITokenPO     `gorm:"embedded"`
	APITokenPOBase `gorm:"embedded"`
}

func (APITokenPORecord) TableName() string { return "biz_iam_api_token" }
func (record APITokenPORecord) Domain() domain.APIToken {
	return domain.APIToken{ID: record.ID, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func aPITokenRecordFromDomain(value domain.APIToken) APITokenPORecord {
	record := APITokenPORecord{}
	record.ID = value.ID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	return record
}
