// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	"context"
	"errors"
	domain "github.com/hvritual/biz/internal/iam/domain"
	ports "github.com/hvritual/biz/internal/iam/ports"
	"gorm.io/gorm"
	"time"
	"yunka.io/framework/requestscope"
)

func AutoMigrate(ctx context.Context, database *gorm.DB) error {
	if database == nil {
		return errors.New("domain persistence: database is required")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	return database.WithContext(ctx).AutoMigrate(&APITokenPORecord{}, &MemberRolePORecord{}, &MemberSitePORecord{}, &MembershipPORecord{}, &RolePORecord{}, &RolePermissionPORecord{}, &TenantPORecord{}, &UserPORecord{})
}

type APITokenRepository struct{ database *gorm.DB }

func (repository *APITokenRepository) scoped(ctx context.Context) (*gorm.DB, error) {
	query := repository.database.WithContext(ctx)
	return query, nil
}
func (repository *APITokenRepository) Create(ctx context.Context, value *domain.APIToken) error {
	if value == nil {
		return errors.New("domain persistence: value is required")
	}
	if value.Version == 0 {
		value.Version = 1
	}
	now := time.Now().UTC()
	if value.CreatedAt.IsZero() {
		value.CreatedAt = now
	}
	value.UpdatedAt = now
	record := aPITokenRecordFromDomain(*value)
	if err := repository.database.WithContext(ctx).Create(&record).Error; err != nil {
		return err
	}
	*value = record.Domain()
	return nil
}
func (repository *APITokenRepository) Get(ctx context.Context, id string) (domain.APIToken, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return domain.APIToken{}, err
	}
	var record APITokenPORecord
	if err := query.Where("id = ?", id).First(&record).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return domain.APIToken{}, ports.ErrNotFound
		}
		return domain.APIToken{}, err
	}
	return record.Domain(), nil
}
func (repository *APITokenRepository) List(ctx context.Context, limit, offset int) ([]domain.APIToken, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return nil, err
	}
	var rows []APITokenPORecord
	if limit > 0 {
		query = query.Limit(limit)
	}
	if offset > 0 {
		query = query.Offset(offset)
	}
	if err := query.Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	result := make([]domain.APIToken, 0, len(rows))
	for _, row := range rows {
		result = append(result, row.Domain())
	}
	return result, nil
}
func (repository *APITokenRepository) Update(ctx context.Context, value *domain.APIToken, expected uint64) error {
	if value == nil || value.ID == "" {
		return errors.New("domain persistence: update value/id is required")
	}
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	updates := map[string]any{"version": gorm.Expr("version + 1"), "updated_at": time.Now().UTC()}
	result := query.Model(&APITokenPORecord{}).Where("id = ? AND version = ?", value.ID, expected).Updates(updates)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func (repository *APITokenRepository) Delete(ctx context.Context, id string, expected uint64) error {
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	result := query.Where("id = ? AND version = ?", id, expected).Delete(&APITokenPORecord{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}

type MemberRoleRepository struct{ database *gorm.DB }

func (repository *MemberRoleRepository) scoped(ctx context.Context) (*gorm.DB, error) {
	query := repository.database.WithContext(ctx)
	return query, nil
}
func (repository *MemberRoleRepository) Create(ctx context.Context, value *domain.MemberRole) error {
	if value == nil {
		return errors.New("domain persistence: value is required")
	}
	if value.Version == 0 {
		value.Version = 1
	}
	now := time.Now().UTC()
	if value.CreatedAt.IsZero() {
		value.CreatedAt = now
	}
	value.UpdatedAt = now
	record := memberRoleRecordFromDomain(*value)
	if err := repository.database.WithContext(ctx).Create(&record).Error; err != nil {
		return err
	}
	*value = record.Domain()
	return nil
}
func (repository *MemberRoleRepository) Get(ctx context.Context, id string) (domain.MemberRole, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return domain.MemberRole{}, err
	}
	var record MemberRolePORecord
	if err := query.Where("id = ?", id).First(&record).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return domain.MemberRole{}, ports.ErrNotFound
		}
		return domain.MemberRole{}, err
	}
	return record.Domain(), nil
}
func (repository *MemberRoleRepository) List(ctx context.Context, limit, offset int) ([]domain.MemberRole, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return nil, err
	}
	var rows []MemberRolePORecord
	if limit > 0 {
		query = query.Limit(limit)
	}
	if offset > 0 {
		query = query.Offset(offset)
	}
	if err := query.Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	result := make([]domain.MemberRole, 0, len(rows))
	for _, row := range rows {
		result = append(result, row.Domain())
	}
	return result, nil
}
func (repository *MemberRoleRepository) Update(ctx context.Context, value *domain.MemberRole, expected uint64) error {
	if value == nil || value.ID == "" {
		return errors.New("domain persistence: update value/id is required")
	}
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	updates := map[string]any{"version": gorm.Expr("version + 1"), "updated_at": time.Now().UTC()}
	result := query.Model(&MemberRolePORecord{}).Where("id = ? AND version = ?", value.ID, expected).Updates(updates)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func (repository *MemberRoleRepository) Delete(ctx context.Context, id string, expected uint64) error {
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	result := query.Where("id = ? AND version = ?", id, expected).Delete(&MemberRolePORecord{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}

type MemberSiteRepository struct{ database *gorm.DB }

func (repository *MemberSiteRepository) scoped(ctx context.Context) (*gorm.DB, error) {
	query := repository.database.WithContext(ctx)
	return query, nil
}
func (repository *MemberSiteRepository) Create(ctx context.Context, value *domain.MemberSite) error {
	if value == nil {
		return errors.New("domain persistence: value is required")
	}
	if value.Version == 0 {
		value.Version = 1
	}
	now := time.Now().UTC()
	if value.CreatedAt.IsZero() {
		value.CreatedAt = now
	}
	value.UpdatedAt = now
	record := memberSiteRecordFromDomain(*value)
	if err := repository.database.WithContext(ctx).Create(&record).Error; err != nil {
		return err
	}
	*value = record.Domain()
	return nil
}
func (repository *MemberSiteRepository) Get(ctx context.Context, id string) (domain.MemberSite, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return domain.MemberSite{}, err
	}
	var record MemberSitePORecord
	if err := query.Where("id = ?", id).First(&record).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return domain.MemberSite{}, ports.ErrNotFound
		}
		return domain.MemberSite{}, err
	}
	return record.Domain(), nil
}
func (repository *MemberSiteRepository) List(ctx context.Context, limit, offset int) ([]domain.MemberSite, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return nil, err
	}
	var rows []MemberSitePORecord
	if limit > 0 {
		query = query.Limit(limit)
	}
	if offset > 0 {
		query = query.Offset(offset)
	}
	if err := query.Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	result := make([]domain.MemberSite, 0, len(rows))
	for _, row := range rows {
		result = append(result, row.Domain())
	}
	return result, nil
}
func (repository *MemberSiteRepository) Update(ctx context.Context, value *domain.MemberSite, expected uint64) error {
	if value == nil || value.ID == "" {
		return errors.New("domain persistence: update value/id is required")
	}
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	updates := map[string]any{"version": gorm.Expr("version + 1"), "updated_at": time.Now().UTC()}
	result := query.Model(&MemberSitePORecord{}).Where("id = ? AND version = ?", value.ID, expected).Updates(updates)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func (repository *MemberSiteRepository) Delete(ctx context.Context, id string, expected uint64) error {
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	result := query.Where("id = ? AND version = ?", id, expected).Delete(&MemberSitePORecord{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}

type MembershipRepository struct{ database *gorm.DB }

func (repository *MembershipRepository) scoped(ctx context.Context) (*gorm.DB, error) {
	query := repository.database.WithContext(ctx)
	return query, nil
}
func (repository *MembershipRepository) Create(ctx context.Context, value *domain.Membership) error {
	if value == nil {
		return errors.New("domain persistence: value is required")
	}
	if value.Version == 0 {
		value.Version = 1
	}
	now := time.Now().UTC()
	if value.CreatedAt.IsZero() {
		value.CreatedAt = now
	}
	value.UpdatedAt = now
	record := membershipRecordFromDomain(*value)
	if err := repository.database.WithContext(ctx).Create(&record).Error; err != nil {
		return err
	}
	*value = record.Domain()
	return nil
}
func (repository *MembershipRepository) Get(ctx context.Context, id string) (domain.Membership, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return domain.Membership{}, err
	}
	var record MembershipPORecord
	if err := query.Where("id = ?", id).First(&record).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return domain.Membership{}, ports.ErrNotFound
		}
		return domain.Membership{}, err
	}
	return record.Domain(), nil
}
func (repository *MembershipRepository) List(ctx context.Context, limit, offset int) ([]domain.Membership, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return nil, err
	}
	var rows []MembershipPORecord
	if limit > 0 {
		query = query.Limit(limit)
	}
	if offset > 0 {
		query = query.Offset(offset)
	}
	if err := query.Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	result := make([]domain.Membership, 0, len(rows))
	for _, row := range rows {
		result = append(result, row.Domain())
	}
	return result, nil
}
func (repository *MembershipRepository) Update(ctx context.Context, value *domain.Membership, expected uint64) error {
	if value == nil || value.ID == "" {
		return errors.New("domain persistence: update value/id is required")
	}
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	updates := map[string]any{"version": gorm.Expr("version + 1"), "updated_at": time.Now().UTC(), "status": value.Status}
	result := query.Model(&MembershipPORecord{}).Where("id = ? AND version = ?", value.ID, expected).Updates(updates)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func (repository *MembershipRepository) Delete(ctx context.Context, id string, expected uint64) error {
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	result := query.Where("id = ? AND version = ?", id, expected).Delete(&MembershipPORecord{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}

type RoleRepository struct{ database *gorm.DB }

func (repository *RoleRepository) scoped(ctx context.Context) (*gorm.DB, error) {
	query := repository.database.WithContext(ctx)
	return query, nil
}
func (repository *RoleRepository) Create(ctx context.Context, value *domain.Role) error {
	if value == nil {
		return errors.New("domain persistence: value is required")
	}
	if value.Version == 0 {
		value.Version = 1
	}
	now := time.Now().UTC()
	if value.CreatedAt.IsZero() {
		value.CreatedAt = now
	}
	value.UpdatedAt = now
	record := roleRecordFromDomain(*value)
	if err := repository.database.WithContext(ctx).Create(&record).Error; err != nil {
		return err
	}
	*value = record.Domain()
	return nil
}
func (repository *RoleRepository) Get(ctx context.Context, id string) (domain.Role, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return domain.Role{}, err
	}
	var record RolePORecord
	if err := query.Where("id = ?", id).First(&record).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return domain.Role{}, ports.ErrNotFound
		}
		return domain.Role{}, err
	}
	return record.Domain(), nil
}
func (repository *RoleRepository) List(ctx context.Context, limit, offset int) ([]domain.Role, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return nil, err
	}
	var rows []RolePORecord
	if limit > 0 {
		query = query.Limit(limit)
	}
	if offset > 0 {
		query = query.Offset(offset)
	}
	if err := query.Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	result := make([]domain.Role, 0, len(rows))
	for _, row := range rows {
		result = append(result, row.Domain())
	}
	return result, nil
}
func (repository *RoleRepository) Update(ctx context.Context, value *domain.Role, expected uint64) error {
	if value == nil || value.ID == "" {
		return errors.New("domain persistence: update value/id is required")
	}
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	updates := map[string]any{"version": gorm.Expr("version + 1"), "updated_at": time.Now().UTC(), "name": value.Name, "status": value.Status}
	result := query.Model(&RolePORecord{}).Where("id = ? AND version = ?", value.ID, expected).Updates(updates)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func (repository *RoleRepository) Delete(ctx context.Context, id string, expected uint64) error {
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	result := query.Where("id = ? AND version = ?", id, expected).Delete(&RolePORecord{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}

type RolePermissionRepository struct{ database *gorm.DB }

func (repository *RolePermissionRepository) scoped(ctx context.Context) (*gorm.DB, error) {
	query := repository.database.WithContext(ctx)
	return query, nil
}
func (repository *RolePermissionRepository) Create(ctx context.Context, value *domain.RolePermission) error {
	if value == nil {
		return errors.New("domain persistence: value is required")
	}
	if value.Version == 0 {
		value.Version = 1
	}
	now := time.Now().UTC()
	if value.CreatedAt.IsZero() {
		value.CreatedAt = now
	}
	value.UpdatedAt = now
	record := rolePermissionRecordFromDomain(*value)
	if err := repository.database.WithContext(ctx).Create(&record).Error; err != nil {
		return err
	}
	*value = record.Domain()
	return nil
}
func (repository *RolePermissionRepository) Get(ctx context.Context, id string) (domain.RolePermission, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return domain.RolePermission{}, err
	}
	var record RolePermissionPORecord
	if err := query.Where("id = ?", id).First(&record).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return domain.RolePermission{}, ports.ErrNotFound
		}
		return domain.RolePermission{}, err
	}
	return record.Domain(), nil
}
func (repository *RolePermissionRepository) List(ctx context.Context, limit, offset int) ([]domain.RolePermission, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return nil, err
	}
	var rows []RolePermissionPORecord
	if limit > 0 {
		query = query.Limit(limit)
	}
	if offset > 0 {
		query = query.Offset(offset)
	}
	if err := query.Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	result := make([]domain.RolePermission, 0, len(rows))
	for _, row := range rows {
		result = append(result, row.Domain())
	}
	return result, nil
}
func (repository *RolePermissionRepository) Update(ctx context.Context, value *domain.RolePermission, expected uint64) error {
	if value == nil || value.ID == "" {
		return errors.New("domain persistence: update value/id is required")
	}
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	updates := map[string]any{"version": gorm.Expr("version + 1"), "updated_at": time.Now().UTC(), "data_scope": value.DataScope, "permission": value.Permission}
	result := query.Model(&RolePermissionPORecord{}).Where("id = ? AND version = ?", value.ID, expected).Updates(updates)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func (repository *RolePermissionRepository) Delete(ctx context.Context, id string, expected uint64) error {
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	result := query.Where("id = ? AND version = ?", id, expected).Delete(&RolePermissionPORecord{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}

type TenantRepository struct{ database *gorm.DB }

func (repository *TenantRepository) scoped(ctx context.Context) (*gorm.DB, error) {
	query := repository.database.WithContext(ctx)
	return query, nil
}
func (repository *TenantRepository) Create(ctx context.Context, value *domain.Tenant) error {
	if value == nil {
		return errors.New("domain persistence: value is required")
	}
	if value.Version == 0 {
		value.Version = 1
	}
	now := time.Now().UTC()
	if value.CreatedAt.IsZero() {
		value.CreatedAt = now
	}
	value.UpdatedAt = now
	record := tenantRecordFromDomain(*value)
	if err := repository.database.WithContext(ctx).Create(&record).Error; err != nil {
		return err
	}
	*value = record.Domain()
	return nil
}
func (repository *TenantRepository) Get(ctx context.Context, id string) (domain.Tenant, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return domain.Tenant{}, err
	}
	var record TenantPORecord
	if err := query.Where("id = ?", id).First(&record).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return domain.Tenant{}, ports.ErrNotFound
		}
		return domain.Tenant{}, err
	}
	return record.Domain(), nil
}
func (repository *TenantRepository) List(ctx context.Context, limit, offset int) ([]domain.Tenant, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return nil, err
	}
	var rows []TenantPORecord
	if limit > 0 {
		query = query.Limit(limit)
	}
	if offset > 0 {
		query = query.Offset(offset)
	}
	if err := query.Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	result := make([]domain.Tenant, 0, len(rows))
	for _, row := range rows {
		result = append(result, row.Domain())
	}
	return result, nil
}
func (repository *TenantRepository) Update(ctx context.Context, value *domain.Tenant, expected uint64) error {
	if value == nil || value.ID == "" {
		return errors.New("domain persistence: update value/id is required")
	}
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	updates := map[string]any{"version": gorm.Expr("version + 1"), "updated_at": time.Now().UTC(), "name": value.Name, "status": value.Status}
	result := query.Model(&TenantPORecord{}).Where("id = ? AND version = ?", value.ID, expected).Updates(updates)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func (repository *TenantRepository) Delete(ctx context.Context, id string, expected uint64) error {
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	result := query.Where("id = ? AND version = ?", id, expected).Delete(&TenantPORecord{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}

type UserRepository struct{ database *gorm.DB }

func (repository *UserRepository) scoped(ctx context.Context) (*gorm.DB, error) {
	query := repository.database.WithContext(ctx)
	return query, nil
}
func (repository *UserRepository) Create(ctx context.Context, value *domain.User) error {
	if value == nil {
		return errors.New("domain persistence: value is required")
	}
	if value.Version == 0 {
		value.Version = 1
	}
	now := time.Now().UTC()
	if value.CreatedAt.IsZero() {
		value.CreatedAt = now
	}
	value.UpdatedAt = now
	record := userRecordFromDomain(*value)
	if err := repository.database.WithContext(ctx).Create(&record).Error; err != nil {
		return err
	}
	*value = record.Domain()
	return nil
}
func (repository *UserRepository) Get(ctx context.Context, id string) (domain.User, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return domain.User{}, err
	}
	var record UserPORecord
	if err := query.Where("id = ?", id).First(&record).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return domain.User{}, ports.ErrNotFound
		}
		return domain.User{}, err
	}
	return record.Domain(), nil
}
func (repository *UserRepository) List(ctx context.Context, limit, offset int) ([]domain.User, error) {
	query, err := repository.scoped(ctx)
	if err != nil {
		return nil, err
	}
	var rows []UserPORecord
	if limit > 0 {
		query = query.Limit(limit)
	}
	if offset > 0 {
		query = query.Offset(offset)
	}
	if err := query.Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	result := make([]domain.User, 0, len(rows))
	for _, row := range rows {
		result = append(result, row.Domain())
	}
	return result, nil
}
func (repository *UserRepository) Update(ctx context.Context, value *domain.User, expected uint64) error {
	if value == nil || value.ID == "" {
		return errors.New("domain persistence: update value/id is required")
	}
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	updates := map[string]any{"version": gorm.Expr("version + 1"), "updated_at": time.Now().UTC(), "email": value.Email, "status": value.Status}
	result := query.Model(&UserPORecord{}).Where("id = ? AND version = ?", value.ID, expected).Updates(updates)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func (repository *UserRepository) Delete(ctx context.Context, id string, expected uint64) error {
	query, err := repository.scoped(ctx)
	if err != nil {
		return err
	}
	result := query.Where("id = ? AND version = ?", id, expected).Delete(&UserPORecord{})
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected != 1 {
		return ports.ErrConflict
	}
	return nil
}
func NewScopeFactory(database *gorm.DB) (requestscope.ScopeFactory[ports.Repositories], error) {
	unit, err := requestscope.NewGORMFactory(database, nil)
	if err != nil {
		return nil, err
	}
	return requestscope.NewFactory(requestscope.FactoryOptions[ports.Repositories]{UnitOfWork: unit, Repositories: requestscope.GORMRepositories(func(ctx context.Context, transaction *gorm.DB) (ports.Repositories, error) {
		repositories := ports.Repositories{}
		repositories.APIToken = &APITokenRepository{database: transaction}
		repositories.MemberRole = &MemberRoleRepository{database: transaction}
		repositories.MemberSite = &MemberSiteRepository{database: transaction}
		repositories.Membership = &MembershipRepository{database: transaction}
		repositories.Role = &RoleRepository{database: transaction}
		repositories.RolePermission = &RolePermissionRepository{database: transaction}
		repositories.Tenant = &TenantRepository{database: transaction}
		repositories.User = &UserRepository{database: transaction}
		return repositories, nil
	})})
}
