// Code generated by yunka domain; DO NOT EDIT.

package persistence

import (
	domain "github.com/hvritual/biz/internal/iam/domain"
	"gorm.io/gorm"
	"time"
)

type UserPOBase struct {
	ID        string         `gorm:"column:id;type:varchar(64);primaryKey"`
	Version   uint64         `gorm:"column:version;type:bigint unsigned;not null;default:1"`
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);not null"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3);not null"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3);index"`
}
type UserPORecord struct {
	UserPO     `gorm:"embedded"`
	UserPOBase `gorm:"embedded"`
}

func (UserPORecord) TableName() string { return "biz_iam_user" }
func (record UserPORecord) Domain() domain.User {
	return domain.User{ID: record.ID, Email: record.UserPO.Email, Status: record.UserPO.Status, Version: record.Version, CreatedAt: record.CreatedAt, UpdatedAt: record.UpdatedAt}
}
func userRecordFromDomain(value domain.User) UserPORecord {
	record := UserPORecord{}
	record.ID = value.ID
	record.Version = value.Version
	record.CreatedAt = value.CreatedAt
	record.UpdatedAt = value.UpdatedAt
	record.UserPO.Email = value.Email
	record.UserPO.Status = value.Status
	return record
}
