// Code generated by protoc-gen-xr v0.1, DO NOT EDIT.
// source: base

package grpc

import (
	"errors"
	"fmt"
	"google.golang.org/grpc"
	"yunka.io/gateway/rpc/server"
	"yunka.io/pkg/invoke"
)

type IGrpcServer interface {
	GetGrpcServer() *grpc.Server
}

type _RegisterHandler func(s IGrpcServer, srv interface{}) error

type GrpcServer struct {
	grpcSrv   *grpc.Server
	handleMap map[string]_RegisterHandler
}

func (g *GrpcServer) GetGrpcServer() *grpc.Server {
	return g.grpcSrv
}

func (g *GrpcServer) RegisterServer(name string, srv interface{}) error {
	if srv == nil {
		return errors.New("interface is nil")
	}
	h, ok := g.handleMap[name]
	if !ok {
		return errors.New(fmt.Sprintf("%s handler has not register", name))
	}
	return h(g, srv)
}
func NewGrpcServer(grpcSrv *grpc.Server) invoke.RpcServer {
	return &GrpcServer{
		grpcSrv: grpcSrv,
		handleMap: map[string]_RegisterHandler{

			server.GatewayServiceName: _RegisterGatewayService,
		},
	}
}
