// Code generated by protoc-gen-xr v0.1, DO NOT EDIT.
// source: gateway.proto

/*
Package grpc is a generated rpc stub package.

It is generated from these files:
	api_common.proto
	common.proto
	gateway.proto
*/
package grpc

import (
	"errors"
	"yunka.io/gateway/rpc/meta"
)

func _RegisterGatewayService(s IGrpcServer, srv interface{}) error {
	if srv == nil {
		return errors.New("interface is nil")
	}
	meta.RegisterGatewayServiceServer(s.GetGrpcServer(), srv.(meta.GatewayServiceServer))
	return nil
}
