// Code generated by protoc-gen-xr v0.1, DO NOT EDIT.
// source: grpc_client

package grpc

import (
	"context"
	"errors"
	"google.golang.org/grpc"
	"strings"
	"sync"
	proto "github.com/golang/protobuf/proto"
	"yunka.io/pkg/invoke"
	"yunka.io/pkg/selector"
)

var (
	methodNameErr = errors.New("method not fill")
)

type GrpcClient struct {
	localClient   invoke.RpcClient
	rpcServerName sync.Map
	selector      selector.Selector
}

func NewGrpcClient(localClient invoke.RpcClient, localSrv []string, selector selector.Selector) *GrpcClient {
	c := &GrpcClient{
		localClient: localClient,
		selector:    selector,
	}

	for _, value := range localSrv {
		c.rpcServerName.Store(value, value)
	}
	return c
}

func (m *GrpcClient) newGrpcConn(ipPort string) (*grpc.ClientConn, error) {
	conn, err := grpc.Dial(ipPort, grpc.WithInsecure())
	if err != nil {
		return nil, err
	}
	return conn, nil
}

func (m *GrpcClient) Invoke(ctx context.Context, method string, args, reply proto.Message,
	param ...interface{}) error {

	i := strings.Index(method[1:], "/")
	if i <= 0 {
		return methodNameErr
	}
	servName := method[1 : i+1]
	_, ok := m.rpcServerName.Load(servName)
	if !ok {
		return m.localClient.Invoke(ctx, method, args, reply)
	}
	nxt, err := m.selector.Select(servName)
	if err != nil {
		return err
	}
	node, err := nxt()
	if err != nil {
		return err
	}

	return m.InvokeNode(ctx, node.Address, method, args, reply)
}

func (m *GrpcClient) InvokeNode(ctx context.Context, nodeId, method string, args, reply proto.Message,
	param ...interface{}) error {
	conn, err := m.newGrpcConn(nodeId)
	if err != nil {
		return err
	}
	defer conn.Close()
	return conn.Invoke(ctx, method, args, reply)
}
