// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api_common.proto

package meta

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// @Description: TODO
// @date 2019-07-16
// @version V1.0
type CallType int32

const (
	CallType_CallReserve CallType = 0
	CallType_HttpCall    CallType = 1
	CallType_RpcCall     CallType = 2
)

var CallType_name = map[int32]string{
	0: "CallReserve",
	1: "HttpCall",
	2: "RpcCall",
}

var CallType_value = map[string]int32{
	"CallReserve": 0,
	"HttpCall":    1,
	"RpcCall":     2,
}

func (x CallType) String() string {
	return proto.EnumName(CallType_name, int32(x))
}

func (CallType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a7981141f1b47ff, []int{0}
}

// auth byte : ---- api req_district check_role check_token
// 判断 auth是否为0 即可判断API是否需要权限
type AuthBit int32

const (
	AuthBit_AuthNot       AuthBit = 0
	AuthBit_AuthToken     AuthBit = 2
	AuthBit_AuthRole      AuthBit = 4
	AuthBit_AuthTimeLimit AuthBit = 8
	AuthBit_AuthApi       AuthBit = 16
)

var AuthBit_name = map[int32]string{
	0:  "AuthNot",
	2:  "AuthToken",
	4:  "AuthRole",
	8:  "AuthTimeLimit",
	16: "AuthApi",
}

var AuthBit_value = map[string]int32{
	"AuthNot":       0,
	"AuthToken":     2,
	"AuthRole":      4,
	"AuthTimeLimit": 8,
	"AuthApi":       16,
}

func (x AuthBit) String() string {
	return proto.EnumName(AuthBit_name, int32(x))
}

func (AuthBit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a7981141f1b47ff, []int{1}
}

// 网关运行时所需要的api
type RuntimeApi struct {
	Uuid                 string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SrvName              string        `protobuf:"bytes,2,opt,name=srvName,proto3" json:"srvName,omitempty"`
	ModuleName           string        `protobuf:"bytes,3,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	Uri                  string        `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Name                 string        `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	CallType             CallType      `protobuf:"varint,6,opt,name=callType,proto3,enum=io.yunka.gateway.rpc.CallType" json:"callType,omitempty"`
	Auth                 AuthBit       `protobuf:"varint,7,opt,name=auth,proto3,enum=io.yunka.gateway.rpc.AuthBit" json:"auth,omitempty"`
	SrvApi               string        `protobuf:"bytes,8,opt,name=srvApi,proto3" json:"srvApi,omitempty"`
	IsRedirect           bool          `protobuf:"varint,9,opt,name=isRedirect,proto3" json:"isRedirect,omitempty"`
	Composes             []*RuntimeApi `protobuf:"bytes,10,rep,name=composes,proto3" json:"composes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RuntimeApi) Reset()         { *m = RuntimeApi{} }
func (m *RuntimeApi) String() string { return proto.CompactTextString(m) }
func (*RuntimeApi) ProtoMessage()    {}
func (*RuntimeApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a7981141f1b47ff, []int{0}
}

func (m *RuntimeApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeApi.Unmarshal(m, b)
}
func (m *RuntimeApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeApi.Marshal(b, m, deterministic)
}
func (m *RuntimeApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeApi.Merge(m, src)
}
func (m *RuntimeApi) XXX_Size() int {
	return xxx_messageInfo_RuntimeApi.Size(m)
}
func (m *RuntimeApi) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeApi.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeApi proto.InternalMessageInfo

func (m *RuntimeApi) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RuntimeApi) GetSrvName() string {
	if m != nil {
		return m.SrvName
	}
	return ""
}

func (m *RuntimeApi) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *RuntimeApi) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *RuntimeApi) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RuntimeApi) GetCallType() CallType {
	if m != nil {
		return m.CallType
	}
	return CallType_CallReserve
}

func (m *RuntimeApi) GetAuth() AuthBit {
	if m != nil {
		return m.Auth
	}
	return AuthBit_AuthNot
}

func (m *RuntimeApi) GetSrvApi() string {
	if m != nil {
		return m.SrvApi
	}
	return ""
}

func (m *RuntimeApi) GetIsRedirect() bool {
	if m != nil {
		return m.IsRedirect
	}
	return false
}

func (m *RuntimeApi) GetComposes() []*RuntimeApi {
	if m != nil {
		return m.Composes
	}
	return nil
}

type CircuitCfg struct {
	CloseTime            int32    `protobuf:"varint,1,opt,name=CloseTime,proto3" json:"CloseTime,omitempty"`
	CheckPeriod          int32    `protobuf:"varint,2,opt,name=CheckPeriod,proto3" json:"CheckPeriod,omitempty"`
	LimitPercent         int32    `protobuf:"varint,3,opt,name=LimitPercent,proto3" json:"LimitPercent,omitempty"`
	HalfOpen             int32    `protobuf:"varint,4,opt,name=HalfOpen,proto3" json:"HalfOpen,omitempty"`
	HalfClose            int32    `protobuf:"varint,5,opt,name=HalfClose,proto3" json:"HalfClose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CircuitCfg) Reset()         { *m = CircuitCfg{} }
func (m *CircuitCfg) String() string { return proto.CompactTextString(m) }
func (*CircuitCfg) ProtoMessage()    {}
func (*CircuitCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a7981141f1b47ff, []int{1}
}

func (m *CircuitCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CircuitCfg.Unmarshal(m, b)
}
func (m *CircuitCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CircuitCfg.Marshal(b, m, deterministic)
}
func (m *CircuitCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CircuitCfg.Merge(m, src)
}
func (m *CircuitCfg) XXX_Size() int {
	return xxx_messageInfo_CircuitCfg.Size(m)
}
func (m *CircuitCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_CircuitCfg.DiscardUnknown(m)
}

var xxx_messageInfo_CircuitCfg proto.InternalMessageInfo

func (m *CircuitCfg) GetCloseTime() int32 {
	if m != nil {
		return m.CloseTime
	}
	return 0
}

func (m *CircuitCfg) GetCheckPeriod() int32 {
	if m != nil {
		return m.CheckPeriod
	}
	return 0
}

func (m *CircuitCfg) GetLimitPercent() int32 {
	if m != nil {
		return m.LimitPercent
	}
	return 0
}

func (m *CircuitCfg) GetHalfOpen() int32 {
	if m != nil {
		return m.HalfOpen
	}
	return 0
}

func (m *CircuitCfg) GetHalfClose() int32 {
	if m != nil {
		return m.HalfClose
	}
	return 0
}

type ServerNode struct {
	IpPort               string      `protobuf:"bytes,1,opt,name=ipPort,proto3" json:"ipPort,omitempty"`
	Uuid                 string      `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Qps                  int32       `protobuf:"varint,3,opt,name=qps,proto3" json:"qps,omitempty"`
	SrvName              string      `protobuf:"bytes,4,opt,name=srvName,proto3" json:"srvName,omitempty"`
	Circuit              *CircuitCfg `protobuf:"bytes,5,opt,name=Circuit,proto3" json:"Circuit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerNode) Reset()         { *m = ServerNode{} }
func (m *ServerNode) String() string { return proto.CompactTextString(m) }
func (*ServerNode) ProtoMessage()    {}
func (*ServerNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a7981141f1b47ff, []int{2}
}

func (m *ServerNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerNode.Unmarshal(m, b)
}
func (m *ServerNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerNode.Marshal(b, m, deterministic)
}
func (m *ServerNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerNode.Merge(m, src)
}
func (m *ServerNode) XXX_Size() int {
	return xxx_messageInfo_ServerNode.Size(m)
}
func (m *ServerNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerNode.DiscardUnknown(m)
}

var xxx_messageInfo_ServerNode proto.InternalMessageInfo

func (m *ServerNode) GetIpPort() string {
	if m != nil {
		return m.IpPort
	}
	return ""
}

func (m *ServerNode) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ServerNode) GetQps() int32 {
	if m != nil {
		return m.Qps
	}
	return 0
}

func (m *ServerNode) GetSrvName() string {
	if m != nil {
		return m.SrvName
	}
	return ""
}

func (m *ServerNode) GetCircuit() *CircuitCfg {
	if m != nil {
		return m.Circuit
	}
	return nil
}

func init() {
	proto.RegisterEnum("io.yunka.gateway.rpc.CallType", CallType_name, CallType_value)
	proto.RegisterEnum("io.yunka.gateway.rpc.AuthBit", AuthBit_name, AuthBit_value)
	proto.RegisterType((*RuntimeApi)(nil), "io.yunka.gateway.rpc.RuntimeApi")
	proto.RegisterType((*CircuitCfg)(nil), "io.yunka.gateway.rpc.CircuitCfg")
	proto.RegisterType((*ServerNode)(nil), "io.yunka.gateway.rpc.ServerNode")
}

func init() {
	proto.RegisterFile("api_common.proto", fileDescriptor_2a7981141f1b47ff)
}

var fileDescriptor_2a7981141f1b47ff = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x5e, 0xda, 0xa4, 0x49, 0x5f, 0x37, 0x30, 0x16, 0x42, 0x11, 0x82, 0x29, 0xea, 0xa9, 0xda,
	0x21, 0x12, 0x43, 0xe2, 0x30, 0x71, 0xe9, 0x72, 0xd9, 0x01, 0x95, 0xca, 0xeb, 0x89, 0x0b, 0x0a,
	0xc9, 0xdb, 0x6a, 0x35, 0x8e, 0x8d, 0xe3, 0x14, 0xf5, 0xdf, 0x70, 0xe6, 0x7f, 0xf1, 0x3f, 0x90,
	0x4d, 0xda, 0x66, 0x52, 0x77, 0xfb, 0xbe, 0xef, 0xbd, 0x67, 0xbf, 0x7c, 0xfe, 0x02, 0x24, 0x57,
	0xfc, 0x7b, 0x21, 0x85, 0x90, 0x75, 0xaa, 0xb4, 0x34, 0x92, 0xbe, 0xe6, 0x32, 0xdd, 0xb5, 0xf5,
	0x26, 0x4f, 0x1f, 0x73, 0x83, 0xbf, 0xf2, 0x5d, 0xaa, 0x55, 0x31, 0xfd, 0x3b, 0x00, 0x60, 0x6d,
	0x6d, 0xb8, 0xc0, 0xb9, 0xe2, 0x94, 0x82, 0xdf, 0xb6, 0xbc, 0x8c, 0xbd, 0xc4, 0x9b, 0x8d, 0x99,
	0xc3, 0x34, 0x86, 0xb0, 0xd1, 0xdb, 0x45, 0x2e, 0x30, 0x1e, 0x38, 0x79, 0x4f, 0xe9, 0x25, 0x80,
	0x90, 0x65, 0x5b, 0xa1, 0x2b, 0x0e, 0x5d, 0xb1, 0xa7, 0x50, 0x02, 0xc3, 0x56, 0xf3, 0xd8, 0x77,
	0x05, 0x0b, 0xed, 0xf9, 0xb5, 0xed, 0x0d, 0xfe, 0x9f, 0x6f, 0x31, 0xbd, 0x81, 0xa8, 0xc8, 0xab,
	0x6a, 0xb5, 0x53, 0x18, 0x8f, 0x12, 0x6f, 0xf6, 0xe2, 0xfa, 0x32, 0x3d, 0xb5, 0x6b, 0x9a, 0x75,
	0x5d, 0xec, 0xd0, 0x4f, 0x3f, 0x80, 0x9f, 0xb7, 0x66, 0x1d, 0x87, 0x6e, 0xee, 0xfd, 0xe9, 0xb9,
	0x79, 0x6b, 0xd6, 0xb7, 0xdc, 0x30, 0xd7, 0x4a, 0xdf, 0xc0, 0xa8, 0xd1, 0xdb, 0xb9, 0xe2, 0x71,
	0xe4, 0x96, 0xe8, 0x98, 0xfd, 0x18, 0xde, 0x30, 0x2c, 0xb9, 0xc6, 0xc2, 0xc4, 0xe3, 0xc4, 0x9b,
	0x45, 0xac, 0xa7, 0xd0, 0xcf, 0x10, 0x15, 0x52, 0x28, 0xd9, 0x60, 0x13, 0x43, 0x32, 0x9c, 0x4d,
	0xae, 0x93, 0xd3, 0xd7, 0x1d, 0xed, 0x64, 0x87, 0x89, 0xe9, 0x1f, 0x0f, 0x20, 0xe3, 0xba, 0x68,
	0xb9, 0xc9, 0x1e, 0x1e, 0xe9, 0x3b, 0x18, 0x67, 0x95, 0x6c, 0x70, 0xc5, 0x05, 0x3a, 0xb3, 0x03,
	0x76, 0x14, 0x68, 0x02, 0x93, 0x6c, 0x8d, 0xc5, 0x66, 0x89, 0x9a, 0xcb, 0xd2, 0xb9, 0x1e, 0xb0,
	0xbe, 0x44, 0xa7, 0x70, 0xfe, 0x85, 0x0b, 0x6e, 0x96, 0xa8, 0x0b, 0xac, 0x8d, 0xf3, 0x3e, 0x60,
	0x4f, 0x34, 0xfa, 0x16, 0xa2, 0xbb, 0xbc, 0x7a, 0xf8, 0xaa, 0xb0, 0x76, 0x4f, 0x10, 0xb0, 0x03,
	0xb7, 0xf7, 0x5b, 0xec, 0xae, 0x74, 0x8f, 0x11, 0xb0, 0xa3, 0x30, 0xfd, 0xed, 0x01, 0xdc, 0xa3,
	0xde, 0xa2, 0x5e, 0xc8, 0x12, 0xad, 0x63, 0x5c, 0x2d, 0xa5, 0x36, 0x5d, 0x2c, 0x3a, 0x76, 0x08,
	0xcb, 0xa0, 0x17, 0x16, 0x02, 0xc3, 0x9f, 0xaa, 0xe9, 0xf6, 0xb1, 0xb0, 0x1f, 0x1f, 0xff, 0x69,
	0x7c, 0x6e, 0x20, 0xec, 0x2c, 0x71, 0x2b, 0x3c, 0x6b, 0xe8, 0xd1, 0x37, 0xb6, 0x1f, 0xb8, 0xfa,
	0x04, 0xd1, 0x3e, 0x0e, 0xf4, 0x25, 0x4c, 0x2c, 0x66, 0xd8, 0xd8, 0x9d, 0xc9, 0x19, 0x3d, 0x87,
	0xe8, 0xce, 0x18, 0x65, 0x45, 0xe2, 0xd1, 0x09, 0x84, 0x4c, 0x15, 0x8e, 0x0c, 0xae, 0xee, 0x21,
	0xec, 0xe2, 0x60, 0x75, 0x0b, 0x17, 0xd2, 0x90, 0x33, 0x7a, 0x01, 0x63, 0x4b, 0x56, 0x72, 0x83,
	0x35, 0x19, 0xd8, 0x13, 0x2c, 0x65, 0xb2, 0x42, 0xe2, 0xd3, 0x57, 0x70, 0xe1, 0x8a, 0x5c, 0xa0,
	0x73, 0x98, 0x44, 0xfb, 0xe1, 0xb9, 0xe2, 0x84, 0xdc, 0x8e, 0xbe, 0xf9, 0x02, 0x4d, 0xfe, 0x63,
	0xe4, 0xfe, 0xb4, 0x8f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xb3, 0x02, 0xfb, 0x7d, 0x03,
	0x00, 0x00,
}
