// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gateway/api_common.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallType int32

const (
	CallType_CallReserve CallType = 0
	CallType_HttpCall    CallType = 1
	CallType_RpcCall     CallType = 2
)

// Enum value maps for CallType.
var (
	CallType_name = map[int32]string{
		0: "CallReserve",
		1: "HttpCall",
		2: "RpcCall",
	}
	CallType_value = map[string]int32{
		"CallReserve": 0,
		"HttpCall":    1,
		"RpcCall":     2,
	}
)

func (x CallType) Enum() *CallType {
	p := new(CallType)
	*p = x
	return p
}

func (x CallType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallType) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_api_common_proto_enumTypes[0].Descriptor()
}

func (CallType) Type() protoreflect.EnumType {
	return &file_gateway_api_common_proto_enumTypes[0]
}

func (x CallType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallType.Descriptor instead.
func (CallType) EnumDescriptor() ([]byte, []int) {
	return file_gateway_api_common_proto_rawDescGZIP(), []int{0}
}

type AuthBit int32

const (
	AuthBit_AuthNot       AuthBit = 0
	AuthBit_AuthToken     AuthBit = 2
	AuthBit_AuthRole      AuthBit = 4
	AuthBit_AuthTimeLimit AuthBit = 8
	AuthBit_AuthApi       AuthBit = 16
)

// Enum value maps for AuthBit.
var (
	AuthBit_name = map[int32]string{
		0:  "AuthNot",
		2:  "AuthToken",
		4:  "AuthRole",
		8:  "AuthTimeLimit",
		16: "AuthApi",
	}
	AuthBit_value = map[string]int32{
		"AuthNot":       0,
		"AuthToken":     2,
		"AuthRole":      4,
		"AuthTimeLimit": 8,
		"AuthApi":       16,
	}
)

func (x AuthBit) Enum() *AuthBit {
	p := new(AuthBit)
	*p = x
	return p
}

func (x AuthBit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthBit) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_api_common_proto_enumTypes[1].Descriptor()
}

func (AuthBit) Type() protoreflect.EnumType {
	return &file_gateway_api_common_proto_enumTypes[1]
}

func (x AuthBit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthBit.Descriptor instead.
func (AuthBit) EnumDescriptor() ([]byte, []int) {
	return file_gateway_api_common_proto_rawDescGZIP(), []int{1}
}

type PermissionMode int32

const (
	PermissionMode_PermissionAll PermissionMode = 0
	PermissionMode_PermissionAny PermissionMode = 1
)

// Enum value maps for PermissionMode.
var (
	PermissionMode_name = map[int32]string{
		0: "PermissionAll",
		1: "PermissionAny",
	}
	PermissionMode_value = map[string]int32{
		"PermissionAll": 0,
		"PermissionAny": 1,
	}
)

func (x PermissionMode) Enum() *PermissionMode {
	p := new(PermissionMode)
	*p = x
	return p
}

func (x PermissionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_api_common_proto_enumTypes[2].Descriptor()
}

func (PermissionMode) Type() protoreflect.EnumType {
	return &file_gateway_api_common_proto_enumTypes[2]
}

func (x PermissionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionMode.Descriptor instead.
func (PermissionMode) EnumDescriptor() ([]byte, []int) {
	return file_gateway_api_common_proto_rawDescGZIP(), []int{2}
}

type RuntimeAuthorization struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    string                 `protobuf:"bytes,1,opt,name=operationId,proto3" json:"operationId,omitempty"`
	Permissions    []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Mode           PermissionMode         `protobuf:"varint,3,opt,name=mode,proto3,enum=io.yunka.gateway.rpc.PermissionMode" json:"mode,omitempty"`
	TenantRequired bool                   `protobuf:"varint,4,opt,name=tenantRequired,proto3" json:"tenantRequired,omitempty"`
	Authentication []string               `protobuf:"bytes,5,rep,name=authentication,proto3" json:"authentication,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeAuthorization) Reset() {
	*x = RuntimeAuthorization{}
	mi := &file_gateway_api_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeAuthorization) ProtoMessage() {}

func (x *RuntimeAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeAuthorization.ProtoReflect.Descriptor instead.
func (*RuntimeAuthorization) Descriptor() ([]byte, []int) {
	return file_gateway_api_common_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeAuthorization) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RuntimeAuthorization) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RuntimeAuthorization) GetMode() PermissionMode {
	if x != nil {
		return x.Mode
	}
	return PermissionMode_PermissionAll
}

func (x *RuntimeAuthorization) GetTenantRequired() bool {
	if x != nil {
		return x.TenantRequired
	}
	return false
}

func (x *RuntimeAuthorization) GetAuthentication() []string {
	if x != nil {
		return x.Authentication
	}
	return nil
}

type RuntimeApi struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SrvName       string                 `protobuf:"bytes,2,opt,name=srvName,proto3" json:"srvName,omitempty"`
	ModuleName    string                 `protobuf:"bytes,3,opt,name=moduleName,proto3" json:"moduleName,omitempty"`
	Uri           string                 `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	CallType      CallType               `protobuf:"varint,6,opt,name=callType,proto3,enum=io.yunka.gateway.rpc.CallType" json:"callType,omitempty"`
	Auth          AuthBit                `protobuf:"varint,7,opt,name=auth,proto3,enum=io.yunka.gateway.rpc.AuthBit" json:"auth,omitempty"`
	SrvApi        string                 `protobuf:"bytes,8,opt,name=srvApi,proto3" json:"srvApi,omitempty"`
	IsRedirect    bool                   `protobuf:"varint,9,opt,name=isRedirect,proto3" json:"isRedirect,omitempty"`
	Composes      []*RuntimeApi          `protobuf:"bytes,10,rep,name=composes,proto3" json:"composes,omitempty"`
	Authorization *RuntimeAuthorization  `protobuf:"bytes,11,opt,name=authorization,proto3" json:"authorization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeApi) Reset() {
	*x = RuntimeApi{}
	mi := &file_gateway_api_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeApi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeApi) ProtoMessage() {}

func (x *RuntimeApi) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeApi.ProtoReflect.Descriptor instead.
func (*RuntimeApi) Descriptor() ([]byte, []int) {
	return file_gateway_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeApi) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RuntimeApi) GetSrvName() string {
	if x != nil {
		return x.SrvName
	}
	return ""
}

func (x *RuntimeApi) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *RuntimeApi) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RuntimeApi) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeApi) GetCallType() CallType {
	if x != nil {
		return x.CallType
	}
	return CallType_CallReserve
}

func (x *RuntimeApi) GetAuth() AuthBit {
	if x != nil {
		return x.Auth
	}
	return AuthBit_AuthNot
}

func (x *RuntimeApi) GetSrvApi() string {
	if x != nil {
		return x.SrvApi
	}
	return ""
}

func (x *RuntimeApi) GetIsRedirect() bool {
	if x != nil {
		return x.IsRedirect
	}
	return false
}

func (x *RuntimeApi) GetComposes() []*RuntimeApi {
	if x != nil {
		return x.Composes
	}
	return nil
}

func (x *RuntimeApi) GetAuthorization() *RuntimeAuthorization {
	if x != nil {
		return x.Authorization
	}
	return nil
}

type CircuitCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloseTime     int32                  `protobuf:"varint,1,opt,name=CloseTime,proto3" json:"CloseTime,omitempty"`
	CheckPeriod   int32                  `protobuf:"varint,2,opt,name=CheckPeriod,proto3" json:"CheckPeriod,omitempty"`
	LimitPercent  int32                  `protobuf:"varint,3,opt,name=LimitPercent,proto3" json:"LimitPercent,omitempty"`
	HalfOpen      int32                  `protobuf:"varint,4,opt,name=HalfOpen,proto3" json:"HalfOpen,omitempty"`
	HalfClose     int32                  `protobuf:"varint,5,opt,name=HalfClose,proto3" json:"HalfClose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitCfg) Reset() {
	*x = CircuitCfg{}
	mi := &file_gateway_api_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitCfg) ProtoMessage() {}

func (x *CircuitCfg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitCfg.ProtoReflect.Descriptor instead.
func (*CircuitCfg) Descriptor() ([]byte, []int) {
	return file_gateway_api_common_proto_rawDescGZIP(), []int{2}
}

func (x *CircuitCfg) GetCloseTime() int32 {
	if x != nil {
		return x.CloseTime
	}
	return 0
}

func (x *CircuitCfg) GetCheckPeriod() int32 {
	if x != nil {
		return x.CheckPeriod
	}
	return 0
}

func (x *CircuitCfg) GetLimitPercent() int32 {
	if x != nil {
		return x.LimitPercent
	}
	return 0
}

func (x *CircuitCfg) GetHalfOpen() int32 {
	if x != nil {
		return x.HalfOpen
	}
	return 0
}

func (x *CircuitCfg) GetHalfClose() int32 {
	if x != nil {
		return x.HalfClose
	}
	return 0
}

type ServerNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpPort        string                 `protobuf:"bytes,1,opt,name=ipPort,proto3" json:"ipPort,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Qps           int32                  `protobuf:"varint,3,opt,name=qps,proto3" json:"qps,omitempty"`
	SrvName       string                 `protobuf:"bytes,4,opt,name=srvName,proto3" json:"srvName,omitempty"`
	Circuit       *CircuitCfg            `protobuf:"bytes,5,opt,name=Circuit,proto3" json:"Circuit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerNode) Reset() {
	*x = ServerNode{}
	mi := &file_gateway_api_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerNode) ProtoMessage() {}

func (x *ServerNode) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_api_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerNode.ProtoReflect.Descriptor instead.
func (*ServerNode) Descriptor() ([]byte, []int) {
	return file_gateway_api_common_proto_rawDescGZIP(), []int{3}
}

func (x *ServerNode) GetIpPort() string {
	if x != nil {
		return x.IpPort
	}
	return ""
}

func (x *ServerNode) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ServerNode) GetQps() int32 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *ServerNode) GetSrvName() string {
	if x != nil {
		return x.SrvName
	}
	return ""
}

func (x *ServerNode) GetCircuit() *CircuitCfg {
	if x != nil {
		return x.Circuit
	}
	return nil
}

var File_gateway_api_common_proto protoreflect.FileDescriptor

const file_gateway_api_common_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/api_common.proto\x12\x14io.yunka.gateway.rpc\"\xe4\x01\n" +
	"\x14RuntimeAuthorization\x12 \n" +
	"\voperationId\x18\x01 \x01(\tR\voperationId\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x128\n" +
	"\x04mode\x18\x03 \x01(\x0e2$.io.yunka.gateway.rpc.PermissionModeR\x04mode\x12&\n" +
	"\x0etenantRequired\x18\x04 \x01(\bR\x0etenantRequired\x12&\n" +
	"\x0eauthentication\x18\x05 \x03(\tR\x0eauthentication\"\xb7\x03\n" +
	"\n" +
	"RuntimeApi\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\asrvName\x18\x02 \x01(\tR\asrvName\x12\x1e\n" +
	"\n" +
	"moduleName\x18\x03 \x01(\tR\n" +
	"moduleName\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12:\n" +
	"\bcallType\x18\x06 \x01(\x0e2\x1e.io.yunka.gateway.rpc.CallTypeR\bcallType\x121\n" +
	"\x04auth\x18\a \x01(\x0e2\x1d.io.yunka.gateway.rpc.AuthBitR\x04auth\x12\x16\n" +
	"\x06srvApi\x18\b \x01(\tR\x06srvApi\x12\x1e\n" +
	"\n" +
	"isRedirect\x18\t \x01(\bR\n" +
	"isRedirect\x12<\n" +
	"\bcomposes\x18\n" +
	" \x03(\v2 .io.yunka.gateway.rpc.RuntimeApiR\bcomposes\x12P\n" +
	"\rauthorization\x18\v \x01(\v2*.io.yunka.gateway.rpc.RuntimeAuthorizationR\rauthorization\"\xaa\x01\n" +
	"\n" +
	"CircuitCfg\x12\x1c\n" +
	"\tCloseTime\x18\x01 \x01(\x05R\tCloseTime\x12 \n" +
	"\vCheckPeriod\x18\x02 \x01(\x05R\vCheckPeriod\x12\"\n" +
	"\fLimitPercent\x18\x03 \x01(\x05R\fLimitPercent\x12\x1a\n" +
	"\bHalfOpen\x18\x04 \x01(\x05R\bHalfOpen\x12\x1c\n" +
	"\tHalfClose\x18\x05 \x01(\x05R\tHalfClose\"\xa0\x01\n" +
	"\n" +
	"ServerNode\x12\x16\n" +
	"\x06ipPort\x18\x01 \x01(\tR\x06ipPort\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03qps\x18\x03 \x01(\x05R\x03qps\x12\x18\n" +
	"\asrvName\x18\x04 \x01(\tR\asrvName\x12:\n" +
	"\aCircuit\x18\x05 \x01(\v2 .io.yunka.gateway.rpc.CircuitCfgR\aCircuit*6\n" +
	"\bCallType\x12\x0f\n" +
	"\vCallReserve\x10\x00\x12\f\n" +
	"\bHttpCall\x10\x01\x12\v\n" +
	"\aRpcCall\x10\x02*S\n" +
	"\aAuthBit\x12\v\n" +
	"\aAuthNot\x10\x00\x12\r\n" +
	"\tAuthToken\x10\x02\x12\f\n" +
	"\bAuthRole\x10\x04\x12\x11\n" +
	"\rAuthTimeLimit\x10\b\x12\v\n" +
	"\aAuthApi\x10\x10*6\n" +
	"\x0ePermissionMode\x12\x11\n" +
	"\rPermissionAll\x10\x00\x12\x11\n" +
	"\rPermissionAny\x10\x01B Z\x1eyunka.io/gateway/rpc/meta;metab\x06proto3"

var (
	file_gateway_api_common_proto_rawDescOnce sync.Once
	file_gateway_api_common_proto_rawDescData []byte
)

func file_gateway_api_common_proto_rawDescGZIP() []byte {
	file_gateway_api_common_proto_rawDescOnce.Do(func() {
		file_gateway_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_api_common_proto_rawDesc), len(file_gateway_api_common_proto_rawDesc)))
	})
	return file_gateway_api_common_proto_rawDescData
}

var file_gateway_api_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gateway_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateway_api_common_proto_goTypes = []any{
	(CallType)(0),                // 0: io.yunka.gateway.rpc.CallType
	(AuthBit)(0),                 // 1: io.yunka.gateway.rpc.AuthBit
	(PermissionMode)(0),          // 2: io.yunka.gateway.rpc.PermissionMode
	(*RuntimeAuthorization)(nil), // 3: io.yunka.gateway.rpc.RuntimeAuthorization
	(*RuntimeApi)(nil),           // 4: io.yunka.gateway.rpc.RuntimeApi
	(*CircuitCfg)(nil),           // 5: io.yunka.gateway.rpc.CircuitCfg
	(*ServerNode)(nil),           // 6: io.yunka.gateway.rpc.ServerNode
}
var file_gateway_api_common_proto_depIdxs = []int32{
	2, // 0: io.yunka.gateway.rpc.RuntimeAuthorization.mode:type_name -> io.yunka.gateway.rpc.PermissionMode
	0, // 1: io.yunka.gateway.rpc.RuntimeApi.callType:type_name -> io.yunka.gateway.rpc.CallType
	1, // 2: io.yunka.gateway.rpc.RuntimeApi.auth:type_name -> io.yunka.gateway.rpc.AuthBit
	4, // 3: io.yunka.gateway.rpc.RuntimeApi.composes:type_name -> io.yunka.gateway.rpc.RuntimeApi
	3, // 4: io.yunka.gateway.rpc.RuntimeApi.authorization:type_name -> io.yunka.gateway.rpc.RuntimeAuthorization
	5, // 5: io.yunka.gateway.rpc.ServerNode.Circuit:type_name -> io.yunka.gateway.rpc.CircuitCfg
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_gateway_api_common_proto_init() }
func file_gateway_api_common_proto_init() {
	if File_gateway_api_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_api_common_proto_rawDesc), len(file_gateway_api_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_api_common_proto_goTypes,
		DependencyIndexes: file_gateway_api_common_proto_depIdxs,
		EnumInfos:         file_gateway_api_common_proto_enumTypes,
		MessageInfos:      file_gateway_api_common_proto_msgTypes,
	}.Build()
	File_gateway_api_common_proto = out.File
	file_gateway_api_common_proto_goTypes = nil
	file_gateway_api_common_proto_depIdxs = nil
}
