// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package meta

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseCode int32

const (
	ResponseCode_Not      ResponseCode = 0
	ResponseCode_Response ResponseCode = 1
)

var ResponseCode_name = map[int32]string{
	0: "Not",
	1: "Response",
}

var ResponseCode_value = map[string]int32{
	"Not":      0,
	"Response": 1,
}

func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}

func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type NotParamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotParamRequest) Reset()         { *m = NotParamRequest{} }
func (m *NotParamRequest) String() string { return proto.CompactTextString(m) }
func (*NotParamRequest) ProtoMessage()    {}
func (*NotParamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *NotParamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotParamRequest.Unmarshal(m, b)
}
func (m *NotParamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotParamRequest.Marshal(b, m, deterministic)
}
func (m *NotParamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotParamRequest.Merge(m, src)
}
func (m *NotParamRequest) XXX_Size() int {
	return xxx_messageInfo_NotParamRequest.Size(m)
}
func (m *NotParamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotParamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotParamRequest proto.InternalMessageInfo

type NotResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=io.yunka.gateway.rpc.ResponseCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NotResponse) Reset()         { *m = NotResponse{} }
func (m *NotResponse) String() string { return proto.CompactTextString(m) }
func (*NotResponse) ProtoMessage()    {}
func (*NotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *NotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotResponse.Unmarshal(m, b)
}
func (m *NotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotResponse.Marshal(b, m, deterministic)
}
func (m *NotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotResponse.Merge(m, src)
}
func (m *NotResponse) XXX_Size() int {
	return xxx_messageInfo_NotResponse.Size(m)
}
func (m *NotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotResponse proto.InternalMessageInfo

func (m *NotResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Not
}

func init() {
	proto.RegisterEnum("io.yunka.gateway.rpc.ResponseCode", ResponseCode_name, ResponseCode_value)
	proto.RegisterType((*NotParamRequest)(nil), "io.yunka.gateway.rpc.NotParamRequest")
	proto.RegisterType((*NotResponse)(nil), "io.yunka.gateway.rpc.NotResponse")
}

func init() {
	proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206)
}

var fileDescriptor_555bd8c177793206 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc9, 0xcc, 0xd7, 0xab, 0x2c, 0xcd,
	0xcb, 0x4e, 0xd4, 0x4b, 0x4f, 0x2c, 0x49, 0x2d, 0x4f, 0xac, 0xd4, 0x2b, 0x2a, 0x48, 0x56, 0x12,
	0xe4, 0xe2, 0xf7, 0xcb, 0x2f, 0x09, 0x48, 0x2c, 0x4a, 0xcc, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x51, 0x72, 0xe5, 0xe2, 0xf6, 0xcb, 0x2f, 0x09, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e,
	0x15, 0x32, 0xe3, 0x62, 0x49, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x52,
	0xd2, 0xc3, 0x66, 0x8c, 0x1e, 0x4c, 0xb5, 0x73, 0x7e, 0x4a, 0x6a, 0x10, 0x58, 0xbd, 0x96, 0x2a,
	0x17, 0x0f, 0xb2, 0xa8, 0x10, 0x3b, 0x17, 0xb3, 0x5f, 0x7e, 0x89, 0x00, 0x83, 0x10, 0x0f, 0x17,
	0x07, 0x4c, 0x42, 0x80, 0x31, 0x89, 0x0d, 0xec, 0x3a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x02, 0xcd, 0x79, 0xcc, 0xad, 0x00, 0x00, 0x00,
}
