// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gateway/gateway.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperateRuntimeApiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ResponseCode           `protobuf:"varint,1,opt,name=code,proto3,enum=io.yunka.gateway.rpc.ResponseCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateRuntimeApiResponse) Reset() {
	*x = OperateRuntimeApiResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateRuntimeApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateRuntimeApiResponse) ProtoMessage() {}

func (x *OperateRuntimeApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateRuntimeApiResponse.ProtoReflect.Descriptor instead.
func (*OperateRuntimeApiResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *OperateRuntimeApiResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_Not
}

func (x *OperateRuntimeApiResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteRuntimeApiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuntimeApiRequest) Reset() {
	*x = DeleteRuntimeApiRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuntimeApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuntimeApiRequest) ProtoMessage() {}

func (x *DeleteRuntimeApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuntimeApiRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuntimeApiRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRuntimeApiRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DeleteRuntimeApiRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type OperateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ResponseCode           `protobuf:"varint,1,opt,name=code,proto3,enum=io.yunka.gateway.rpc.ResponseCode" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateRoleResponse) Reset() {
	*x = OperateRoleResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateRoleResponse) ProtoMessage() {}

func (x *OperateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateRoleResponse.ProtoReflect.Descriptor instead.
func (*OperateRoleResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *OperateRoleResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_Not
}

func (x *OperateRoleResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RoleModuleBtn struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrgUUID             string                 `protobuf:"bytes,1,opt,name=orgUUID,proto3" json:"orgUUID,omitempty"`
	RoleUUID            string                 `protobuf:"bytes,2,opt,name=roleUUID,proto3" json:"roleUUID,omitempty"`
	ModuleBtnUUID       []string               `protobuf:"bytes,3,rep,name=moduleBtnUUID,proto3" json:"moduleBtnUUID,omitempty"`
	DeleteModuleBtnUUID []string               `protobuf:"bytes,4,rep,name=deleteModuleBtnUUID,proto3" json:"deleteModuleBtnUUID,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RoleModuleBtn) Reset() {
	*x = RoleModuleBtn{}
	mi := &file_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleModuleBtn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleModuleBtn) ProtoMessage() {}

func (x *RoleModuleBtn) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleModuleBtn.ProtoReflect.Descriptor instead.
func (*RoleModuleBtn) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RoleModuleBtn) GetOrgUUID() string {
	if x != nil {
		return x.OrgUUID
	}
	return ""
}

func (x *RoleModuleBtn) GetRoleUUID() string {
	if x != nil {
		return x.RoleUUID
	}
	return ""
}

func (x *RoleModuleBtn) GetModuleBtnUUID() []string {
	if x != nil {
		return x.ModuleBtnUUID
	}
	return nil
}

func (x *RoleModuleBtn) GetDeleteModuleBtnUUID() []string {
	if x != nil {
		return x.DeleteModuleBtnUUID
	}
	return nil
}

type RuntimeApiModuleButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiUUID       string                 `protobuf:"bytes,1,opt,name=apiUUID,proto3" json:"apiUUID,omitempty"`
	ModuleBtnUUID string                 `protobuf:"bytes,2,opt,name=moduleBtnUUID,proto3" json:"moduleBtnUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeApiModuleButton) Reset() {
	*x = RuntimeApiModuleButton{}
	mi := &file_gateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeApiModuleButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeApiModuleButton) ProtoMessage() {}

func (x *RuntimeApiModuleButton) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeApiModuleButton.ProtoReflect.Descriptor instead.
func (*RuntimeApiModuleButton) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeApiModuleButton) GetApiUUID() string {
	if x != nil {
		return x.ApiUUID
	}
	return ""
}

func (x *RuntimeApiModuleButton) GetModuleBtnUUID() string {
	if x != nil {
		return x.ModuleBtnUUID
	}
	return ""
}

type BatchRuntimeApiRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Apis          []*RuntimeApi             `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
	Buttons       []*RuntimeApiModuleButton `protobuf:"bytes,2,rep,name=buttons,proto3" json:"buttons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRuntimeApiRequest) Reset() {
	*x = BatchRuntimeApiRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRuntimeApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRuntimeApiRequest) ProtoMessage() {}

func (x *BatchRuntimeApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRuntimeApiRequest.ProtoReflect.Descriptor instead.
func (*BatchRuntimeApiRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *BatchRuntimeApiRequest) GetApis() []*RuntimeApi {
	if x != nil {
		return x.Apis
	}
	return nil
}

func (x *BatchRuntimeApiRequest) GetButtons() []*RuntimeApiModuleButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

type LockEnterpriseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnterpriseUUID string                 `protobuf:"bytes,1,opt,name=enterpriseUUID,proto3" json:"enterpriseUUID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LockEnterpriseRequest) Reset() {
	*x = LockEnterpriseRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockEnterpriseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockEnterpriseRequest) ProtoMessage() {}

func (x *LockEnterpriseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockEnterpriseRequest.ProtoReflect.Descriptor instead.
func (*LockEnterpriseRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *LockEnterpriseRequest) GetEnterpriseUUID() string {
	if x != nil {
		return x.EnterpriseUUID
	}
	return ""
}

var File_gateway_gateway_proto protoreflect.FileDescriptor

const file_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x15gateway/gateway.proto\x12\x14io.yunka.gateway.rpc\x1a\x18gateway/api_common.proto\x1a\x14gateway/common.proto\"e\n" +
	"\x19OperateRuntimeApiResponse\x126\n" +
	"\x04code\x18\x01 \x01(\x0e2\".io.yunka.gateway.rpc.ResponseCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"?\n" +
	"\x17DeleteRuntimeApiRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\"_\n" +
	"\x13OperateRoleResponse\x126\n" +
	"\x04code\x18\x01 \x01(\x0e2\".io.yunka.gateway.rpc.ResponseCodeR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x9d\x01\n" +
	"\rRoleModuleBtn\x12\x18\n" +
	"\aorgUUID\x18\x01 \x01(\tR\aorgUUID\x12\x1a\n" +
	"\broleUUID\x18\x02 \x01(\tR\broleUUID\x12$\n" +
	"\rmoduleBtnUUID\x18\x03 \x03(\tR\rmoduleBtnUUID\x120\n" +
	"\x13deleteModuleBtnUUID\x18\x04 \x03(\tR\x13deleteModuleBtnUUID\"X\n" +
	"\x16RuntimeApiModuleButton\x12\x18\n" +
	"\aapiUUID\x18\x01 \x01(\tR\aapiUUID\x12$\n" +
	"\rmoduleBtnUUID\x18\x02 \x01(\tR\rmoduleBtnUUID\"\x96\x01\n" +
	"\x16BatchRuntimeApiRequest\x124\n" +
	"\x04apis\x18\x01 \x03(\v2 .io.yunka.gateway.rpc.RuntimeApiR\x04apis\x12F\n" +
	"\abuttons\x18\x02 \x03(\v2,.io.yunka.gateway.rpc.RuntimeApiModuleButtonR\abuttons\"?\n" +
	"\x15LockEnterpriseRequest\x12&\n" +
	"\x0eenterpriseUUID\x18\x01 \x01(\tR\x0eenterpriseUUID2\xdb\x02\n" +
	"\x0eGatewayService\x12s\n" +
	"\x12BatchAddRuntimeApi\x12,.io.yunka.gateway.rpc.BatchRuntimeApiRequest\x1a/.io.yunka.gateway.rpc.OperateRuntimeApiResponse\x12r\n" +
	"\x10DeleteRuntimeApi\x12-.io.yunka.gateway.rpc.DeleteRuntimeApiRequest\x1a/.io.yunka.gateway.rpc.OperateRuntimeApiResponse\x12`\n" +
	"\x0eOperateRoleAPI\x12#.io.yunka.gateway.rpc.RoleModuleBtn\x1a).io.yunka.gateway.rpc.OperateRoleResponseB Z\x1eyunka.io/gateway/rpc/meta;metab\x06proto3"

var (
	file_gateway_gateway_proto_rawDescOnce sync.Once
	file_gateway_gateway_proto_rawDescData []byte
)

func file_gateway_gateway_proto_rawDescGZIP() []byte {
	file_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)))
	})
	return file_gateway_gateway_proto_rawDescData
}

var file_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gateway_gateway_proto_goTypes = []any{
	(*OperateRuntimeApiResponse)(nil), // 0: io.yunka.gateway.rpc.OperateRuntimeApiResponse
	(*DeleteRuntimeApiRequest)(nil),   // 1: io.yunka.gateway.rpc.DeleteRuntimeApiRequest
	(*OperateRoleResponse)(nil),       // 2: io.yunka.gateway.rpc.OperateRoleResponse
	(*RoleModuleBtn)(nil),             // 3: io.yunka.gateway.rpc.RoleModuleBtn
	(*RuntimeApiModuleButton)(nil),    // 4: io.yunka.gateway.rpc.RuntimeApiModuleButton
	(*BatchRuntimeApiRequest)(nil),    // 5: io.yunka.gateway.rpc.BatchRuntimeApiRequest
	(*LockEnterpriseRequest)(nil),     // 6: io.yunka.gateway.rpc.LockEnterpriseRequest
	(ResponseCode)(0),                 // 7: io.yunka.gateway.rpc.ResponseCode
	(*RuntimeApi)(nil),                // 8: io.yunka.gateway.rpc.RuntimeApi
}
var file_gateway_gateway_proto_depIdxs = []int32{
	7, // 0: io.yunka.gateway.rpc.OperateRuntimeApiResponse.code:type_name -> io.yunka.gateway.rpc.ResponseCode
	7, // 1: io.yunka.gateway.rpc.OperateRoleResponse.code:type_name -> io.yunka.gateway.rpc.ResponseCode
	8, // 2: io.yunka.gateway.rpc.BatchRuntimeApiRequest.apis:type_name -> io.yunka.gateway.rpc.RuntimeApi
	4, // 3: io.yunka.gateway.rpc.BatchRuntimeApiRequest.buttons:type_name -> io.yunka.gateway.rpc.RuntimeApiModuleButton
	5, // 4: io.yunka.gateway.rpc.GatewayService.BatchAddRuntimeApi:input_type -> io.yunka.gateway.rpc.BatchRuntimeApiRequest
	1, // 5: io.yunka.gateway.rpc.GatewayService.DeleteRuntimeApi:input_type -> io.yunka.gateway.rpc.DeleteRuntimeApiRequest
	3, // 6: io.yunka.gateway.rpc.GatewayService.OperateRoleAPI:input_type -> io.yunka.gateway.rpc.RoleModuleBtn
	0, // 7: io.yunka.gateway.rpc.GatewayService.BatchAddRuntimeApi:output_type -> io.yunka.gateway.rpc.OperateRuntimeApiResponse
	0, // 8: io.yunka.gateway.rpc.GatewayService.DeleteRuntimeApi:output_type -> io.yunka.gateway.rpc.OperateRuntimeApiResponse
	2, // 9: io.yunka.gateway.rpc.GatewayService.OperateRoleAPI:output_type -> io.yunka.gateway.rpc.OperateRoleResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_gateway_proto_init() }
func file_gateway_gateway_proto_init() {
	if File_gateway_gateway_proto != nil {
		return
	}
	file_gateway_api_common_proto_init()
	file_gateway_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_gateway_proto_msgTypes,
	}.Build()
	File_gateway_gateway_proto = out.File
	file_gateway_gateway_proto_goTypes = nil
	file_gateway_gateway_proto_depIdxs = nil
}
