// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: gateway/gateway.proto

package meta

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_BatchAddRuntimeApi_FullMethodName = "/io.yunka.gateway.rpc.GatewayService/BatchAddRuntimeApi"
	GatewayService_DeleteRuntimeApi_FullMethodName   = "/io.yunka.gateway.rpc.GatewayService/DeleteRuntimeApi"
	GatewayService_OperateRoleAPI_FullMethodName     = "/io.yunka.gateway.rpc.GatewayService/OperateRoleAPI"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	BatchAddRuntimeApi(ctx context.Context, in *BatchRuntimeApiRequest, opts ...grpc.CallOption) (*OperateRuntimeApiResponse, error)
	DeleteRuntimeApi(ctx context.Context, in *DeleteRuntimeApiRequest, opts ...grpc.CallOption) (*OperateRuntimeApiResponse, error)
	OperateRoleAPI(ctx context.Context, in *RoleModuleBtn, opts ...grpc.CallOption) (*OperateRoleResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) BatchAddRuntimeApi(ctx context.Context, in *BatchRuntimeApiRequest, opts ...grpc.CallOption) (*OperateRuntimeApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateRuntimeApiResponse)
	err := c.cc.Invoke(ctx, GatewayService_BatchAddRuntimeApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DeleteRuntimeApi(ctx context.Context, in *DeleteRuntimeApiRequest, opts ...grpc.CallOption) (*OperateRuntimeApiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateRuntimeApiResponse)
	err := c.cc.Invoke(ctx, GatewayService_DeleteRuntimeApi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) OperateRoleAPI(ctx context.Context, in *RoleModuleBtn, opts ...grpc.CallOption) (*OperateRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateRoleResponse)
	err := c.cc.Invoke(ctx, GatewayService_OperateRoleAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations should embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	BatchAddRuntimeApi(context.Context, *BatchRuntimeApiRequest) (*OperateRuntimeApiResponse, error)
	DeleteRuntimeApi(context.Context, *DeleteRuntimeApiRequest) (*OperateRuntimeApiResponse, error)
	OperateRoleAPI(context.Context, *RoleModuleBtn) (*OperateRoleResponse, error)
}

// UnimplementedGatewayServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) BatchAddRuntimeApi(context.Context, *BatchRuntimeApiRequest) (*OperateRuntimeApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchAddRuntimeApi not implemented")
}
func (UnimplementedGatewayServiceServer) DeleteRuntimeApi(context.Context, *DeleteRuntimeApiRequest) (*OperateRuntimeApiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRuntimeApi not implemented")
}
func (UnimplementedGatewayServiceServer) OperateRoleAPI(context.Context, *RoleModuleBtn) (*OperateRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OperateRoleAPI not implemented")
}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue() {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_BatchAddRuntimeApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRuntimeApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).BatchAddRuntimeApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_BatchAddRuntimeApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).BatchAddRuntimeApi(ctx, req.(*BatchRuntimeApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DeleteRuntimeApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuntimeApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DeleteRuntimeApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DeleteRuntimeApi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DeleteRuntimeApi(ctx, req.(*DeleteRuntimeApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_OperateRoleAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleModuleBtn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).OperateRoleAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_OperateRoleAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).OperateRoleAPI(ctx, req.(*RoleModuleBtn))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.yunka.gateway.rpc.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchAddRuntimeApi",
			Handler:    _GatewayService_BatchAddRuntimeApi_Handler,
		},
		{
			MethodName: "DeleteRuntimeApi",
			Handler:    _GatewayService_DeleteRuntimeApi_Handler,
		},
		{
			MethodName: "OperateRoleAPI",
			Handler:    _GatewayService_OperateRoleAPI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/gateway.proto",
}
