// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package meta

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperateRuntimeApiResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=io.yunka.gateway.rpc.ResponseCode" json:"code,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OperateRuntimeApiResponse) Reset()         { *m = OperateRuntimeApiResponse{} }
func (m *OperateRuntimeApiResponse) String() string { return proto.CompactTextString(m) }
func (*OperateRuntimeApiResponse) ProtoMessage()    {}
func (*OperateRuntimeApiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *OperateRuntimeApiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperateRuntimeApiResponse.Unmarshal(m, b)
}
func (m *OperateRuntimeApiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperateRuntimeApiResponse.Marshal(b, m, deterministic)
}
func (m *OperateRuntimeApiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperateRuntimeApiResponse.Merge(m, src)
}
func (m *OperateRuntimeApiResponse) XXX_Size() int {
	return xxx_messageInfo_OperateRuntimeApiResponse.Size(m)
}
func (m *OperateRuntimeApiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OperateRuntimeApiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OperateRuntimeApiResponse proto.InternalMessageInfo

func (m *OperateRuntimeApiResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Not
}

func (m *OperateRuntimeApiResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteRuntimeApiRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Uri                  string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRuntimeApiRequest) Reset()         { *m = DeleteRuntimeApiRequest{} }
func (m *DeleteRuntimeApiRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRuntimeApiRequest) ProtoMessage()    {}
func (*DeleteRuntimeApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *DeleteRuntimeApiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuntimeApiRequest.Unmarshal(m, b)
}
func (m *DeleteRuntimeApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuntimeApiRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRuntimeApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuntimeApiRequest.Merge(m, src)
}
func (m *DeleteRuntimeApiRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRuntimeApiRequest.Size(m)
}
func (m *DeleteRuntimeApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuntimeApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuntimeApiRequest proto.InternalMessageInfo

func (m *DeleteRuntimeApiRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DeleteRuntimeApiRequest) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type OperateRoleResponse struct {
	Code                 ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=io.yunka.gateway.rpc.ResponseCode" json:"code,omitempty"`
	Msg                  string       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OperateRoleResponse) Reset()         { *m = OperateRoleResponse{} }
func (m *OperateRoleResponse) String() string { return proto.CompactTextString(m) }
func (*OperateRoleResponse) ProtoMessage()    {}
func (*OperateRoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}

func (m *OperateRoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperateRoleResponse.Unmarshal(m, b)
}
func (m *OperateRoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperateRoleResponse.Marshal(b, m, deterministic)
}
func (m *OperateRoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperateRoleResponse.Merge(m, src)
}
func (m *OperateRoleResponse) XXX_Size() int {
	return xxx_messageInfo_OperateRoleResponse.Size(m)
}
func (m *OperateRoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OperateRoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OperateRoleResponse proto.InternalMessageInfo

func (m *OperateRoleResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Not
}

func (m *OperateRoleResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RoleModuleBtn struct {
	OrgUUID              string   `protobuf:"bytes,1,opt,name=orgUUID,proto3" json:"orgUUID,omitempty"`
	RoleUUID             string   `protobuf:"bytes,2,opt,name=roleUUID,proto3" json:"roleUUID,omitempty"`
	ModuleBtnUUID        []string `protobuf:"bytes,3,rep,name=moduleBtnUUID,proto3" json:"moduleBtnUUID,omitempty"`
	DeleteModuleBtnUUID  []string `protobuf:"bytes,4,rep,name=deleteModuleBtnUUID,proto3" json:"deleteModuleBtnUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleModuleBtn) Reset()         { *m = RoleModuleBtn{} }
func (m *RoleModuleBtn) String() string { return proto.CompactTextString(m) }
func (*RoleModuleBtn) ProtoMessage()    {}
func (*RoleModuleBtn) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{3}
}

func (m *RoleModuleBtn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleModuleBtn.Unmarshal(m, b)
}
func (m *RoleModuleBtn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleModuleBtn.Marshal(b, m, deterministic)
}
func (m *RoleModuleBtn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleModuleBtn.Merge(m, src)
}
func (m *RoleModuleBtn) XXX_Size() int {
	return xxx_messageInfo_RoleModuleBtn.Size(m)
}
func (m *RoleModuleBtn) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleModuleBtn.DiscardUnknown(m)
}

var xxx_messageInfo_RoleModuleBtn proto.InternalMessageInfo

func (m *RoleModuleBtn) GetOrgUUID() string {
	if m != nil {
		return m.OrgUUID
	}
	return ""
}

func (m *RoleModuleBtn) GetRoleUUID() string {
	if m != nil {
		return m.RoleUUID
	}
	return ""
}

func (m *RoleModuleBtn) GetModuleBtnUUID() []string {
	if m != nil {
		return m.ModuleBtnUUID
	}
	return nil
}

func (m *RoleModuleBtn) GetDeleteModuleBtnUUID() []string {
	if m != nil {
		return m.DeleteModuleBtnUUID
	}
	return nil
}

type RuntimeApiModuleButton struct {
	ApiUUID              string   `protobuf:"bytes,1,opt,name=apiUUID,proto3" json:"apiUUID,omitempty"`
	ModuleBtnUUID        string   `protobuf:"bytes,2,opt,name=moduleBtnUUID,proto3" json:"moduleBtnUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuntimeApiModuleButton) Reset()         { *m = RuntimeApiModuleButton{} }
func (m *RuntimeApiModuleButton) String() string { return proto.CompactTextString(m) }
func (*RuntimeApiModuleButton) ProtoMessage()    {}
func (*RuntimeApiModuleButton) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{4}
}

func (m *RuntimeApiModuleButton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuntimeApiModuleButton.Unmarshal(m, b)
}
func (m *RuntimeApiModuleButton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuntimeApiModuleButton.Marshal(b, m, deterministic)
}
func (m *RuntimeApiModuleButton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuntimeApiModuleButton.Merge(m, src)
}
func (m *RuntimeApiModuleButton) XXX_Size() int {
	return xxx_messageInfo_RuntimeApiModuleButton.Size(m)
}
func (m *RuntimeApiModuleButton) XXX_DiscardUnknown() {
	xxx_messageInfo_RuntimeApiModuleButton.DiscardUnknown(m)
}

var xxx_messageInfo_RuntimeApiModuleButton proto.InternalMessageInfo

func (m *RuntimeApiModuleButton) GetApiUUID() string {
	if m != nil {
		return m.ApiUUID
	}
	return ""
}

func (m *RuntimeApiModuleButton) GetModuleBtnUUID() string {
	if m != nil {
		return m.ModuleBtnUUID
	}
	return ""
}

type BatchRuntimeApiRequest struct {
	Apis                 []*RuntimeApi             `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
	Buttons              []*RuntimeApiModuleButton `protobuf:"bytes,2,rep,name=buttons,proto3" json:"buttons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BatchRuntimeApiRequest) Reset()         { *m = BatchRuntimeApiRequest{} }
func (m *BatchRuntimeApiRequest) String() string { return proto.CompactTextString(m) }
func (*BatchRuntimeApiRequest) ProtoMessage()    {}
func (*BatchRuntimeApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{5}
}

func (m *BatchRuntimeApiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchRuntimeApiRequest.Unmarshal(m, b)
}
func (m *BatchRuntimeApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchRuntimeApiRequest.Marshal(b, m, deterministic)
}
func (m *BatchRuntimeApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchRuntimeApiRequest.Merge(m, src)
}
func (m *BatchRuntimeApiRequest) XXX_Size() int {
	return xxx_messageInfo_BatchRuntimeApiRequest.Size(m)
}
func (m *BatchRuntimeApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchRuntimeApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchRuntimeApiRequest proto.InternalMessageInfo

func (m *BatchRuntimeApiRequest) GetApis() []*RuntimeApi {
	if m != nil {
		return m.Apis
	}
	return nil
}

func (m *BatchRuntimeApiRequest) GetButtons() []*RuntimeApiModuleButton {
	if m != nil {
		return m.Buttons
	}
	return nil
}

type LockEnterpriseRequest struct {
	EnterpriseUUID       string   `protobuf:"bytes,1,opt,name=enterpriseUUID,proto3" json:"enterpriseUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockEnterpriseRequest) Reset()         { *m = LockEnterpriseRequest{} }
func (m *LockEnterpriseRequest) String() string { return proto.CompactTextString(m) }
func (*LockEnterpriseRequest) ProtoMessage()    {}
func (*LockEnterpriseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{6}
}

func (m *LockEnterpriseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockEnterpriseRequest.Unmarshal(m, b)
}
func (m *LockEnterpriseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockEnterpriseRequest.Marshal(b, m, deterministic)
}
func (m *LockEnterpriseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockEnterpriseRequest.Merge(m, src)
}
func (m *LockEnterpriseRequest) XXX_Size() int {
	return xxx_messageInfo_LockEnterpriseRequest.Size(m)
}
func (m *LockEnterpriseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockEnterpriseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockEnterpriseRequest proto.InternalMessageInfo

func (m *LockEnterpriseRequest) GetEnterpriseUUID() string {
	if m != nil {
		return m.EnterpriseUUID
	}
	return ""
}

func init() {
	proto.RegisterType((*OperateRuntimeApiResponse)(nil), "io.yunka.gateway.rpc.OperateRuntimeApiResponse")
	proto.RegisterType((*DeleteRuntimeApiRequest)(nil), "io.yunka.gateway.rpc.DeleteRuntimeApiRequest")
	proto.RegisterType((*OperateRoleResponse)(nil), "io.yunka.gateway.rpc.OperateRoleResponse")
	proto.RegisterType((*RoleModuleBtn)(nil), "io.yunka.gateway.rpc.RoleModuleBtn")
	proto.RegisterType((*RuntimeApiModuleButton)(nil), "io.yunka.gateway.rpc.RuntimeApiModuleButton")
	proto.RegisterType((*BatchRuntimeApiRequest)(nil), "io.yunka.gateway.rpc.BatchRuntimeApiRequest")
	proto.RegisterType((*LockEnterpriseRequest)(nil), "io.yunka.gateway.rpc.LockEnterpriseRequest")
}

func init() {
	proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5)
}

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x13, 0xab, 0x25, 0x03, 0x89, 0xa2, 0x2d, 0x14, 0xe3, 0x93, 0x65, 0x10, 0x0a, 0x12,
	0x18, 0x14, 0x10, 0xd7, 0x2a, 0xa1, 0x80, 0x2a, 0x51, 0x81, 0x8c, 0x2a, 0x21, 0x2e, 0x65, 0x6b,
	0x8f, 0xc2, 0xaa, 0xb1, 0x77, 0xd9, 0x0f, 0x50, 0xff, 0x08, 0x37, 0x7e, 0x19, 0x7f, 0x06, 0x65,
	0x9d, 0x6d, 0xec, 0xc6, 0x06, 0x71, 0xe8, 0xcd, 0x33, 0xfb, 0xe6, 0xbd, 0x37, 0xb3, 0x3b, 0x86,
	0xe1, 0x82, 0x6a, 0xfc, 0x41, 0x2f, 0x12, 0x21, 0xb9, 0xe6, 0xe4, 0x36, 0xe3, 0xc9, 0x85, 0x29,
	0xcf, 0x69, 0xe2, 0xf2, 0x52, 0x64, 0xe1, 0x98, 0x0a, 0x76, 0x9a, 0xf1, 0xa2, 0xe0, 0x65, 0x85,
	0x0b, 0x6f, 0xd5, 0xa3, 0x18, 0xe1, 0xde, 0x7b, 0x81, 0x92, 0x6a, 0x4c, 0x4d, 0xa9, 0x59, 0x81,
	0x33, 0xc1, 0x52, 0x54, 0x82, 0x97, 0x0a, 0xc9, 0x4b, 0xf0, 0x33, 0x9e, 0x63, 0xe0, 0x45, 0xde,
	0x64, 0x34, 0x8d, 0x93, 0x36, 0x85, 0xc4, 0xa1, 0x5f, 0xf1, 0x1c, 0x53, 0x8b, 0x27, 0x63, 0xe8,
	0x17, 0x6a, 0x11, 0xf4, 0x22, 0x6f, 0x32, 0x48, 0x57, 0x9f, 0xf1, 0x01, 0xdc, 0x3d, 0xc4, 0x25,
	0x36, 0x55, 0xbe, 0x19, 0x54, 0x9a, 0x10, 0xf0, 0x8d, 0x61, 0xb9, 0x15, 0x19, 0xa4, 0xf6, 0x7b,
	0x45, 0x60, 0x24, 0x73, 0x04, 0x46, 0xb2, 0xf8, 0x14, 0xf6, 0x9c, 0x4f, 0xbe, 0xc4, 0x6b, 0x70,
	0xf8, 0xcb, 0x83, 0xe1, 0x8a, 0xfa, 0x98, 0xe7, 0x66, 0x89, 0x73, 0x5d, 0x92, 0x00, 0x76, 0xb9,
	0x5c, 0x9c, 0x9c, 0x1c, 0x1d, 0xae, 0xbd, 0xb9, 0x90, 0x84, 0x70, 0x43, 0xf2, 0x25, 0xda, 0xa3,
	0x8a, 0xe2, 0x32, 0x26, 0x0f, 0x60, 0x58, 0x38, 0x0a, 0x0b, 0xe8, 0x47, 0xfd, 0xc9, 0x20, 0x6d,
	0x26, 0xc9, 0x33, 0xd8, 0xcb, 0xed, 0x3c, 0x8e, 0x1b, 0x58, 0xdf, 0x62, 0xdb, 0x8e, 0xe2, 0x4f,
	0xb0, 0xbf, 0x99, 0xdd, 0xfa, 0xc8, 0x68, 0xcd, 0xad, 0x4f, 0x2a, 0x58, 0xdd, 0xe7, 0x3a, 0xdc,
	0xf6, 0x52, 0x99, 0x6d, 0x26, 0xe3, 0x9f, 0x1e, 0xec, 0xcf, 0xa9, 0xce, 0xbe, 0x6e, 0xdf, 0xcd,
	0x0b, 0xf0, 0xa9, 0x60, 0x2a, 0xf0, 0xa2, 0xfe, 0xe4, 0xe6, 0x34, 0xea, 0x18, 0xef, 0xa6, 0xcc,
	0xa2, 0xc9, 0x1b, 0xd8, 0x3d, 0xb3, 0xd6, 0x54, 0xd0, 0xb3, 0x85, 0x8f, 0xff, 0x55, 0x58, 0xef,
	0x27, 0x75, 0xc5, 0xf1, 0x01, 0xdc, 0x79, 0xc7, 0xb3, 0xf3, 0xd7, 0xa5, 0x46, 0x29, 0x24, 0x53,
	0xe8, 0x6c, 0x3d, 0x84, 0x11, 0x5e, 0x26, 0x6b, 0x8d, 0x5f, 0xc9, 0x4e, 0x7f, 0xf7, 0x60, 0xf4,
	0xb6, 0x12, 0xfc, 0x88, 0xf2, 0x3b, 0xcb, 0x90, 0x28, 0x20, 0xb6, 0xd7, 0x59, 0x9e, 0x6f, 0xe4,
	0x49, 0x87, 0xc1, 0xf6, 0xa9, 0x84, 0x4f, 0xdb, 0xd1, 0xdd, 0x7b, 0x24, 0x61, 0x7c, 0xf5, 0xf5,
	0x93, 0x27, 0xed, 0x24, 0x1d, 0x5b, 0xf2, 0xff, 0x9a, 0x5f, 0x60, 0x54, 0x5b, 0x98, 0xd9, 0x87,
	0x23, 0x72, 0xbf, 0xe3, 0x16, 0xea, 0x8f, 0x3e, 0x7c, 0xf4, 0x77, 0x9d, 0xda, 0xee, 0xcd, 0x77,
	0x3e, 0xfb, 0x05, 0x6a, 0x7a, 0xb6, 0x63, 0xff, 0x24, 0xcf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x46, 0xb4, 0x10, 0xcf, 0x90, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayServiceClient interface {
	BatchAddRuntimeApi(ctx context.Context, in *BatchRuntimeApiRequest, opts ...grpc.CallOption) (*OperateRuntimeApiResponse, error)
	DeleteRuntimeApi(ctx context.Context, in *DeleteRuntimeApiRequest, opts ...grpc.CallOption) (*OperateRuntimeApiResponse, error)
	OperateRoleAPI(ctx context.Context, in *RoleModuleBtn, opts ...grpc.CallOption) (*OperateRoleResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) BatchAddRuntimeApi(ctx context.Context, in *BatchRuntimeApiRequest, opts ...grpc.CallOption) (*OperateRuntimeApiResponse, error) {
	out := new(OperateRuntimeApiResponse)
	err := c.cc.Invoke(ctx, "/io.yunka.gateway.rpc.GatewayService/BatchAddRuntimeApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DeleteRuntimeApi(ctx context.Context, in *DeleteRuntimeApiRequest, opts ...grpc.CallOption) (*OperateRuntimeApiResponse, error) {
	out := new(OperateRuntimeApiResponse)
	err := c.cc.Invoke(ctx, "/io.yunka.gateway.rpc.GatewayService/DeleteRuntimeApi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) OperateRoleAPI(ctx context.Context, in *RoleModuleBtn, opts ...grpc.CallOption) (*OperateRoleResponse, error) {
	out := new(OperateRoleResponse)
	err := c.cc.Invoke(ctx, "/io.yunka.gateway.rpc.GatewayService/OperateRoleAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
type GatewayServiceServer interface {
	BatchAddRuntimeApi(context.Context, *BatchRuntimeApiRequest) (*OperateRuntimeApiResponse, error)
	DeleteRuntimeApi(context.Context, *DeleteRuntimeApiRequest) (*OperateRuntimeApiResponse, error)
	OperateRoleAPI(context.Context, *RoleModuleBtn) (*OperateRoleResponse, error)
}

// UnimplementedGatewayServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayServiceServer struct {
}

func (*UnimplementedGatewayServiceServer) BatchAddRuntimeApi(ctx context.Context, req *BatchRuntimeApiRequest) (*OperateRuntimeApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchAddRuntimeApi not implemented")
}
func (*UnimplementedGatewayServiceServer) DeleteRuntimeApi(ctx context.Context, req *DeleteRuntimeApiRequest) (*OperateRuntimeApiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRuntimeApi not implemented")
}
func (*UnimplementedGatewayServiceServer) OperateRoleAPI(ctx context.Context, req *RoleModuleBtn) (*OperateRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperateRoleAPI not implemented")
}

func RegisterGatewayServiceServer(s *grpc.Server, srv GatewayServiceServer) {
	s.RegisterService(&_GatewayService_serviceDesc, srv)
}

func _GatewayService_BatchAddRuntimeApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRuntimeApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).BatchAddRuntimeApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.yunka.gateway.rpc.GatewayService/BatchAddRuntimeApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).BatchAddRuntimeApi(ctx, req.(*BatchRuntimeApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DeleteRuntimeApi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuntimeApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DeleteRuntimeApi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.yunka.gateway.rpc.GatewayService/DeleteRuntimeApi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DeleteRuntimeApi(ctx, req.(*DeleteRuntimeApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_OperateRoleAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoleModuleBtn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).OperateRoleAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.yunka.gateway.rpc.GatewayService/OperateRoleAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).OperateRoleAPI(ctx, req.(*RoleModuleBtn))
	}
	return interceptor(ctx, in, info, handler)
}

var _GatewayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.yunka.gateway.rpc.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchAddRuntimeApi",
			Handler:    _GatewayService_BatchAddRuntimeApi_Handler,
		},
		{
			MethodName: "DeleteRuntimeApi",
			Handler:    _GatewayService_DeleteRuntimeApi_Handler,
		},
		{
			MethodName: "OperateRoleAPI",
			Handler:    _GatewayService_OperateRoleAPI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
