syntax = "proto3";
package io.yunka.gateway.rpc;

option go_package = "meta";

/**
* @Description: TODO
* @date 2019-07-16
* @version V1.0
*/
enum CallType {
    CallReserve = 0;
    HttpCall = 1;
    RpcCall = 2;
}

// auth byte : ---- api req_district check_role check_token
// 判断 auth是否为0 即可判断API是否需要权限
enum AuthBit {
    AuthNot = 0;
    AuthToken = 2;
    AuthRole = 4;
    AuthTimeLimit = 8; // 需要检测token 下发时间
    AuthApi = 16; // 接口可以过API
}

// 网关运行时所需要的api
message RuntimeApi {
    string uuid = 1;
    string srvName = 2;
    string moduleName = 3;
    string uri = 4;
    string name = 5; // 用作接口聚合返回结果的key
    CallType callType = 6;
    AuthBit auth = 7;
    string srvApi = 8;
    bool isRedirect = 9;
    repeated RuntimeApi composes = 10;
}


message CircuitCfg {
    int32 CloseTime = 1;
    int32 CheckPeriod = 2;
    int32 LimitPercent = 3;
    int32 HalfOpen = 4;
    int32 HalfClose = 5;
}

message ServerNode {
    string ipPort = 1;
    string uuid = 2;
    int32 qps = 3;
    string srvName = 4;
    CircuitCfg Circuit = 5;
}
