// Code generated by yunka domain; DO NOT EDIT.

package wire

import (
	"context"
	"fmt"
	application "github.com/hvritual/biz/internal/iam/application"
	persistence "github.com/hvritual/biz/internal/iam/infrastructure/persistence"
	"gorm.io/gorm"
)

type Bundle struct{ Service application.Service }

func Build(database *gorm.DB) (Bundle, error) {
	if err := persistence.AutoMigrate(context.Background(), database); err != nil {
		return Bundle{}, fmt.Errorf("domain wire: auto migrate: %w", err)
	}
	scopes, err := persistence.NewScopeFactory(database)
	if err != nil {
		return Bundle{}, err
	}
	service, err := application.NewService(scopes)
	if err != nil {
		return Bundle{}, err
	}
	return Bundle{Service: service}, nil
}
