package contract

import (
	"fmt"
	"go/format"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

const GeneratedApplicationMarker = "// Code generated by yunka contract; DO NOT EDIT."

type ApplicationCodeOptions struct {
	RootImport string
}

type GeneratedApplicationFile struct {
	Path    string
	Content []byte
}

type protoGoPackage struct {
	ProtoPackage string
	ImportPath   string
	Alias        string
}

type goTypeRef struct {
	ImportPath string
	Alias      string
	Type       string
}

type serviceCodegenNaming struct {
	Multi                bool
	FileStem             string
	Symbol               string
	ApplicationInterface string
	OperationPrefix      string
	PermissionsFunc      string
	ResolverFunc         string
	PoliciesFunc         string
	RPCServer            string
	RPCRegister          string
	RESTHandler          string
	RESTRegister         string
	SecurityError        string
}

func namingForService(service Service, multi bool) serviceCodegenNaming {
	fileStem := safeFileName(service.Application.Name)
	if fileStem == "" {
		fileStem = safeFileName(service.Name)
	}
	if !multi {
		return serviceCodegenNaming{
			FileStem:             fileStem,
			Symbol:               service.Name,
			ApplicationInterface: service.Name,
			PermissionsFunc:      "Permissions",
			ResolverFunc:         "Resolver",
			PoliciesFunc:         "policies",
			RPCServer:            service.Name + "Server",
			RPCRegister:          "Register",
			RESTHandler:          "Handler",
			RESTRegister:         "Register",
			SecurityError:        "writeSecurityError",
		}
	}
	symbol := exportedApplicationSymbol(service.Application.Name)
	if symbol == "" {
		symbol = exportedApplicationSymbol(service.Name)
	}
	applicationInterface := symbol
	if !strings.HasSuffix(applicationInterface, "Application") {
		applicationInterface += "Application"
	}
	privateSymbol := lowerFirstIdentifier(symbol)
	return serviceCodegenNaming{
		Multi:                true,
		FileStem:             fileStem,
		Symbol:               symbol,
		ApplicationInterface: applicationInterface,
		OperationPrefix:      symbol,
		PermissionsFunc:      symbol + "Permissions",
		ResolverFunc:         symbol + "Resolver",
		PoliciesFunc:         privateSymbol + "Policies",
		RPCServer:            symbol + "Server",
		RPCRegister:          "Register" + symbol,
		RESTHandler:          symbol + "Handler",
		RESTRegister:         "Register" + symbol,
		SecurityError:        "write" + symbol + "SecurityError",
	}
}

func exportedApplicationSymbol(value string) string {
	parts := strings.FieldsFunc(strings.TrimSpace(value), func(current rune) bool {
		return !unicode.IsLetter(current) && !unicode.IsDigit(current)
	})
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	return sanitizeGoIdentifier(b.String())
}

func lowerFirstIdentifier(value string) string {
	runes := []rune(value)
	if len(runes) == 0 {
		return "application"
	}
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func operationIdentifier(naming serviceCodegenNaming, method Method) string {
	return "Operation" + naming.OperationPrefix + method.Name
}

func RenderApplicationCode(manifest Manifest, options ApplicationCodeOptions) ([]GeneratedApplicationFile, error) {
	manifest.Normalize()
	rootImport := strings.TrimRight(strings.TrimSpace(options.RootImport), "/")
	if rootImport == "" {
		return nil, fmt.Errorf("contract application codegen: root import is required")
	}
	packages, err := buildProtoGoPackages(manifest)
	if err != nil {
		return nil, err
	}
	messages := messageIndex(manifest)
	typedByDomain := make(map[string][]Service)
	for _, service := range manifest.Services {
		if service.Application == nil {
			continue
		}
		if service.Domain == "" {
			return nil, fmt.Errorf("contract application codegen: service %s has no domain", service.FullName)
		}
		typedByDomain[service.Domain] = append(typedByDomain[service.Domain], service)
	}
	domains := make([]string, 0, len(typedByDomain))
	for domain := range typedByDomain {
		domains = append(domains, domain)
	}
	sort.Strings(domains)

	var files []GeneratedApplicationFile
	for _, domain := range domains {
		services := append([]Service(nil), typedByDomain[domain]...)
		sort.Slice(services, func(i, j int) bool { return services[i].FullName < services[j].FullName })
		multi := len(services) > 1
		namings := make(map[string]serviceCodegenNaming, len(services))
		codegenOwners := map[string]string{}
		for _, service := range services {
			naming := namingForService(service, multi)
			if multi {
				identity := naming.FileStem + "|" + naming.Symbol
				if owner, duplicate := codegenOwners[identity]; duplicate && owner != service.FullName {
					return nil, fmt.Errorf("contract application codegen: applications %s and %s collapse to the same generated identity %q", owner, service.FullName, identity)
				}
				codegenOwners[identity] = service.FullName
			}
			namings[service.FullName] = naming
			for _, method := range service.Methods {
				if method.Operation == nil {
					return nil, fmt.Errorf("contract application codegen: typed application method %s has no operation", method.FullName)
				}
				if method.ClientStreaming || method.ServerStreaming {
					return nil, fmt.Errorf("contract application codegen: streaming method %s requires handwritten adapter", method.FullName)
				}
				if _, ok := messages[method.Request]; !ok && !knownExternalType(method.Request) {
					return nil, fmt.Errorf("contract application codegen: request %s is not in the manifest", method.Request)
				}
				if _, ok := messages[method.Response]; !ok && !knownExternalType(method.Response) {
					return nil, fmt.Errorf("contract application codegen: response %s is not in the manifest", method.Response)
				}
				for _, binding := range method.HTTP {
					if binding.Body != "" && binding.Body != "*" {
						return nil, fmt.Errorf("contract application codegen: %s HTTP body %q requires handwritten mapping", method.FullName, binding.Body)
					}
					if binding.ResponseBody != "" {
						return nil, fmt.Errorf("contract application codegen: %s response_body requires handwritten mapping", method.FullName)
					}
					if _, err := simplePathFields(binding.Path); err != nil {
						return nil, fmt.Errorf("contract application codegen: %s: %w", method.FullName, err)
					}
				}
			}

			domainDir := filepath.ToSlash(service.Domain)
			artifacts := []struct {
				path   string
				render func() (string, error)
			}{
				{filepath.ToSlash(filepath.Join(domainDir, "application", "zz_yunka_"+naming.FileStem+"_application_port_gen.go")), func() (string, error) {
					return renderApplicationPort(service, packages, naming)
				}},
				{filepath.ToSlash(filepath.Join(domainDir, "policy", "zz_yunka_"+naming.FileStem+"_operation_policy_gen.go")), func() (string, error) {
					return renderOperationPolicy(service, naming)
				}},
				{filepath.ToSlash(filepath.Join(domainDir, "transport", "rpc", "zz_yunka_"+naming.FileStem+"_rpc_adapter_gen.go")), func() (string, error) {
					return renderRPCAdapter(service, packages, rootImport, naming)
				}},
				{filepath.ToSlash(filepath.Join(domainDir, "transport", "rest", "zz_yunka_"+naming.FileStem+"_rest_adapter_gen.go")), func() (string, error) {
					return renderRESTAdapter(service, packages, messages, rootImport, naming)
				}},
			}
			for _, artifact := range artifacts {
				source, err := artifact.render()
				if err != nil {
					return nil, err
				}
				formatted, err := format.Source([]byte(source))
				if err != nil {
					return nil, fmt.Errorf("contract application codegen: format %s: %w\n%s", artifact.path, err, source)
				}
				files = append(files, GeneratedApplicationFile{Path: artifact.path, Content: formatted})
			}
		}
		if multi {
			source, err := renderDomainPolicy(services, namings)
			if err != nil {
				return nil, err
			}
			formatted, err := format.Source([]byte(source))
			if err != nil {
				return nil, fmt.Errorf("contract application codegen: format domain policy %s: %w\n%s", domain, err, source)
			}
			files = append(files, GeneratedApplicationFile{
				Path:    filepath.ToSlash(filepath.Join(domain, "policy", "zz_yunka_domain_operation_policy_gen.go")),
				Content: formatted,
			})
		}
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

func renderApplicationPort(service Service, packages []protoGoPackage, naming serviceCodegenNaming) (string, error) {
	imports := newImportSet()
	var methods strings.Builder
	for _, method := range service.Methods {
		request, err := resolveGoType(method.Request, packages, imports)
		if err != nil {
			return "", err
		}
		response, err := resolveGoType(method.Response, packages, imports)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&methods, "\t%s(context.Context, *%s.%s) (*%s.%s, error)\n", method.Name, request.Alias, request.Type, response.Alias, response.Type)
	}
	var b strings.Builder
	b.WriteString(GeneratedApplicationMarker + "\n\npackage application\n\nimport (\n\t\"context\"\n")
	b.WriteString(imports.render())
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "// %s is generated from PB and contains no business implementation.\n", service.Name)
	fmt.Fprintf(&b, "type %s interface {\n%s}\n", naming.ApplicationInterface, methods.String())
	return b.String(), nil
}

func renderOperationPolicy(service Service, naming serviceCodegenNaming) (string, error) {
	if !naming.Multi {
		var b strings.Builder
		b.WriteString(GeneratedApplicationMarker + "\n\npackage policy\n\n")
		b.WriteString("import \"yunka.io/gateway/authz\"\n\n")
		for _, method := range service.Methods {
			operation := method.Operation
			fmt.Fprintf(&b, "const Operation%s authz.OperationID = %q\n", method.Name, operation.ID)
		}
		permissionSet := map[string]struct{}{}
		for _, method := range service.Methods {
			for _, permission := range method.Operation.Permissions {
				if permission = strings.TrimSpace(permission); permission != "" {
					permissionSet[permission] = struct{}{}
				}
			}
		}
		permissionValues := make([]string, 0, len(permissionSet))
		for permission := range permissionSet {
			permissionValues = append(permissionValues, permission)
		}
		sort.Strings(permissionValues)
		b.WriteString("\nfunc Permissions() []authz.PermissionKey {\n\treturn []authz.PermissionKey{")
		for _, permission := range permissionValues {
			fmt.Fprintf(&b, "%q,", permission)
		}
		b.WriteString("}\n}\n")
		b.WriteString("\nfunc Resolver() authz.StaticResolver {\n\treturn authz.NewStaticResolver(map[string]authz.Policy{\n")
		for _, method := range service.Methods {
			operation := method.Operation
			fullMethod := "/" + strings.TrimPrefix(service.FullName, ".") + "/" + method.Name
			fmt.Fprintf(&b, "\t\t%q: {Operation: Operation%s", fullMethod, method.Name)
			writeOperationPolicyLiteral(&b, operation)
			b.WriteString("},\n")
		}
		b.WriteString("\t})\n}\n")
		return b.String(), nil
	}

	var b strings.Builder
	b.WriteString(GeneratedApplicationMarker + "\n\npackage policy\n\n")
	b.WriteString("import \"yunka.io/gateway/authz\"\n\n")
	for _, method := range service.Methods {
		fmt.Fprintf(&b, "const %s authz.OperationID = %q\n", operationIdentifier(naming, method), method.Operation.ID)
	}
	permissions := servicePermissionValues(service)
	fmt.Fprintf(&b, "\nfunc %s() []authz.PermissionKey {\n\treturn []authz.PermissionKey{", naming.PermissionsFunc)
	for _, permission := range permissions {
		fmt.Fprintf(&b, "%q,", permission)
	}
	b.WriteString("}\n}\n")
	fmt.Fprintf(&b, "\nfunc %s() authz.StaticResolver { return authz.NewStaticResolver(%s()) }\n", naming.ResolverFunc, naming.PoliciesFunc)
	fmt.Fprintf(&b, "\nfunc %s() map[string]authz.Policy {\n\treturn map[string]authz.Policy{\n", naming.PoliciesFunc)
	for _, method := range service.Methods {
		operation := method.Operation
		fullMethod := "/" + strings.TrimPrefix(service.FullName, ".") + "/" + method.Name
		fmt.Fprintf(&b, "\t\t%q: {Operation: %s", fullMethod, operationIdentifier(naming, method))
		writeOperationPolicyLiteral(&b, operation)
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n}\n")
	return b.String(), nil
}

func writeOperationPolicyLiteral(b *strings.Builder, operation *OperationDeclaration) {
	if len(operation.Permissions) > 0 {
		b.WriteString(", Permissions: []authz.PermissionKey{")
		for _, permission := range operation.Permissions {
			fmt.Fprintf(b, "%q,", permission)
		}
		b.WriteString("}")
	}
	if operation.PermissionMode == "any" {
		b.WriteString(", Mode: authz.PermissionAny")
	} else {
		b.WriteString(", Mode: authz.PermissionAll")
	}
	if operation.TenantRequired {
		b.WriteString(", TenantRequired: true")
	}
	if len(operation.Authentication) > 0 {
		b.WriteString(", Authentication: []string{")
		for _, authentication := range operation.Authentication {
			fmt.Fprintf(b, "%q,", authentication)
		}
		b.WriteString("}")
	}
}

func servicePermissionValues(service Service) []string {
	permissionSet := map[string]struct{}{}
	for _, method := range service.Methods {
		for _, permission := range method.Operation.Permissions {
			if permission = strings.TrimSpace(permission); permission != "" {
				permissionSet[permission] = struct{}{}
			}
		}
	}
	values := make([]string, 0, len(permissionSet))
	for permission := range permissionSet {
		values = append(values, permission)
	}
	sort.Strings(values)
	return values
}

func renderDomainPolicy(services []Service, namings map[string]serviceCodegenNaming) (string, error) {
	permissionSet := map[string]struct{}{}
	for _, service := range services {
		for _, permission := range servicePermissionValues(service) {
			permissionSet[permission] = struct{}{}
		}
	}
	permissions := make([]string, 0, len(permissionSet))
	for permission := range permissionSet {
		permissions = append(permissions, permission)
	}
	sort.Strings(permissions)

	var b strings.Builder
	b.WriteString(GeneratedApplicationMarker + "\n\npackage policy\n\n")
	b.WriteString("import \"yunka.io/gateway/authz\"\n\n")
	b.WriteString("func Permissions() []authz.PermissionKey {\n\treturn []authz.PermissionKey{")
	for _, permission := range permissions {
		fmt.Fprintf(&b, "%q,", permission)
	}
	b.WriteString("}\n}\n")
	b.WriteString("\nfunc Resolver() authz.StaticResolver {\n\tpolicies := map[string]authz.Policy{}\n")
	for _, service := range services {
		naming, ok := namings[service.FullName]
		if !ok {
			return "", fmt.Errorf("contract application codegen: missing naming for service %s", service.FullName)
		}
		fmt.Fprintf(&b, "\tfor key, value := range %s() { policies[key] = value }\n", naming.PoliciesFunc)
	}
	b.WriteString("\treturn authz.NewStaticResolver(policies)\n}\n")
	return b.String(), nil
}

func renderRPCAdapter(service Service, packages []protoGoPackage, rootImport string, naming serviceCodegenNaming) (string, error) {
	imports := newImportSet()
	servicePackage, err := resolveServicePackage(service, packages, imports)
	if err != nil {
		return "", err
	}
	applicationImport := rootImport + "/" + service.Domain + "/application"
	applicationAlias := imports.add(applicationImport, "application")
	imports.add("google.golang.org/grpc", "grpc")
	var methods strings.Builder
	for _, method := range service.Methods {
		request, err := resolveGoType(method.Request, packages, imports)
		if err != nil {
			return "", err
		}
		response, err := resolveGoType(method.Response, packages, imports)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&methods, "func (server *%s) %s(ctx context.Context, request *%s.%s) (*%s.%s, error) { return server.application.%s(ctx, request) }\n\n", naming.RPCServer, method.Name, request.Alias, request.Type, response.Alias, response.Type, method.Name)
	}
	var b strings.Builder
	b.WriteString(GeneratedApplicationMarker + "\n\npackage rpc\n\nimport (\n\t\"context\"\n")
	b.WriteString(imports.render())
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "type %s struct {\n\t%s.Unimplemented%sServer\n\tapplication %s.%s\n}\n\n", naming.RPCServer, servicePackage.Alias, service.Name, applicationAlias, naming.ApplicationInterface)
	fmt.Fprintf(&b, "func %s(registrar grpc.ServiceRegistrar, application %s.%s) {\n\t%s.Register%sServer(registrar, &%s{application: application})\n}\n\n", naming.RPCRegister, applicationAlias, naming.ApplicationInterface, servicePackage.Alias, service.Name, naming.RPCServer)
	b.WriteString(methods.String())
	return b.String(), nil
}

func renderRESTAdapter(service Service, packages []protoGoPackage, messages map[string]Message, rootImport string, naming serviceCodegenNaming) (string, error) {
	imports := newImportSet()
	applicationAlias := imports.add(rootImport+"/"+service.Domain+"/application", "application")
	imports.add("yunka.io/gateway/authz", "authz")
	imports.add("google.golang.org/protobuf/encoding/protojson", "protojson")

	var handlers strings.Builder
	var registrations strings.Builder
	bindingCount := 0
	for _, method := range service.Methods {
		requestRef, err := resolveGoType(method.Request, packages, imports)
		if err != nil {
			return "", err
		}
		requestMessage := messages[method.Request]
		for index, binding := range method.HTTP {
			bindingCount++
			handlerName := "handle" + method.Name
			if len(method.HTTP) > 1 {
				handlerName += strconv.Itoa(index + 1)
			}
			pattern := strings.ToUpper(binding.Method) + " " + binding.Path
			fmt.Fprintf(&registrations, "\tmux.HandleFunc(%q, handler.%s)\n", pattern, handlerName)
			fmt.Fprintf(&handlers, "func (handler *%s) %s(writer http.ResponseWriter, request *http.Request) {\n", naming.RESTHandler, handlerName)
			fmt.Fprintf(&handlers, "\twire := &%s.%s{}\n", requestRef.Alias, requestRef.Type)
			pathFields, _ := simplePathFields(binding.Path)
			if binding.Body == "*" {
				imports.add("io", "io")
				handlers.WriteString("\tbody, err := io.ReadAll(request.Body)\n\tif err != nil { http.Error(writer, \"invalid request body\", http.StatusBadRequest); return }\n\tif len(body) > 0 { if err := protojson.Unmarshal(body, wire); err != nil { http.Error(writer, \"invalid request body\", http.StatusBadRequest); return } }\n")
			} else {
				pathSet := make(map[string]struct{}, len(pathFields))
				for _, value := range pathFields {
					pathSet[value] = struct{}{}
				}
				for _, field := range requestMessage.Fields {
					if _, pathField := pathSet[field.Name]; pathField || field.Repeated || field.Map || field.Kind == "message" || field.Kind == "enum" {
						continue
					}
					queryExpr := "request.URL.Query().Get(" + strconv.Quote(field.Name) + ")"
					fmt.Fprintf(&handlers, "\tif raw := %s; raw != \"\" {\n", queryExpr)
					if scalarAssignmentNeedsStrconv(field) {
						imports.add("strconv", "strconv")
					}
					if err := writeScalarAssignment(&handlers, "wire", field, "raw", false); err != nil {
						return "", err
					}
					handlers.WriteString("\t}\n")
				}
			}
			for _, fieldName := range pathFields {
				field, ok := findMessageField(requestMessage, fieldName)
				if !ok {
					return "", fmt.Errorf("contract application codegen: %s path field %q not found in %s", method.FullName, fieldName, method.Request)
				}
				if scalarAssignmentNeedsStrconv(field) {
					imports.add("strconv", "strconv")
				}
				if err := writeScalarAssignment(&handlers, "wire", field, "request.PathValue("+strconv.Quote(fieldName)+")", true); err != nil {
					return "", fmt.Errorf("contract application codegen: %s: %w", method.FullName, err)
				}
			}
			fullMethod := "/" + strings.TrimPrefix(service.FullName, ".") + "/" + method.Name
			fmt.Fprintf(&handlers, "\tsecured, err := handler.runtime.Prepare(request.Context(), %q, wire)\n", fullMethod)
			fmt.Fprintf(&handlers, "\tif err != nil { %s(writer, err); return }\n", naming.SecurityError)
			fmt.Fprintf(&handlers, "\toutput, err := handler.application.%s(secured, wire)\n", method.Name)
			handlers.WriteString("\tif err != nil { http.Error(writer, \"application request failed\", http.StatusBadRequest); return }\n\tpayload, err := protojson.Marshal(output)\n\tif err != nil { http.Error(writer, \"response encoding failed\", http.StatusInternalServerError); return }\n\twriter.Header().Set(\"Content-Type\", \"application/json\")\n\t_, _ = writer.Write(payload)\n}\n\n")
		}
	}
	if bindingCount == 0 {
		return GeneratedApplicationMarker + "\n\npackage rest\n", nil
	}

	var b strings.Builder
	b.WriteString(GeneratedApplicationMarker + "\n\npackage rest\n\nimport (\n\t\"errors\"\n\t\"net/http\"\n")
	b.WriteString(imports.render())
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "type %s struct { application %s.%s; runtime authz.OperationRuntime }\n\n", naming.RESTHandler, applicationAlias, naming.ApplicationInterface)
	fmt.Fprintf(&b, "func %s(mux *http.ServeMux, application %s.%s, runtime authz.OperationRuntime) error {\n", naming.RESTRegister, applicationAlias, naming.ApplicationInterface)
	b.WriteString("\tif mux == nil { return errors.New(\"contract REST adapter: mux is required\") }\n")
	b.WriteString("\tif application == nil { return errors.New(\"contract REST adapter: application is required\") }\n")
	b.WriteString("\tif runtime == nil { return errors.New(\"contract REST adapter: operation runtime is required\") }\n")
	fmt.Fprintf(&b, "\thandler := &%s{application: application, runtime: runtime}\n", naming.RESTHandler)
	b.WriteString(registrations.String())
	b.WriteString("\treturn nil\n}\n\n")
	fmt.Fprintf(&b, "func %s(writer http.ResponseWriter, err error) {\n", naming.SecurityError)
	b.WriteString("\tif !authz.IsDenied(err) { http.Error(writer, \"authorization unavailable\", http.StatusInternalServerError); return }\n")
	b.WriteString("\tstatusCode := http.StatusForbidden\n\tvar denied *authz.DeniedError\n")
	b.WriteString("\tif errors.As(err, &denied) && (denied.Decision.Reason == authz.ReasonUnauthenticated || denied.Decision.Reason == authz.ReasonAuthenticationMethod) { statusCode = http.StatusUnauthorized }\n")
	b.WriteString("\thttp.Error(writer, http.StatusText(statusCode), statusCode)\n}\n\n")
	b.WriteString(handlers.String())
	return b.String(), nil
}

func (policy *AuthorizationPolicy) ProtectedLike() bool {
	return policy != nil && (len(policy.Authentication) > 0 || len(policy.Permissions) > 0 || policy.TenantRequired)
}

func scalarAssignmentNeedsStrconv(field Field) bool {
	switch field.Type {
	case "bool", "int32", "int64", "sint32", "sint64", "sfixed32", "sfixed64", "uint32", "uint64", "fixed32", "fixed64", "float", "double":
		return true
	default:
		return false
	}
}

func writeScalarAssignment(builder *strings.Builder, receiver string, field Field, rawExpression string, path bool) error {
	goName := protoGoFieldName(field.Name)
	badRequest := "http.Error(writer, \"invalid request parameter\", http.StatusBadRequest); return"
	switch field.Type {
	case "string":
		fmt.Fprintf(builder, "\t%s.%s = %s\n", receiver, goName, rawExpression)
	case "bool":
		fmt.Fprintf(builder, "\tparsed, err := strconv.ParseBool(%s); if err != nil { %s }; %s.%s = parsed\n", rawExpression, badRequest, receiver, goName)
	case "int32", "int64", "sint32", "sint64", "sfixed32", "sfixed64":
		bits := 64
		cast := "int64"
		if strings.Contains(field.Type, "32") {
			bits, cast = 32, "int32"
		}
		fmt.Fprintf(builder, "\tparsed, err := strconv.ParseInt(%s, 10, %d); if err != nil { %s }; %s.%s = %s(parsed)\n", rawExpression, bits, badRequest, receiver, goName, cast)
	case "uint32", "uint64", "fixed32", "fixed64":
		bits := 64
		cast := "uint64"
		if strings.Contains(field.Type, "32") {
			bits, cast = 32, "uint32"
		}
		fmt.Fprintf(builder, "\tparsed, err := strconv.ParseUint(%s, 10, %d); if err != nil { %s }; %s.%s = %s(parsed)\n", rawExpression, bits, badRequest, receiver, goName, cast)
	case "float", "double":
		bits := 64
		cast := "float64"
		if field.Type == "float" {
			bits, cast = 32, "float32"
		}
		fmt.Fprintf(builder, "\tparsed, err := strconv.ParseFloat(%s, %d); if err != nil { %s }; %s.%s = %s(parsed)\n", rawExpression, bits, badRequest, receiver, goName, cast)
	default:
		location := "query"
		if path {
			location = "path"
		}
		return fmt.Errorf("%s field %s type %s requires handwritten mapping", location, field.Name, field.Type)
	}
	return nil
}

func findMessageField(message Message, name string) (Field, bool) {
	for _, field := range message.Fields {
		if field.Name == name || field.JSONName == name {
			return field, true
		}
	}
	return Field{}, false
}

func simplePathFields(path string) ([]string, error) {
	var fields []string
	for {
		start := strings.IndexByte(path, '{')
		if start < 0 {
			break
		}
		end := strings.IndexByte(path[start+1:], '}')
		if end < 0 {
			return nil, fmt.Errorf("HTTP path %q has unmatched '{'", path)
		}
		end += start + 1
		name := path[start+1 : end]
		if name == "" || strings.ContainsAny(name, "=/*") {
			return nil, fmt.Errorf("HTTP path template %q requires handwritten routing", name)
		}
		fields = append(fields, name)
		path = path[end+1:]
	}
	return fields, nil
}

type importSet struct {
	byPath map[string]string
	used   map[string]string
}

func newImportSet() *importSet {
	return &importSet{byPath: map[string]string{}, used: map[string]string{}}
}

func (set *importSet) add(path, preferred string) string {
	if alias, ok := set.byPath[path]; ok {
		return alias
	}
	alias := sanitizeGoIdentifier(preferred)
	if alias == "" {
		alias = sanitizeGoIdentifier(filepath.Base(path))
	}
	base := alias
	for index := 2; ; index++ {
		if owner, exists := set.used[alias]; !exists || owner == path {
			break
		}
		alias = base + strconv.Itoa(index)
	}
	set.byPath[path] = alias
	set.used[alias] = path
	return alias
}

func (set *importSet) render() string {
	paths := make([]string, 0, len(set.byPath))
	for path := range set.byPath {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	var b strings.Builder
	for _, path := range paths {
		fmt.Fprintf(&b, "\t%s %q\n", set.byPath[path], path)
	}
	return b.String()
}

func buildProtoGoPackages(manifest Manifest) ([]protoGoPackage, error) {
	byProto := map[string]protoGoPackage{}
	for _, file := range manifest.Files {
		if file.Package == "" || file.GoPackage == "" {
			continue
		}
		path, alias := splitGoPackage(file.GoPackage)
		item := protoGoPackage{ProtoPackage: file.Package, ImportPath: path, Alias: alias}
		if current, ok := byProto[file.Package]; ok && (current.ImportPath != item.ImportPath || current.Alias != item.Alias) {
			return nil, fmt.Errorf("contract application codegen: proto package %s maps to multiple Go packages", file.Package)
		}
		byProto[file.Package] = item
	}
	result := make([]protoGoPackage, 0, len(byProto))
	for _, item := range byProto {
		result = append(result, item)
	}
	sort.Slice(result, func(i, j int) bool { return len(result[i].ProtoPackage) > len(result[j].ProtoPackage) })
	return result, nil
}

func resolveServicePackage(service Service, packages []protoGoPackage, imports *importSet) (goTypeRef, error) {
	full := strings.TrimSuffix(service.FullName, "."+service.Name)
	for _, item := range packages {
		if item.ProtoPackage == full {
			alias := imports.add(item.ImportPath, item.Alias)
			return goTypeRef{ImportPath: item.ImportPath, Alias: alias, Type: service.Name}, nil
		}
	}
	return goTypeRef{}, fmt.Errorf("contract application codegen: no Go package for service %s", service.FullName)
}

func resolveGoType(fullName string, packages []protoGoPackage, imports *importSet) (goTypeRef, error) {
	if known, ok := knownGoWellKnownType(fullName); ok {
		known.Alias = imports.add(known.ImportPath, known.Alias)
		return known, nil
	}
	for _, item := range packages {
		prefix := item.ProtoPackage + "."
		if strings.HasPrefix(fullName, prefix) {
			typeName := strings.ReplaceAll(strings.TrimPrefix(fullName, prefix), ".", "_")
			alias := imports.add(item.ImportPath, item.Alias)
			return goTypeRef{ImportPath: item.ImportPath, Alias: alias, Type: typeName}, nil
		}
	}
	return goTypeRef{}, fmt.Errorf("contract application codegen: no Go package for protobuf type %s", fullName)
}

func knownGoWellKnownType(fullName string) (goTypeRef, bool) {
	switch fullName {
	case "google.protobuf.Empty":
		return goTypeRef{ImportPath: "google.golang.org/protobuf/types/known/emptypb", Alias: "emptypb", Type: "Empty"}, true
	case "google.protobuf.Timestamp":
		return goTypeRef{ImportPath: "google.golang.org/protobuf/types/known/timestamppb", Alias: "timestamppb", Type: "Timestamp"}, true
	case "google.protobuf.Duration":
		return goTypeRef{ImportPath: "google.golang.org/protobuf/types/known/durationpb", Alias: "durationpb", Type: "Duration"}, true
	case "google.protobuf.Any":
		return goTypeRef{ImportPath: "google.golang.org/protobuf/types/known/anypb", Alias: "anypb", Type: "Any"}, true
	default:
		return goTypeRef{}, false
	}
}

func splitGoPackage(value string) (string, string) {
	path, alias, found := strings.Cut(strings.TrimSpace(value), ";")
	if !found || strings.TrimSpace(alias) == "" {
		alias = filepath.Base(path)
	}
	return strings.TrimSpace(path), sanitizeGoIdentifier(alias)
}

func protoGoFieldName(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	var b strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	return b.String()
}

func sanitizeGoIdentifier(value string) string {
	var b strings.Builder
	for index, current := range strings.TrimSpace(value) {
		if unicode.IsLetter(current) || current == '_' || (index > 0 && unicode.IsDigit(current)) {
			b.WriteRune(current)
		}
	}
	return b.String()
}

func safeFileName(value string) string {
	value = strings.TrimSpace(value)
	var b strings.Builder
	for _, current := range value {
		if unicode.IsLetter(current) || unicode.IsDigit(current) {
			b.WriteRune(unicode.ToLower(current))
			continue
		}
		if b.Len() > 0 && !strings.HasSuffix(b.String(), "_") {
			b.WriteByte('_')
		}
	}
	return strings.Trim(b.String(), "_")
}
