package contract

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"yunka.io/pkg/assemblyplan"
)

const (
	GeneratedAssemblyMarker = "// Code generated by yunka assembly compiler; DO NOT EDIT."
	AssemblyCodePath         = "assembly/zz_yunka_assembly_gen.go"
)

type AssemblyCodeOptions struct {
	RootImport string
}

type GeneratedAssemblyFile struct {
	Path    string
	Content []byte
}

func RenderAssemblyCode(manifest Manifest, plan assemblyplan.Plan, options AssemblyCodeOptions) ([]GeneratedAssemblyFile, error) {
	manifest.Normalize()
	plan = assemblyplan.Normalize(plan)
	if err := assemblyplan.Validate(plan); err != nil {
		return nil, fmt.Errorf("contract assembly codegen: assembly plan: %w", err)
	}
	rootImport := strings.TrimRight(strings.TrimSpace(options.RootImport), "/")
	if rootImport == "" && len(plan.Applications) > 0 {
		return nil, fmt.Errorf("contract assembly codegen: root import is required")
	}
	if err := verifyAssemblyPlanAgainstManifest(manifest, plan); err != nil {
		return nil, err
	}
	services, domainCounts, err := assemblyServiceIndex(manifest, plan)
	if err != nil {
		return nil, err
	}
	order, err := assemblyApplicationOrder(plan)
	if err != nil {
		return nil, err
	}
	source, err := renderAssemblyRoot(plan, rootImport, services, domainCounts, order)
	if err != nil {
		return nil, err
	}
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("contract assembly codegen: format %s: %w\n%s", AssemblyCodePath, err, source)
	}
	return []GeneratedAssemblyFile{{Path: AssemblyCodePath, Content: formatted}}, nil
}

func verifyAssemblyPlanAgainstManifest(manifest Manifest, plan assemblyplan.Plan) error {
	operations, err := CompileOperationPlans(manifest)
	if err != nil {
		return fmt.Errorf("contract assembly codegen: canonical operation plan: %w", err)
	}
	modules := assemblyModuleInputs(plan)
	canonical, err := CompileAssemblyPlan(manifest, operations, modules)
	if err != nil {
		return fmt.Errorf("contract assembly codegen: canonical assembly plan: %w", err)
	}
	want, err := assemblyplan.Digest(canonical)
	if err != nil {
		return err
	}
	got, err := assemblyplan.Digest(plan)
	if err != nil {
		return err
	}
	if want != got {
		return fmt.Errorf("contract assembly codegen: assembly plan does not match canonical manifest/module facts: got=%s want=%s", got, want)
	}
	return nil
}

func assemblyModuleInputs(plan assemblyplan.Plan) []assemblyplan.ModuleInput {
	dependencies := make(map[string][]string, len(plan.Modules))
	for _, edge := range plan.ModuleDependencies {
		dependencies[edge.From] = append(dependencies[edge.From], edge.To)
	}
	result := make([]assemblyplan.ModuleInput, 0, len(plan.Modules))
	for _, module := range plan.Modules {
		result = append(result, assemblyplan.ModuleInput{
			Name:         module.Name,
			Version:      module.Version,
			DependsOn:    append([]string(nil), dependencies[module.Name]...),
			Requirements: module.Requirements,
			Evidence:     module.Evidence,
		})
	}
	return result
}

func assemblyServiceIndex(manifest Manifest, plan assemblyplan.Plan) (map[string]Service, map[string]int, error) {
	services := make(map[string]Service)
	domainCounts := make(map[string]int)
	for _, service := range manifest.Services {
		if service.Application == nil {
			continue
		}
		id := strings.TrimSpace(service.Domain) + "/" + strings.TrimSpace(service.Application.Name)
		if _, duplicate := services[id]; duplicate {
			return nil, nil, fmt.Errorf("contract assembly codegen: duplicate application service %s", id)
		}
		services[id] = service
		domainCounts[service.Domain]++
	}
	for _, application := range plan.Applications {
		if _, ok := services[application.ID]; !ok {
			return nil, nil, fmt.Errorf("contract assembly codegen: application %s has no canonical service declaration", application.ID)
		}
	}
	return services, domainCounts, nil
}

func assemblyApplicationOrder(plan assemblyplan.Plan) ([]string, error) {
	indegree := make(map[string]int, len(plan.Applications))
	dependents := make(map[string][]string, len(plan.Applications))
	for _, application := range plan.Applications {
		indegree[application.ID] = 0
	}
	for _, edge := range plan.ApplicationDependencies {
		indegree[edge.From]++
		dependents[edge.To] = append(dependents[edge.To], edge.From)
	}
	for id := range dependents {
		sort.Strings(dependents[id])
	}
	ready := make([]string, 0)
	for id, degree := range indegree {
		if degree == 0 {
			ready = append(ready, id)
		}
	}
	sort.Strings(ready)
	order := make([]string, 0, len(indegree))
	for len(ready) > 0 {
		id := ready[0]
		ready = ready[1:]
		order = append(order, id)
		for _, dependent := range dependents[id] {
			indegree[dependent]--
			if indegree[dependent] == 0 {
				ready = insertAssemblyString(ready, dependent)
			}
		}
	}
	if len(order) != len(indegree) {
		return nil, fmt.Errorf("contract assembly codegen: application dependency graph is not acyclic")
	}
	return order, nil
}

func insertAssemblyString(values []string, value string) []string {
	index := sort.SearchStrings(values, value)
	values = append(values, "")
	copy(values[index+1:], values[index:])
	values[index] = value
	return values
}

func renderAssemblyRoot(plan assemblyplan.Plan, rootImport string, services map[string]Service, domainCounts map[string]int, order []string) (string, error) {
	imports := newImportSet()
	imports.add("errors", "errors")
	if len(plan.Applications) > 0 {
		imports.add("fmt", "fmt")
	}
	imports.add("yunka.io/framework/core/modulecatalog", "modulecatalog")
	imports.add("yunka.io/framework/kernel", "kernel")
	imports.add("yunka.io/framework/operation", "operation")
	imports.add("yunka.io/framework/platform", "platform")

	type appInfo struct {
		ID           string
		Symbol       string
		Package      string
		Interface    string
		Service      Service
		Naming       serviceCodegenNaming
		Dependencies []string
		HTTP         bool
		RPC          bool
	}
	infos := make(map[string]appInfo, len(plan.Applications))
	dependencyMap := make(map[string][]string)
	for _, edge := range plan.ApplicationDependencies {
		dependencyMap[edge.From] = append(dependencyMap[edge.From], edge.To)
	}
	transportMap := make(map[string]map[string]bool)
	for _, operation := range plan.Operations {
		if transportMap[operation.Application] == nil {
			transportMap[operation.Application] = map[string]bool{}
		}
		for _, binding := range operation.Bindings {
			transportMap[operation.Application][binding.Transport] = true
		}
	}
	seenSymbols := map[string]string{}
	for _, application := range plan.Applications {
		service := services[application.ID]
		naming := namingForService(service, domainCounts[service.Domain] > 1)
		symbol := exportedApplicationSymbol(strings.ReplaceAll(application.ID, "/", "_"))
		if symbol == "" {
			return "", fmt.Errorf("contract assembly codegen: application %s has no generated symbol", application.ID)
		}
		if owner, duplicate := seenSymbols[symbol]; duplicate && owner != application.ID {
			return "", fmt.Errorf("contract assembly codegen: applications %s and %s collapse to symbol %s", owner, application.ID, symbol)
		}
		seenSymbols[symbol] = application.ID
		alias := imports.add(rootImport+"/"+service.Domain+"/application", safeFileName(service.Domain)+"application")
		deps := append([]string(nil), dependencyMap[application.ID]...)
		sort.Strings(deps)
		infos[application.ID] = appInfo{
			ID: application.ID, Symbol: symbol, Package: alias, Interface: naming.ApplicationInterface,
			Service: service, Naming: naming, Dependencies: deps,
			HTTP: transportMap[application.ID]["http"], RPC: transportMap[application.ID]["rpc"],
		}
	}

	hasHTTP, hasRPC := false, false
	for _, info := range infos {
		hasHTTP = hasHTTP || info.HTTP
		hasRPC = hasRPC || info.RPC
	}
	if hasHTTP {
		imports.add("net/http", "http")
	}
	if hasRPC {
		imports.add("google.golang.org/grpc", "grpc")
	}

	var b strings.Builder
	b.WriteString(GeneratedAssemblyMarker + "\n\npackage assembly\n\nimport (\n")
	b.WriteString(imports.render())
	b.WriteString(")\n\n")

	digest, err := assemblyplan.Digest(plan)
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&b, "const AssemblyPlanDigest = %q\n\n", digest)

	applicationIDs := make([]string, 0, len(infos))
	for id := range infos {
		applicationIDs = append(applicationIDs, id)
	}
	sort.Strings(applicationIDs)

	for _, id := range applicationIDs {
		info := infos[id]
		fmt.Fprintf(&b, "type %sDependencies struct {\n", info.Symbol)
		for _, dependency := range info.Dependencies {
			field := exportedApplicationSymbol(strings.ReplaceAll(dependency, "/", "_"))
			fmt.Fprintf(&b, "\t%s %s.%sChildCapability\n", field, info.Package, field)
		}
		b.WriteString("}\n\n")
	}

	b.WriteString("type ApplicationFactories interface {\n")
	for _, id := range applicationIDs {
		info := infos[id]
		fmt.Fprintf(&b, "\tBuild%s(%sDependencies) (%s.%s, error)\n", info.Symbol, info.Symbol, info.Package, info.Interface)
	}
	b.WriteString("}\n\n")

	b.WriteString("type Applications struct {\n")
	for _, id := range applicationIDs {
		info := infos[id]
		fmt.Fprintf(&b, "\t%s %s.%s\n", info.Symbol, info.Package, info.Interface)
	}
	b.WriteString("}\n\n")

	b.WriteString("func BuildApplications(factories ApplicationFactories, executor operation.Executor) (Applications, error) {\n")
	b.WriteString("\tif factories == nil { return Applications{}, errors.New(\"yunka assembly: application factories are required\") }\n")
	if len(plan.ApplicationDependencies) > 0 {
		b.WriteString("\tif executor == nil { return Applications{}, errors.New(\"yunka assembly: operation executor is required for child capabilities\") }\n")
	}
	b.WriteString("\tvar applications Applications\n\tvar err error\n")
	for _, id := range order {
		info := infos[id]
		for _, dependency := range info.Dependencies {
			depInfo := infos[dependency]
			field := depInfo.Symbol
			local := lowerFirstIdentifier(info.Symbol + field + "Capability")
			fmt.Fprintf(&b, "\t%s, err := %s.New%sChildCapability(applications.%s, executor)\n", local, info.Package, field, field)
			fmt.Fprintf(&b, "\tif err != nil { return Applications{}, fmt.Errorf(%q, err) }\n", "yunka assembly: build "+id+" dependency "+dependency+": %w")
		}
		fmt.Fprintf(&b, "\tapplications.%s, err = factories.Build%s(%sDependencies{", info.Symbol, info.Symbol, info.Symbol)
		for index, dependency := range info.Dependencies {
			if index > 0 {
				b.WriteString(", ")
			}
			depInfo := infos[dependency]
			local := lowerFirstIdentifier(info.Symbol + depInfo.Symbol + "Capability")
			fmt.Fprintf(&b, "%s: %s", depInfo.Symbol, local)
		}
		b.WriteString("})\n")
		fmt.Fprintf(&b, "\tif err != nil { return Applications{}, fmt.Errorf(%q, err) }\n", "yunka assembly: build application "+id+": %w")
		fmt.Fprintf(&b, "\tif applications.%s == nil { return Applications{}, errors.New(%q) }\n", info.Symbol, "yunka assembly: application factory returned nil for "+id)
	}
	b.WriteString("\treturn applications, nil\n}\n\n")

	b.WriteString("type KernelDependencies struct {\n\tPlatform *platform.Provider\n\tCatalog *modulecatalog.Catalog\n}\n\n")
	b.WriteString("func KernelOptions(dependencies KernelDependencies) kernel.Options {\n\treturn kernel.Options{Platform: dependencies.Platform, Catalog: dependencies.Catalog}\n}\n\n")
	renderExpectedModuleRequirements(&b, plan)

	b.WriteString("type TransportBindings struct {\n")
	if hasHTTP {
		b.WriteString("\tHTTP *http.ServeMux\n")
	}
	if hasRPC {
		b.WriteString("\tRPC grpc.ServiceRegistrar\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("func RegisterTransports(bindings TransportBindings, applications Applications, executor operation.Executor) error {\n")
	if hasHTTP || hasRPC {
		b.WriteString("\tif executor == nil { return errors.New(\"yunka assembly: operation executor is required for transport registration\") }\n")
	}
	if hasHTTP {
		b.WriteString("\tif bindings.HTTP == nil { return errors.New(\"yunka assembly: HTTP mux is required\") }\n")
	}
	if hasRPC {
		b.WriteString("\tif bindings.RPC == nil { return errors.New(\"yunka assembly: gRPC registrar is required\") }\n")
	}
	for _, id := range applicationIDs {
		info := infos[id]
		if !info.HTTP && !info.RPC {
			continue
		}
		fmt.Fprintf(&b, "\tif applications.%s == nil { return errors.New(%q) }\n", info.Symbol, "yunka assembly: application "+id+" is required for transport registration")
		if info.HTTP {
			alias := imports.add(rootImport+"/"+info.Service.Domain+"/transport/rest", safeFileName(info.Service.Domain)+"rest")
			fmt.Fprintf(&b, "\tif err := %s.%s(bindings.HTTP, applications.%s, executor); err != nil { return fmt.Errorf(%q, err) }\n", alias, c9RegisterName(info.Naming), info.Symbol, "yunka assembly: register HTTP "+id+": %w")
		}
		if info.RPC {
			alias := imports.add(rootImport+"/"+info.Service.Domain+"/transport/rpc", safeFileName(info.Service.Domain)+"rpc")
			fmt.Fprintf(&b, "\tif err := %s.%s(bindings.RPC, applications.%s, executor); err != nil { return fmt.Errorf(%q, err) }\n", alias, c9RegisterName(info.Naming), info.Symbol, "yunka assembly: register gRPC "+id+": %w")
		}
	}
	b.WriteString("\treturn nil\n}\n")

	needle := "import (\n" + imports.render() + ")\n\n"
	source := b.String()
	firstStart := strings.Index(source, "import (\n")
	if firstStart < 0 {
		return "", fmt.Errorf("contract assembly codegen: generated import block missing")
	}
	firstEnd := strings.Index(source[firstStart:], ")\n\n")
	if firstEnd < 0 {
		return "", fmt.Errorf("contract assembly codegen: generated import block is malformed")
	}
	firstEnd += firstStart + len(")\n\n")
	return source[:firstStart] + needle + source[firstEnd:], nil
}

func renderExpectedModuleRequirements(b *strings.Builder, plan assemblyplan.Plan) {
	modules := make([]string, 0, len(plan.Modules))
	configs := make([]assemblyplan.Requirement, 0)
	databaseSet := map[string]struct{}{}
	rpcSet := map[string]struct{}{}
	logger := false
	eventBus := false
	for _, module := range plan.Modules {
		modules = append(modules, module.Name)
	}
	for _, requirement := range plan.Requirements {
		switch requirement.Kind {
		case "config":
			configs = append(configs, requirement)
		case "database":
			databaseSet[requirement.Name] = struct{}{}
		case "rpc":
			rpcSet[requirement.Name] = struct{}{}
		case "logger":
			logger = true
		case "event_bus":
			eventBus = true
		}
	}
	sort.Strings(modules)
	sort.Slice(configs, func(i, j int) bool {
		if configs[i].Module != configs[j].Module {
			return configs[i].Module < configs[j].Module
		}
		return configs[i].Name < configs[j].Name
	})
	databases := make([]string, 0, len(databaseSet))
	for name := range databaseSet {
		databases = append(databases, name)
	}
	sort.Strings(databases)
	rpcs := make([]string, 0, len(rpcSet))
	for name := range rpcSet {
		rpcs = append(rpcs, name)
	}
	sort.Strings(rpcs)

	b.WriteString("func ExpectedModuleRequirements() modulecatalog.RequirementSet {\n\treturn modulecatalog.RequirementSet{\n")
	b.WriteString("\t\tModules: []string{")
	for _, module := range modules {
		fmt.Fprintf(b, "%q,", module)
	}
	b.WriteString("},\n")
	if len(configs) > 0 {
		b.WriteString("\t\tConfigs: []modulecatalog.ConfigRequirement{")
		for _, config := range configs {
			fmt.Fprintf(b, "{Module:%q, Key:%q},", config.Module, config.Name)
		}
		b.WriteString("},\n")
	}
	if logger {
		b.WriteString("\t\tLogger: true,\n")
	}
	if len(databases) > 0 {
		b.WriteString("\t\tDatabases: []modulecatalog.DatabaseRequirement{")
		for _, database := range databases {
			fmt.Fprintf(b, "{Name:%q},", database)
		}
		b.WriteString("},\n")
	}
	if eventBus {
		b.WriteString("\t\tEventBus: true,\n")
	}
	if len(rpcs) > 0 {
		b.WriteString("\t\tRPC: []modulecatalog.RPCRequirement{")
		for _, rpc := range rpcs {
			fmt.Fprintf(b, "{Name:%q},", rpc)
		}
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n}\n\n")
}

func WriteAssemblyCode(root string, files []GeneratedAssemblyFile) error {
	expected, err := assemblyFileMap(files)
	if err != nil {
		return err
	}
	root = strings.TrimSpace(root)
	if root == "" {
		if len(expected) == 0 {
			return nil
		}
		return fmt.Errorf("contract assembly codegen: output root is required")
	}
	for relative, content := range expected {
		target, err := containedApplicationPath(root, relative)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := writeFileAtomic(target, content, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func CheckAssemblyCode(root string, files []GeneratedAssemblyFile) ([]Drift, error) {
	expected, err := assemblyFileMap(files)
	if err != nil {
		return nil, err
	}
	root = strings.TrimSpace(root)
	if root == "" {
		if len(expected) == 0 {
			return nil, nil
		}
		return nil, fmt.Errorf("contract assembly codegen: output root is required")
	}
	var drift []Drift
	for relative, want := range expected {
		target, err := containedApplicationPath(root, relative)
		if err != nil {
			return nil, err
		}
		got, err := os.ReadFile(target)
		if err != nil {
			if os.IsNotExist(err) {
				drift = append(drift, Drift{File: relative, Reason: "generated assembly artifact is missing", Missing: true})
				continue
			}
			return nil, err
		}
		if !bytes.Equal(got, want) {
			drift = append(drift, Drift{File: relative, Reason: "generated assembly artifact differs from AssemblyPlan"})
		}
	}
	sort.Slice(drift, func(i, j int) bool { return drift[i].File < drift[j].File })
	return drift, nil
}

func assemblyFileMap(files []GeneratedAssemblyFile) (map[string][]byte, error) {
	expected := make(map[string][]byte, len(files))
	for _, file := range files {
		relative := filepath.ToSlash(filepath.Clean(strings.TrimSpace(file.Path)))
		if relative != AssemblyCodePath {
			return nil, fmt.Errorf("contract assembly codegen: unmanaged generated path %q", file.Path)
		}
		if _, duplicate := expected[relative]; duplicate {
			return nil, fmt.Errorf("contract assembly codegen: duplicate generated path %q", relative)
		}
		if !bytes.HasPrefix(file.Content, []byte(GeneratedAssemblyMarker)) {
			return nil, fmt.Errorf("contract assembly codegen: generated marker missing from %q", relative)
		}
		expected[relative] = append([]byte(nil), file.Content...)
	}
	return expected, nil
}
