package contract

import (
	"fmt"
	"sort"
	"strings"
	"unicode"
)

type TypeScriptOptions struct {
	Header string
}

func GenerateTypeScript(manifest Manifest, options TypeScriptOptions) ([]byte, error) {
	manifest.Normalize()
	var builder strings.Builder
	if options.Header == "" {
		options.Header = "Code generated by yunka contract; DO NOT EDIT."
	}
	builder.WriteString("// ")
	builder.WriteString(options.Header)
	builder.WriteString("\n\n")
	builder.WriteString("export interface HttpBinding {\n  method: string;\n  path: string;\n  body?: string;\n  responseBody?: string;\n}\n\n")
	builder.WriteString("export interface RpcOperation {\n  fullName: string;\n  rpcPath: string;\n  requestType: string;\n  responseType: string;\n  http?: readonly HttpBinding[];\n}\n\n")
	builder.WriteString("export interface RpcTransport {\n  call<Request, Response>(operation: RpcOperation, request: Request): Promise<Response>;\n}\n\n")

	for _, enum := range manifest.Enums {
		builder.WriteString("export type ")
		builder.WriteString(tsTypeName(enum.FullName))
		builder.WriteString(" = ")
		if len(enum.Values) == 0 {
			builder.WriteString("never")
		} else {
			for i, value := range enum.Values {
				if i > 0 {
					builder.WriteString(" | ")
				}
				builder.WriteString(fmt.Sprintf("%q", value.Name))
			}
		}
		builder.WriteString(";\n\n")
	}
	for _, message := range manifest.Messages {
		builder.WriteString("export interface ")
		builder.WriteString(tsTypeName(message.FullName))
		builder.WriteString(" {\n")
		for _, field := range message.Fields {
			builder.WriteString("  ")
			builder.WriteString(tsPropertyName(field.JSONName))
			if !field.Required {
				builder.WriteString("?")
			}
			builder.WriteString(": ")
			builder.WriteString(tsFieldType(field))
			builder.WriteString(";\n")
		}
		builder.WriteString("}\n\n")
	}

	type operation struct {
		Key     string
		Service Service
		Method  Method
	}
	var operations []operation
	for _, service := range manifest.Services {
		for _, method := range service.Methods {
			operations = append(operations, operation{Key: method.FullName, Service: service, Method: method})
		}
	}
	sort.Slice(operations, func(i, j int) bool { return operations[i].Key < operations[j].Key })
	builder.WriteString("export const operations = {\n")
	for _, item := range operations {
		builder.WriteString("  ")
		builder.WriteString(fmt.Sprintf("%q", item.Key))
		builder.WriteString(": {\n")
		builder.WriteString("    fullName: ")
		builder.WriteString(fmt.Sprintf("%q", item.Method.FullName))
		builder.WriteString(",\n    rpcPath: ")
		builder.WriteString(fmt.Sprintf("%q", rpcPath(item.Service.FullName, item.Method.Name)))
		builder.WriteString(",\n    requestType: ")
		builder.WriteString(fmt.Sprintf("%q", item.Method.Request))
		builder.WriteString(",\n    responseType: ")
		builder.WriteString(fmt.Sprintf("%q", item.Method.Response))
		if len(item.Method.HTTP) > 0 {
			builder.WriteString(",\n    http: [\n")
			for _, binding := range item.Method.HTTP {
				builder.WriteString("      {")
				builder.WriteString(" method: ")
				builder.WriteString(fmt.Sprintf("%q", binding.Method))
				builder.WriteString(", path: ")
				builder.WriteString(fmt.Sprintf("%q", binding.Path))
				if binding.Body != "" {
					builder.WriteString(", body: ")
					builder.WriteString(fmt.Sprintf("%q", binding.Body))
				}
				if binding.ResponseBody != "" {
					builder.WriteString(", responseBody: ")
					builder.WriteString(fmt.Sprintf("%q", binding.ResponseBody))
				}
				builder.WriteString(" },\n")
			}
			builder.WriteString("    ]")
		}
		builder.WriteString("\n  },\n")
	}
	builder.WriteString("} as const satisfies Record<string, RpcOperation>;\n\n")

	for _, service := range manifest.Services {
		builder.WriteString("export class ")
		builder.WriteString(tsTypeName(service.FullName))
		builder.WriteString("Client {\n")
		builder.WriteString("  constructor(private readonly transport: RpcTransport) {}\n\n")
		for _, method := range service.Methods {
			builder.WriteString("  ")
			builder.WriteString(tsMethodName(method.Name))
			builder.WriteString("(request: ")
			builder.WriteString(tsTypeName(method.Request))
			builder.WriteString("): Promise<")
			builder.WriteString(tsTypeName(method.Response))
			builder.WriteString("> {\n")
			builder.WriteString("    return this.transport.call<")
			builder.WriteString(tsTypeName(method.Request))
			builder.WriteString(", ")
			builder.WriteString(tsTypeName(method.Response))
			builder.WriteString(">(operations[")
			builder.WriteString(fmt.Sprintf("%q", method.FullName))
			builder.WriteString("], request);\n  }\n\n")
		}
		builder.WriteString("}\n\n")
	}
	return []byte(strings.TrimRight(builder.String(), "\n") + "\n"), nil
}

func tsFieldType(field Field) string {
	var result string
	if field.Map {
		key := tsMapKeyType(field.MapKeyType)
		value := tsBaseType(field.MapValueType, field.MapValueKind)
		result = "Record<" + key + ", " + value + ">"
	} else {
		result = tsBaseType(field.Type, field.Kind)
	}
	if field.Repeated {
		return "readonly " + result + "[]"
	}
	return result
}

func tsBaseType(typeName, kind string) string {
	if kind == "message" || kind == "enum" {
		if known := tsWellKnown(typeName); known != "" {
			return known
		}
		return tsTypeName(typeName)
	}
	switch typeName {
	case "double", "float", "int32", "uint32", "sint32", "fixed32", "sfixed32":
		return "number"
	case "int64", "uint64", "sint64", "fixed64", "sfixed64":
		return "string"
	case "bool":
		return "boolean"
	case "string", "bytes":
		return "string"
	default:
		return "unknown"
	}
}

func tsWellKnown(typeName string) string {
	switch typeName {
	case "google.protobuf.Timestamp", "google.protobuf.Duration":
		return "string"
	case "google.protobuf.Empty":
		return "Record<string, never>"
	case "google.protobuf.Struct":
		return "Record<string, unknown>"
	case "google.protobuf.Value", "google.protobuf.Any":
		return "unknown"
	case "google.protobuf.ListValue":
		return "readonly unknown[]"
	default:
		return ""
	}
}

func tsMapKeyType(typeName string) string {
	switch typeName {
	case "bool", "string":
		return "string"
	default:
		return "string"
	}
}

func tsTypeName(fullName string) string {
	fullName = strings.TrimPrefix(fullName, ".")
	if known := tsWellKnown(fullName); known != "" {
		return known
	}
	segments := strings.FieldsFunc(fullName, func(r rune) bool {
		return !(unicode.IsLetter(r) || unicode.IsDigit(r))
	})
	for i, segment := range segments {
		if segment == "" {
			continue
		}
		runes := []rune(segment)
		runes[0] = unicode.ToUpper(runes[0])
		segments[i] = string(runes)
	}
	if len(segments) == 0 {
		return "Unknown"
	}
	return strings.Join(segments, "_")
}

func tsMethodName(value string) string {
	if value == "" {
		return "call"
	}
	runes := []rune(value)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func tsPropertyName(value string) string {
	if value == "" {
		return "field"
	}
	valid := true
	for i, r := range value {
		if !(unicode.IsLetter(r) || r == '_' || (i > 0 && unicode.IsDigit(r))) {
			valid = false
			break
		}
	}
	if valid {
		return value
	}
	return fmt.Sprintf("%q", value)
}
